### ISSUE TITLE
i am facing issue while running  docker command available in course 

### ISSUE THREAD

**Issue by nehamjhanwar** [The-OpenROAD-Project/OpenLane#1003]
Hi Team, 

i am facing issue while running  docker command available in course  
**same error permission denied and image missing openlane:current** 

 [Free VLSI Tutorial - VSD - A complete guide to install Openlane and Sky130nm PDK]
 (https://www.udemy.com/course/vsd-a-complete-guide-to-install-openlane-and-sky130nm-pdk/)

Of step3 docker **Final steps to install openlane toolchain  Video 7:23 to 8:58** 

**Error** this is image path 

6. [https://files.slack.com/files-pri/T01CTV637HS-F036SF3PFPU/image.png](https://files.slack.com/files-pri/T01CTV637HS-F036SF3PFPU/image.png)

[Free VLSI Tutorial - VSD - A complete guide to install Openlane and Sky130nm PDK](https://www.udemy.com/course/vsd-a-complete-guide-to-install-openlane-and-sky130nm-pdk/)
Another step towards freedom in IC design!! - Free Course (23 kB)

Thanks In Advance

**Comment by donn** [comment]
I can't access either the course you're mentioning nor the image you just posted. Sorry, not much we can do to help here. OpenLane is under active development, so the most surefire way to install it is to read the documentation.
