### ISSUE TITLE
Design reports after routing show technically-true, but practically-useless, utilization numbers

### ISSUE THREAD

**Issue by tdene** [The-OpenROAD-Project/OpenLane#1004]
### Description
During the implementation of any design, OpenLane will create a `reports` folder.
This `reports` folder has, among others, an area report.
The area report displays both raw area, as well as % utilization.

All routing and post-routing reports show 95%+ utilization due to the presence of filler cells.
This is technically true, but practically useless.

### Environment
```
Kernel: Linux v5.13.0-35-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.12 (OK)
OpenLane Git Version: 2022.02.21_02.33.47
pip:click: INSTALLED
pip:pyyaml: INSTALLED
pip:venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

e40929f 2022-02-20T10:29:53+02:00 ECO Flow Fix (#940) - donghl17 -  (HEAD -> master, tag: 2022.02.21_02.33.47, origin/master, origin/HEAD)
a7d97cc 2022-02-19T10:00:15+02:00 Update README.md (#939) - wale soyinka -  (tag: 2022.02.20_02.17.26)
58f206f 2022-02-18T16:02:03+02:00 Update Magic, Open_PDKS (#917) - Donn -  (tag: 2022.02.19_02.27.52)
```

### Reproduction Material
Implement any design through OpenLane and refer to the generated `reports/*/*area*` files.

### Expected behavior
Reported utilization should not include filler cells.

**Comment by maliberty** [comment]
This is because OL chooses to fill with decap cells not filler cells.  Filler cells are excluded but decaps are not fillers.  It is an OL decision and not a tool issue.  @donn

**Comment by kareefardi** [comment]
I don't think that is applicable anymore. I just checked the reports and utilization number seems to ignore both decap and fill cells. Perhaps that is happening since both have `CLASS CORE SPACER`. @maliberty If you think my interpretation is wrong and believe this might still be an issue please re-open it.
