### ISSUE TITLE
LVS error net mismatch

### ISSUE THREAD

**Issue by gncemre23** [The-OpenROAD-Project/OpenLane#1012]
### Description
While hardening the core, which has SRAM macro and another digital which is hardened separately without any error, I get the LVS error given below.
![image](https://user-images.githubusercontent.com/3584912/158961649-522897bc-c286-46d6-aa2c-e581472cdc8d.png)

### Environment
```
Kernel: Linux v5.11.0-49-generic
Distribution: ubuntu 21.04
Python: v3.9.5 (OK)
Container Engine: docker v20.10.7 (OK)
OpenLane Git Version: -dev
pip:click: INSTALLED
pip:pyyaml: INSTALLED
pip:venv: INSTALLED
---
PDK Version Verification Status: OK
```

### Reproduction Material
in the **[repository](https://github.com/Procenne-Digital-Design/secure-memory/tree/uart)**, I run the following command 
`flow.tcl -design user_project_wrapper -tag with_user_proj_0.5 -overwrite -disable_output`

### Expected behavior
No lvs error
### Logs
```
Please find the attached log file.
[29-user_project_wrapper.lef.log](https://github.com/The-OpenROAD-Project/OpenLane/files/8302756/29-user_project_wrapper.lef.log)
```

**Comment by d-m-bailey** [comment]
@gncemre23 Looks like you have a power short. Can you post your gds?

**Comment by gncemre23** [comment]
Sure! Please find the attached
[user_project_wrapper.gds.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/8306732/user_project_wrapper.gds.zip)
d

**Comment by d-m-bailey** [comment]
@gncemre23 Looks like your `user_proj_example` has met5 routing layers that are shorting with the `user_project_wrapper` power grid. Should be easy to see if you just display met5. Maybe set your max routing layer to met4.
<img width="520" alt="met5_shorts" src="https://user-images.githubusercontent.com/8349634/159095992-f488211e-f7b3-458e-ab1a-bda6d29db83d.png">

I don't believe this is an openroad issue and suggest the issue be closed.

**Comment by armleo** [comment]
Also you have typo here:
set ::env(VDD_NET) {vcdd1}
set ::env(GND_NET) {vssd1}

**Comment by Sukru-Uzun** [comment]
> @gncemre23 Looks like your `user_proj_example` has met5 routing layers that are shorting with the `user_project_wrapper` power grid. Should be easy to see if you just display met5. Maybe set your max routing layer to met4. <img alt="met5_shorts" width="520" src="https://user-images.githubusercontent.com/8349634/159095992-f488211e-f7b3-458e-ab1a-bda6d29db83d.png">
> 
> I don't believe this is an openroad issue and suggest the issue be closed.

Is this klayout?

**Comment by d-m-bailey** [comment]
Yes, klayout.

**Comment by Sukru-Uzun** [comment]
Can we observe that on the Openroad -gui ? I cannot import gds or lef files in openroad.

**Comment by gncemre23** [comment]
I realized that I did not set DESIG_IS_CORE parameter as 0 while hardening the user_proj_example macro. I guess that causes the tool is using met5 even if I set rt_max_layer as met4. Now, with this adjustment, I don't have any LVS errors.
Thank you @d-m-bailey
