### ISSUE TITLE
SKY130 DECAP12 is too dense on LI1. Proposed solution.

### ISSUE THREAD

**Issue by armleo** [The-OpenROAD-Project/OpenLane#1014]
### Prompt
I have very not dense design. DECAP12 has 80% coverage of the area, and since all spare locations have DECAP12, it means that I will always be above 40% maximal area for LI1.

### Proposal
My proposal would be to modify the filler insertion to limit how much of the area can be covered by DECAP12/DECAPS/Fillers.

Alternative: Use DECAP12 from efabless to workaround. It has sligtly less capacitance, but does not suffer from this problem.

Up to OpenLane to decide what to do.

**Comment by vijayank88** [comment]
@armleo A testcase will help to debug and analyse what best can be done.

**Comment by armleo** [comment]
The current Magic check does not validate the li1 density rule. Any design with low density and big die area (1mmx1mm) are enough to reproduce. Do you want me to create a design for openlane to test?

**Comment by vijayank88** [comment]
yes
