### ISSUE TITLE
Save SPEF file for all corners

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenLane#1020]
I'm doing STA of a design with macros, so need the SPEF files for all corners. We could either save all of them by default, or else add an option.

**Comment by donn** [comment]
That's in #978, just need to fix a couple designs...

**Comment by antonblanchard** [comment]
We are producing min/nom/max spef files, but we only copy the nominal one into the target directory:

```
        if { [info exists ::env(CURRENT_SPEF)] } {
                lappend arg_list -spef_path $::env(CURRENT_SPEF)
        }
```

**Comment by antonblanchard** [comment]
We are now creating SPEF files for all corners, but we still aren't copying it into `final/spef/*`. Having them is useful for things like hierarchical STA.
