### ISSUE TITLE
FP_PDN_AUTO_ADJUST should guarantee that it snaps to the manufacturing grid

### ISSUE THREAD

**Issue by tdene** [The-OpenROAD-Project/OpenLane#1050]
### Prompt
The `FP_PDN_AUTO_ADJUST` flag, as implemented [here](https://github.com/The-OpenROAD-Project/OpenLane/blob/master/scripts/tcl_commands/floorplan.tcl#L67) currently sets the pitch and offset of the power grid by dividing the core width and height by the hard-coded values 4 and 8.

While this is sufficient for currently-supported PDKs, it is not future-proof.

### Proposal
The method in question should get information about the manufacturing grid and use it to snap the power grid to the manufacturing grid.

More discussion on this topic, and implementation ideas, can be found in the comments of #1044.

**Comment by kareefardi** [comment]
`FP_PDN_AUTO_ADJUST` will be removed in the future
