### ISSUE TITLE
Getting KLayout Violation = -1 in OpenLane Flow.

### ISSUE THREAD

**Issue by harshithsn** [The-OpenROAD-Project/OpenLane#1060]
I am getting KLayout Violations as -1 in OpenLane Flow
How to Overcome this issue?

![k](https://user-images.githubusercontent.com/63975346/163708616-fdf9fd4e-0bf2-44ce-8c37-b21060391182.PNG)

**Comment by vijayank88** [comment]
@harshithsn 
share `openlane.log`, `cmds.log` and `config.tcl`

**Comment by donn** [comment]
There's no need. Klayout DRC is not currently available for the Sky130 PDK.

**Comment by donn** [comment]
Apologies: Slight correction, it's disabled by default as it takes immense compute power. `set ::env(RUN_KLAYOUT_DRC) {1}` in your design config if you'd like it.

**Comment by harshithsn** [comment]
@donn  Thank You Sir
