### ISSUE TITLE
questions towards edit .tlef file

### ISSUE THREAD

**Issue by YuetingLi666** [The-OpenROAD-Project/OpenLane#1066]
Hi openlane team, we are trying to feed our own generated std cells (still skywater 130nm) into the flow and wonder whether we could change .lef file.

Can we edit the SITE unit size part of the .tlef file as shown in the figure below (to adjust it into the same size as our generated std cells)? Such as add a SITE unithdtpl (high density, triple height), or just change the width/height value of SIZE width by height from default ones.

Or to say, we are recommended not to change .tlef file, and have to fit bbox of our generated standard cells exactly the same size of unithd or unithddb1. Which way would you recommend? Looking forward to your advice.
![image (12)](https://user-images.githubusercontent.com/68885578/164302103-3372c20f-d0e3-4fc1-8548-0132aa2c1e8e.png)

**Comment by vijayank88** [comment]
@YuetingLi666 
As per your slack channel conversation: https://skywater-pdk.slack.com/archives/C016H8WJMBR/p1650516094388809?thread_ts=1650480803.067309&cid=C016H8WJMBR

Add `PLACE_SITE` in OpenLane flow `config.tcl` to use your custom `-site` values as follows:
```
set ::env(PLACE_SITE) {unithd unithddb1}
```
