### ISSUE TITLE
Unable to run ./flow.tcl

### ISSUE THREAD

**Issue by saji87** [The-OpenROAD-Project/OpenLane#1077]
### Description

While running ./flow.tcl, the following error is displayed.

### Environment

```
--
>>make survey || python3 ./env.py issue-survey
python3 ./env.py issue-survey
Kernel: Linux v5.13.0-40-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: UNKNOWN vUNKNOWN (UNSUPPORTED)
OpenLane Git Version: 30f87f541d4e338b6793e46032350f26f64d8791
pip: INSTALLED
pip:venv: INSTALLED
---
>>docker --version
Docker version 20.10.0, build 7287ab3
```
PDK Version Verification Status: OK

### Reproduction
Run ./flow.tcl

### Expected Behaviour
Run normally

### Logs
```
>> ./flow.tcl
can't find package json
    while executing
"package require json"
    (file "/home/saji/projects/OpenLane/scripts/tcl_commands/all.tcl" line 15)
    invoked from within
"source /home/saji/projects/OpenLane/scripts/tcl_commands/all.tcl"
    ("package ifneeded openlane 0.9" script)
    invoked from within
"package require openlane"
    (file "./flow.tcl" line 26)
```
### Previous error
make test ran succesfully. However the docker repository needed to be hard coded in Makefile to pull it as it was empty (efabless/openlane:latest)

**Comment by vijayank88** [comment]
@saji87 
Can you please list the commands used before running `./flow.tcl`?
Seems you're not given `-design <Design_Name>`

Make sure followed below steps or follow it, it will resolve your issue.
```
cd OpenLane
make mount
./flow.tcl -design spm
```

**Comment by saji87** [comment]
My issue seems to be error in `OPENLANE_IMAGE_NAME` in Makefile. Somehow its empty. 

`ifeq ($(OPENLANE_IMAGE_NAME),)`
`OPENLANE_DOCKER_TAG ?= $(shell $(PYTHON_BIN) ./dependencies/get_tag.py)`
`ifneq ($(OPENLANE_DOCKER_TAG),)`
`export OPENLANE_IMAGE_NAME ?= efabless/openlane:$(OPENLANE_DOCKER_TAG)`
`endif`
`endif`
`

After hardcoding it to efabless/openlane the run is succesful

`[SUCCESS]: Flow complete.
[INFO]: Note that the following warnings have been generated:
..............................
`

May I ask what `THREADS ?= 1`  stands for in Makefile

**Comment by vijayank88** [comment]
Can you display?
`which python3`

**Comment by saji87** [comment]
`/usr/bin/python3`

**Comment by vijayank88** [comment]
You need to do following command before make mount:
```
OPENLANE_IMAGE_NAME=efabless/openlane:current make mount
```

**Comment by vijayank88** [comment]
Make sure `pyhton3` default points to `python3.8`

**Comment by saji87** [comment]
`>>make survey || python3 ./env.py issue-survey
python3 ./env.py issue-survey
Kernel: Linux v5.13.0-40-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)`

**Comment by vijayank88** [comment]
@saji87 
If your issue got fixed, you may close this issue.
