### ISSUE TITLE
RUN_SPEF_EXTRACTION=0 should skip run_spef_extraction

### ISSUE THREAD

**Issue by proppy** [The-OpenROAD-Project/OpenLane#1081]
### Description

setting `RUN_SPEF_EXTRACTION=0` doesn't seems to have any effect, see:
https://github.com/The-OpenROAD-Project/OpenLane/blob/b73708657657af6c1d7626ff8d390adc982627db/scripts/tcl_commands/sta.tcl#L90 

### Expected behavior

`run_spef_extraction` is skipped.

**Comment by vijayank88** [comment]
@proppy 
Have you used `set ::env(RUN_SPEF_EXTRACTION) 0` in this format?

**Comment by proppy** [comment]
@vijayank88 it doesn't seems that the variable is used at all: https://github.com/The-OpenROAD-Project/OpenLane/search?q=RUN_SPEF_EXTRACTION

**Comment by proppy** [comment]
fixed with #1089 ?

**Comment by vijayank88** [comment]
yes @proppy
