### ISSUE TITLE
generate configuration reference

### ISSUE THREAD

**Issue by proppy** [The-OpenROAD-Project/OpenLane#1088]
### Prompt

The following page often gets out of date w/ the change to the default TCL configs as shown in #1087:
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/configuration/README.md
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/regression_results/datapoint_definitions.md

### Proposal

It would be nice to find a way to autogenerate those, maybe some of the options listed in https://wiki.tcl-lang.org/page/Source+Documentation+Tools could be explored?

**Comment by donn** [comment]
Can you comment this in #1082?
