### ISSUE TITLE
allow separate padding for global & detailed placement

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenLane#1100]
### Prompt
Using a single padding value limits density and makes placement more difficult

### Proposal
In ORFS we have separate values for detailed and global [padding](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/1182d2619e25a721b0ce065d2221d298939e5989/flow/platforms/sky130hd/config.mk#L111):
```
export CELL_PAD_IN_SITES_GLOBAL_PLACEMENT ?= 1
export CELL_PAD_IN_SITES_DETAIL_PLACEMENT ?= 0
```
Whereas in OL you use a single CELL_PAD (default 4).  This makes both gpl & dpl use the same padding and makes it more difficult to accommodate added/upsized cells during resizing.   I suggest OL adopt a similar approach to ORFS.

**Comment by maliberty** [comment]
@antonblanchard FYI

**Comment by antonblanchard** [comment]
@maliberty sounds good. I also note that we only add padding to the right side, except for clock tree buffers and diodes, where we only add padding to the left side:

```
scripts/openroad/replace.tcl:set_placement_padding -global -right $::env(CELL_PAD)
scripts/openroad/opendp.tcl:set_placement_padding -global -right $::env(CELL_PAD)
scripts/openroad/resizer.tcl:set_placement_padding -global -right $::env(CELL_PAD)
scripts/openroad/resizer_routing_timing.tcl:# set_placement_padding -global -right $::env(CELL_PAD)
scripts/openroad/resizer_timing.tcl:set_placement_padding -global -right $::env(CELL_PAD)
```

```
scripts/openroad/cts.tcl:set_placement_padding -masters $buffers -left $::env(CELL_PAD)
scripts/openroad/diodes.tcl:set_placement_padding -masters $::env(DIODE_CELL) -left $::env(DIODE_PADDING)
scripts/openroad/groute.tcl:    set_placement_padding -masters $::env(DIODE_CELL) -left $::env(DIODE_PADDING)
```

I know it is unlikely to make much difference, but it is odd enough that I trip over it every few months and wonder what the rationale was.

**Comment by maliberty** [comment]
@antonblanchard I have no clue why - in ORFS we use balanced padding.

**Comment by vijayank88** [comment]
I like to make this changes in OpenLane What @maliberty suggesting.

For small design `CELL_PAD=4` works ok. For little complex designs its failing during DPL/GRT stage.

Most of the new user facing this issue and am pointing to change `CELL_PAD=2 or 1` which ever resolves the issue.

**Comment by maliberty** [comment]
To be clear I am hoping the OL team with implement this (@donn) not me

**Comment by antonblanchard** [comment]
I started looking at this. We aren't applying any padding during global placement because we are using the wrong interface:

```
set_placement_padding -global -right $::env(CELL_PAD)

if { $::env(CELL_PAD_EXCLUDE) != "" } {
    set_placement_padding -masters $::env(CELL_PAD_EXCLUDE) -right 0 -left 0
}

global_placement {*}$arg_list
```

For global placement padding we need to use `global_placement -pad_right $::env(CELL_PAD) ...`

That explains some of the detailed placement issues we've seen. Fixing this is going to mean almost every design will need a tweak to `PL_TARGET_DENSITY` however.

**Comment by maliberty** [comment]
@antonblanchard good catch!

**Comment by antonblanchard** [comment]
As expected, a lot of CI breakage with this fix: https://github.com/The-OpenROAD-Project/OpenLane/pull/1172

**Comment by vijayank88** [comment]
We need @donn  help here for metrics change?

**Comment by antonblanchard** [comment]
@vijayank88 the problem is any design with a `PL_TARGET_DENSITY` set near the limit is going to break with any value of padding. Reducing the values will help, although it may break some designs that relied on larger spacing in detailed placement to help with routing.

**Comment by donn** [comment]
> For global placement padding we need to use global_placement -pad_right $::env(CELL_PAD) ...

`-pad_right`? I thought we were balancing?
