### ISSUE TITLE
[ERROR]: during executing openroad script /openlane/scripts/openroad/droute.tcl [ERROR]: Exit code: 1

### ISSUE THREAD

**Issue by Ricardo-Ren** [The-OpenROAD-Project/OpenLane#1101]
[

### [STEP 21]
[INFO]: Running Detailed Routing...  the error is not very clear but it generates during the Detailed Routing
[INFO]: Running Detailed Routing...
[ERROR]: during executing openroad script /openlane/scripts/openroad/droute.tcl
[ERROR]: Exit code: 1
[ERROR]: full log: designs/zyNet/runs/RUN_2022.05.20_10.50.37/logs/routing/21-detailed.log
[ERROR]: Last 10 lines:
[INFO DRT-0019]   Complete 1500000 insts.
[INFO DRT-0019]   Complete 1600000 insts.
[INFO DRT-0019]   Complete 1700000 insts.
[INFO DRT-0019]   Complete 1800000 insts.
[INFO DRT-0019]   Complete 1900000 insts.
[INFO DRT-0019]   Complete 2000000 insts.
[INFO DRT-0019]   Complete 2100000 insts.
[INFO DRT-0019]   Complete 2200000 insts.
[INFO DRT-0019]   Complete 2300000 insts.
child killed: kill signal

### Environment
```
Please run the following set of commands in the OpenLane folder:

make survey || python3 ./env.py issue-survey

And copy and paste the ENTIRE output between the triple-backticks. Please do not gzip and upload the output.
Kernel: Darwin v21.4.0
Distribution: macOS 10.16
Python: v3.8.5 (OK)
Container Engine: docker v20.10.14 (OK)
OpenLane Git Version: 0dc6fb79c91082b94f8ded78d70f8bacbab96bf2
pip: INSTALLED
pip:venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)
If neither command succeeds, you are using an out of date version of OpenLane and should probably update. 
```

### Reproduction [[]()
[openroad_issue_reproducible1.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/8741832/openroad_issue_reproducible1.zip)another file is in below(because I can not upload file bigger than 25mb)
sue_reproducible1.zip…](
 tarball containing the relevant design.
* List the commands used to run the design.
  ./flow.tcl -design zyNet
If you see a message like `Reproducible packaged: Please tarball and upload <PATH> if you're going to submit an issue` in your logs, please also tarba

ll and include that path. This will greatly speed up the fixing process.

### Expected behavior
pass the process
### Logs
```
Add any relevant logs here. Please do ensure they're enclosed by the triple-backticks.
```

**Comment by Ricardo-Ren** [comment]
because I can not upload file bigger than 25 mb this is another part please upzip them togerther
[openroad_issue_reproducible 2.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/8741827/openroad_issue_reproducible.2.zip)
)

**Comment by vijayank88** [comment]
@Ricardo-Ren 
Child kill signal probably Out-of-Memory kill.
How much RAM do system have?

**Comment by vijayank88** [comment]
@Ricardo-Ren 
If its a MPW shuttle design mean share your updated repo link

**Comment by vijayank88** [comment]
With 128GB RAM and 32 core machine detail routing started running without any issues. see the log:

```
INFO DRT-0267] cpu time = 00:08:24, elapsed time = 00:01:42, memory = 9613.09 (MB), peak = 13323.21 (MB)
[INFO DRT-0187] Start routing data preparation.
[INFO DRT-0267] cpu time = 00:00:05, elapsed time = 00:00:05, memory = 10215.34 (MB), peak = 13323.21 (MB)
[INFO DRT-0194] Start detail routing.
[INFO DRT-0195] Start 0th optimization iteration.
    Completing 10% with 0 violations.
    elapsed time = 00:04:19, memory = 37676.21 (MB).
```

Close to 37GB RAM its takes to start routing

**Comment by vijayank88** [comment]
@Ricardo-Ren 
OpenROAD able to complete the routing with system resource:
```
[INFO DRT-0267] cpu time = 43:01:40, elapsed time = 02:49:15, memory = 43125.00 (MB), peak = 44779.61 (MB)
```
So try with above RAM/swap space will help you to complete the routing.
