### ISSUE TITLE
Issue launching "make test" to run OpenLane

### ISSUE THREAD

**Issue by ishfaqahmed29** [The-OpenROAD-Project/OpenLane#1110]
I'm getting the following error message. Do I need to reinstall Docker? 

![image](https://user-images.githubusercontent.com/34355989/170386526-38535e8a-4ced-412f-b302-b34549bf0310.png)

Thanks

**Comment by vijayank88** [comment]
@ishfaqahmed29 
From 2nd screenshot `make pdk` not completed. Try with `sudo make pdk`

Then try `sudo make test` or an other way try following command:
```
make mount
./flow.tcl -design spm
```

**Comment by ishfaqahmed29** [comment]
Hi @vijayank88 

```
Linux, 20.04.1-Ubuntu: Python 3.8.10: Docker version 20.10.14, build a224086349
```

I tried <mark>sudo make pdk</mark>, and then <mark>sudo make test</mark> 

![image](https://user-images.githubusercontent.com/34355989/170493861-986dc99d-f9eb-4247-8f8e-d825bda9b3f4.png)

**Comment by vijayank88** [comment]
@ishfaqahmed29 
You have permission issue.

Just install `OpenLane` where user have `read/write` access.

After successfull installation try
```
make mount
./flow.tcl -design spm
```
