### ISSUE TITLE
 make test does not work correctly / .flow.tcl does not work correctly

### ISSUE THREAD

**Issue by OmurCeran** [The-OpenROAD-Project/OpenLane#1120]
Hello,
When I make `sudo make test` at linux mint 20.3 after installing openlane, I gave error at below.
![image](https://user-images.githubusercontent.com/20382793/171693522-fdbc7d19-3dbf-4615-86d0-b669321100ba.png)

How can I solve this?
There is file in home/openlane/openlane/pdks/sky130A/libs.tech/openlane/config.tcl but it is not read by openlane, why

**Comment by vijayank88** [comment]
@OmurCeran 
Try following way:
```
make mount
./flow.tcl -design spm
```

The above executed by short `make test`

**Comment by OmurCeran** [comment]
I tried it as you said but it is same also.
![image](https://user-images.githubusercontent.com/20382793/171793027-b614d49d-1d19-445f-b714-2cbd6233de4d.png)

It did not solve problem actually.

**Comment by vijayank88** [comment]
@OmurCeran 
Execute below command and post here:

```
Please run the following set of commands in the OpenLane folder:

make survey || python3 ./env.py issue-survey

And copy and paste the ENTIRE output between the triple-backticks. Please do not gzip and upload the output.

If neither command succeeds, you are using an out of date version of OpenLane and should probably update. 
```

**Comment by vijayank88** [comment]
From the  screenshot Openlane version shows rc7 looks very old.

https://github.com/The-OpenROAD-Project/OpenLane#prerequisites do a fresh installation in new path and let us know

**Comment by OmurCeran** [comment]
When I make `make`, it gives me error as shown first figure.
![image](https://user-images.githubusercontent.com/20382793/171811485-8182782d-4ef2-498c-b4e8-dc45f44902e1.png)
However also docker was installed before.
You can see it at second figure.
![image](https://user-images.githubusercontent.com/20382793/171811634-dc4eca26-bbb1-4ec4-b2cd-3c1a1e9ff8a3.png)

**Comment by vijayank88** [comment]
@OmurCeran 
`Container Engine: UNKNOWN` from your survey
Try to remove previous docker and re-install latest version.

**Comment by OmurCeran** [comment]
I tried to install docker by using https://docs.docker.com/engine/install/ubuntu/ this. But it gives me error at below.
![image](https://user-images.githubusercontent.com/20382793/171831409-12fcee11-923f-49b7-be16-d8555b613672.png)

**Comment by vijayank88** [comment]
@OmurCeran 
Follow this instruction : https://computingforgeeks.com/install-docker-and-docker-compose-on-linux-mint-19/

**Comment by vijayank88** [comment]
Inside docker magic already installed. Just use `magic <path to>/spm*.mag

**Comment by vijayank88** [comment]
so spm test completes successfully. Installation working fine, so closing this issue. For other issue, open a new issue.
