### ISSUE TITLE
SDC constraints likely too conservative

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenLane#1124]
@jjcherry95 pointed out some issues with default SDC file in Openlane, so I thought I'd go through all the timing settings:

- `set_clock_uncertainty $::env(SYNTH_CLOCK_UNCERTAINITY) [get_clocks $::env(CLOCK_PORT)]`

The comment on this setting is wrong:

`| SYNTH_CLOCK_UNCERTAINITY  | Specifies a value for the clcok uncertainity in the pre-CTS stages. <br> (Default: 0.25) |`

It doesn't get applied only in the pre-CTS stages as this comment suggests, and post CTS it seems to be another way to specify slack margin (perhaps to account for clock jitter? I'm not sure).

pre-CTS it seems to be a way to communicate clock skew to STA, so I guess it has value. What should we do? One option is to only apply this pre CTS (seems like this was the original intention).

- `set_clock_transition $::env(SYNTH_CLOCK_TRANSITION) [get_clocks $::env(CLOCK_PORT)]`

This does appear to only be used pre CTS, and is replaced by actual STA data post CTS. STA looks to default to 0 if this is not set, and Openlane is setting it to 0.15, which seems reasonable to me.

- `set_timing_derate -early [expr {1-$::env(SYNTH_TIMING_DERATE)}]` and `set_timing_derate -late [expr {1+$::env(SYNTH_TIMING_DERATE)}]`

Since we are already doing multi corner STA, this seems to be a way to further derate past those corners. Considering we aren't confident about some of the sky130 liberty and RCX data, it makes sense to add a derating factor.

- `repair_design -slack_margin`

Not part of the SDC, but related to timing. This is more to account for variations between the pre RCX parasitic capacitance estimates and the RCX data, vs derating timing i would say.

**Comment by donn** [comment]
I fixed the documentation issue but frankly I'm unsure what's actionable about the rest. I'll re-open this issue if you have any further concerns.
