### ISSUE TITLE
Can't find variable FP_IO_HLAYER

### ISSUE THREAD

**Issue by BYCakar** [The-OpenROAD-Project/OpenLane#1129]
### Description
Hi, when I run any design, in IO placement stage I encounter this error.
```
Error: ioplacer.tcl, 54 can't read "::env(FP_IO_HLAYER)": no such variable
[ERROR]: during executing openroad script /openlane/scripts/openroad/ioplacer.tcl
```
I checked config.tcl in the run directory, genuinely there is no FP_IO_HLAYER, and there are other missing variables as well. I guess at the very beginning of the flow these variables are not in the environment somehow, but I could not find where it causes from.

### Environment
```
make: *** No rule to make target 'survey'.  Stop.
Kernel: Linux v5.13.0-44-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.7 (OK)
OpenLane Git Version: -dev
pip:click: INSTALLED
pip:pyyaml: INSTALLED
pip:venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

e4bfdd7 2022-02-22T16:59:14-03:00 Remove pip install, no longer needed (#953) - Vitor Bandeira -  (grafted, HEAD, tag: 2022.02.23_02.50.41)
```

### Reproduction Material
```
[manual_macro_placement_test.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/8847065/manual_macro_placement_test.tar.gz)
[openroad_issue_reproducible.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/8847067/openroad_issue_reproducible.tar.gz)
```

**Comment by vijayank88** [comment]
@BYCakar 
Please update OpenLane image to latest [2022.06.06_01.36.41](https://github.com/The-OpenROAD-Project/OpenLane/releases/tag/2022.06.06_01.36.41) will resolve this issue.

You're using 2022-02-22 tag still.

**Comment by BYCakar** [comment]
I made the setup via caravel_user_project repository, which has 2022-02-22 tag. I tried to update openlane, but I got a pdk version mismatch error. I couldn't be sure if there will be a problem with caravel_user_project, when I update pdk too. If it won't be a problem I will update openlane.

**Comment by vijayank88** [comment]
@BYCakar 
https://github.com/efabless/caravel_user_project/blob/main/Makefile update this file based on commit from https://github.com/The-OpenROAD-Project/OpenLane/blob/master/dependencies/tool_metadata.yml and re-install OpenLane, it should not throw mismatch error

**Comment by BYCakar** [comment]
I am just changing the commit id's in Makefile according to YML file, right? Is there any other changes to be done in makefile?

**Comment by vijayank88** [comment]
@mattvenn  
Any suggestion to merge latest OpenLane commits to caravel flow?

**Comment by mattvenn** [comment]
did you mean to ask me @vijayank88 ? I don't have any opinion on this.

**Comment by BYCakar** [comment]
By the way, I've found from where the problem causes. Two weeks ago I've installed docker image for OpenRAM, which uses the same pdk directory, comes out it made some changes and deleted some variables from the environment. So OpenLane can't find these variables and throws an error.

**Comment by vijayank88** [comment]
@BYCakar See my comment
```
Its should come from default configuration setup. In your case how its missing don't know.
```
Anyway you traced what you did...
Consider closing this as resolved?
