### ISSUE TITLE
Potentially better lef handling

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenLane#1135]
### Prompt
Openlane merges multiple lefs into a single lef to be used in multiple step in the flow. 

### Proposal
I believe today openroad handles properly reading separate lef files. On the one hand avoiding merging would save space during development, on the other hand there is an effort to convert merging into reading multiple lefs in the source code and there are other tools that might need a lef merge.

This is a low priority. It is merely for tracking a potential enhancement.

**Comment by donn** [comment]
Fixed in OpenLane 2.
