### ISSUE TITLE
Thin areas of sky130 met1 rails have no tap cells

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenLane#1140]
I wanted to see how OpenROAD handles very small areas between the perimeter of the core area and placed macros. I took a working design (40um macro halo with the macros 40um in from the left and right edges), and changed to a 20um halo, such that we have 20um of space for met1 rails. The design went from passing LVS to failing.

Although I haven't root caused it to the PDN stage, I do see some strange things. Firstly there are areas where some met4 straps appear to be missing:

![met4_pdn](https://user-images.githubusercontent.com/2029971/168944328-0119caaa-2874-4871-a7ca-f1956e8bf3df.png)

Another question is how these small areas between the perimeter of the core and macros should be handled (should we avoid placing met1 rails or add met4 straps that are closer spaced than our PDN config to power it).

It looks like we run a met4 strap very close to the other one in order to power it:

![met4b](https://user-images.githubusercontent.com/2029971/168944776-f8fc1e4b-92af-4c96-b508-7b7ee100ab64.png)

Test case: 
[pdn.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/8712941/pdn.tar.gz)

**Comment by maliberty** [comment]
@RTimothyEdwards I've moved this to OL as it is a setup issue not a tool issue.  I think the OL team should address this.

**Comment by kareefardi** [comment]
I don't see a problem here too with regards to the original issue.

> > There is no problem here. You have set the decap as your endcap and they are within the 13um tapcell dist. The only issue is choosing decap as a endcap which it is not really.
> 
> ```
> # welltap and endcap cells
> set ::env(FP_WELLTAP_CELL) "sky130_fd_sc_hd__tapvpwrvgnd_1"
> set ::env(FP_ENDCAP_CELL) "sky130_fd_sc_hd__decap_3"
> ```
> 
> @RTimothyEdwards should we be using something other than `decap_3` for the endcap cells? (eg something with a tap)

If you would like to explore that more, please open a new issue.
