### ISSUE TITLE
Unable to launch flow.tcl in local installation

### ISSUE THREAD

**Issue by titan73** [The-OpenROAD-Project/OpenLane#1144]
After worked around the pyinstaller problem (version 4.1 to use instead of latest 5.1) I managed to run the installl script
python3 ./env.py local-install.
According to the doc at https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/local_installs.md,
I should just do ./flow.tcl but I get:

ERROR]: run_non_interactive_mode missing required -design

    while executing
"parse_key_args "run_non_interactive_mode" args arg_values $options flags_map $flags -no_consume"
    (procedure "run_non_interactive_mode" line 10)
    invoked from within
"run_non_interactive_mode {*}$argv"
    invoked from within
"if { [info exists flags_map(-interactive)] || [info exists flags_map(-it)] } {
    if { [info exists arg_values(-file)] } {
        run_file [file nor..."
    (file "./flow.tcl" line 384)

If I use /flow.tcl -design spm, it does not work either with:

[INFO]: Using design configuration at /home/titan/eda/ol/designs/spm/config.tcl
[INFO]: Sourcing Configurations from /home/titan/eda/ol/designs/spm/config.tcl
[ERROR]: PDK_ROOT is not specified. Please make sure you have it set.

    while executing
"prep {*}$args"
    (procedure "run_non_interactive_mode" line 11)
    invoked from within
"run_non_interactive_mode {*}$argv"
    invoked from within
"if { [info exists flags_map(-interactive)] || [info exists flags_map(-it)] } {
    if { [info exists arg_values(-file)] } {
        run_file [file nor..."
    (file "./flow.tcl" line 384)

**Comment by donn** [comment]
That's uh. I mean you can invoke flow.tcl with the same arguments as inside the Docker container.

As for PDK_ROOT, you do need to set that separately, in addition to using a tool like [volare](https://github.com/efabless/volare) to get the PDK installed. 

We'll update the documentation to reflect all of that.

**Comment by titan73** [comment]
Ah yeah indeed. Option -design is needed. I just followed blindy the doc at https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/local_installs.md.

Ok thanks. I will try once the doc is updated.
