### ISSUE TITLE
Need signoff_issue_reproducible script

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#1153]
### Prompt
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/scripts/or_issue.py will generate `openroad_issue_reproducible` for `floorplan to routing` stage.

Readme file: https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/using_or_issue.md

During `signoff` stage, if there is failure during LEF vs LVS, magic DRC error etc, there is no script to produce test case for attachment.

### Proposal

For beginners it will be easy to file a git hub issue with proper test case by using issue generator script.

**Comment by donn** [comment]
#1154 adds this to magic scripts, including DRC and LVS, but I have no immediate interest in adding this to more and more tools. It's diminishing returns at that point to add to tools like yosys and netgen which are only used once in the entire flow.
