### ISSUE TITLE
Use .odb rather than .def between OR steps

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenLane#1159]
### Prompt
Between steps using openroad the intermediate files should be a .odb rather than a .def.  We are storing additional information that can't be represented in def (guides, hierarchy, etc).  ORFS has already made the switch as a reference.

### Proposal
Use read_db / write_db rather than read_def / write_def

**Comment by donn** [comment]
This has been proposed before. I'd like to do it, but then I'd have to account for "contamination" for if the DEFs are manipulated outside of OpenROAD. But it would be good not just for the additional information, but also just for performance reasons.

**Comment by maliberty** [comment]
If required you could always write_def and read_def for outside manipulation.  Better would be to rewrite such as an openroad tcl using the odb apis instead.

Should I take your comment as a rejection or just a concern?

**Comment by donn** [comment]
Concern. It's definitely planned. Just that it's going to be quite a lift.
