### ISSUE TITLE
Disable resizer_routing_timing if Post CTS resizer timing met

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#1167]
### Prompt
Disable the `run_resizer_routing_timing` before routing.

Because for complex design by default running resizer timing again post cts is time consuming task, if timing already met.

### Proposal
Check for post cts `resizer.log`. At the end of log `wns 0.00` mean skip `run_reszier_routing_timing`.

If there are negative values wrt., wns in log file enable `run_resizer_routing_timing` in https://github.com/The-OpenROAD-Project/OpenLane/blob/83b61459abcaef3b0ddcf022e1a67e71c88f6007/scripts/tcl_commands/routing.tcl#L416

**Comment by antonblanchard** [comment]
@vijayank88 Just checking that wns is 0 doesn't ensure that the design is meeting the hold and slack margins we are asking for. We'd probably want to check the design against `GLB_RESIZER_HOLD_SLACK_MARGIN` and `GLB_RESIZER_SETUP_SLACK_MARGIN`

**Comment by vijayank88** [comment]
@antonblanchard 
With recent OpenLane flow i am seeing designs which are failing routing congestion too high error during `run_resizer_routing_timing`.

For one of the design its took 30 hour run time and failed during resizer timing, its not having any macros inside.

**Comment by vijayank88** [comment]
@antonblanchard 
this is the design.  https://github.com/The-OpenROAD-Project/OpenLane/issues/1126#issuecomment-1159340997
Number of leaf instances 659k

**Comment by antonblanchard** [comment]
@vijayank88 that's a pretty big design to expect it to work without a fair bit of tuning.
