### ISSUE TITLE
DPL failed 

### ISSUE THREAD

**Issue by MohamedAliYounis** [The-OpenROAD-Project/OpenLane#1186]
### Description
Hello,
I have a problem in DPL, I tried to change all insertion diode strategies and change the cell pad value and it didn't work.
config.tcl and macro_placement.cfg and openroad_issue_reproducible are attached

[openroad_issue_reproducible.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/9046965/openroad_issue_reproducible.zip)

[config.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/9046992/config.zip)

![image](https://user-images.githubusercontent.com/47182179/177347049-ee61d4e6-a86d-48a4-9b63-786a039ffd97.png)

**Comment by vijayank88** [comment]
@MohamedAliYounis 
Missing issue template
Please run the following set of commands in the OpenLane folder:

`make survey || python3 ./env.py issue-survey`

**Comment by vijayank88** [comment]
@MohamedAliYounis 
1. macro placement configuration wrong. its placed outside core area
![dpl-error1](https://user-images.githubusercontent.com/85787913/177372171-992897f4-52d7-41df-b102-ba0a7a29e343.png)
2.Placement density looks high. relax the placement density
3. Increase the core utilization (CORE_UTIL)

**Comment by donn** [comment]
Staled out.
