### ISSUE TITLE
Included designs not working with sky130B

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenLane#1202]
### Description

PDK=sky130B
make mount
./flow -design spm # fails with a floorplan error

I haven't uploaded a reproducible because I quickly worked out the issue.
The configs usually include another file that sets up density:

```
set filename $::env(DESIGN_DIR)/$::env(PDK)_$::env(STD_CELL_LIBRARY)_config.tcl
```

So if PDK is set to sky130B, then there are no config files found.
copying the sky130A config and changing the name to sky130B resolves the issue.

**Comment by donn** [comment]
Can be done easily enough- new functionality would have to be added to the JSON files to support this, though. I'll take a look.
