### ISSUE TITLE
Are there any instructions on how to write config.tcl?

### ISSUE THREAD

**Issue by RanChenRivai** [The-OpenROAD-Project/OpenLane#1203]
I having trouble writing config.tcl because I`m a novice. Are there any instructions on how to write config.tcl? I have no ideas about what env variables I should set.

**Comment by donn** [comment]
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/configuration_files.md

For MPW-7, ignore the JSON section and just take a look at the Tcl section.
