### ISSUE TITLE
Max fanout Limit ?

### ISSUE THREAD

**Issue by AdhithyanHaridas** [The-OpenROAD-Project/OpenLane#1206]
Hello,
My design had max fanout violations. The following image shows default fanout limit is set to 5
![image](https://user-images.githubusercontent.com/61611374/179073064-99132c96-4e76-44cd-adef-5e9d5abce023.png)

I increased the value of the variable "SYNTH_MAX_FANOUT" to 100 in my config and got no fanout violations. 
![image](https://user-images.githubusercontent.com/61611374/179073660-0816d03d-d8c6-410e-a1ab-010c6f0e9061.png)

Is it okay to exceed the default fanout limit to get timing clean ? or any suggestions ? 

Thanks

**Comment by maliberty** [comment]
At what step in the flow is this report from?  repair_design should fix these.

**Comment by AdhithyanHaridas** [comment]
The report is from signoff.
FYI, 
The first image is from a run which completed the flow with warnings for max slew violations.

The second image is from a run which completed with no warnings. (SYNTH_MAX_FANOUT set to100)

**Comment by maliberty** [comment]
If you look at the net of _42984_/Y what are the fanouts?  I'm wondering if they are something specific like antenna cells or are real fanouts.

**Comment by antonblanchard** [comment]
Or perhaps the resizer has been turned off. @AdhithyanHaridas can you attach your config?

**Comment by vvvverre** [comment]
I found this thread after encountering a similar issue. I am new to ASIC design, having previously only done FPGA development, so I am not sure how to reduce the high fanout on these pins. Should it be done in my HDL code, through configuring OpenLane, or another way entirely?

This is the output I got in `reports/signoff/30-rcx_sta.slew.rpt`:
```
===========================================================================
 report_check_types -max_slew -max_cap -max_fanout -violators
============================================================================
max fanout

Pin                                   Limit Fanout  Slack
---------------------------------------------------------
clkbuf_4_3_0_wb_clk_i/X                   5     24    -19 (VIOLATED)
clkbuf_4_0_0_wb_clk_i/X                   5     22    -17 (VIOLATED)
clkbuf_4_1_0_wb_clk_i/X                   5     20    -15 (VIOLATED)
clkbuf_4_2_0_wb_clk_i/X                   5     20    -15 (VIOLATED)
clkbuf_4_6_0_wb_clk_i/X                   5     20    -15 (VIOLATED)
clkbuf_4_12_0_wb_clk_i/X                  5     16    -11 (VIOLATED)
clkbuf_4_5_0_wb_clk_i/X                   5     14     -9 (VIOLATED)
clkbuf_4_7_0_wb_clk_i/X                   5     14     -9 (VIOLATED)
clkbuf_4_8_0_wb_clk_i/X                   5     14     -9 (VIOLATED)
clkbuf_4_9_0_wb_clk_i/X                   5     14     -9 (VIOLATED)
clkbuf_4_10_0_wb_clk_i/X                  5     12     -7 (VIOLATED)
clkbuf_4_13_0_wb_clk_i/X                  5     12     -7 (VIOLATED)

<SNIP>

===========================================================================
max slew violation count 0
max fanout violation count 293
max cap violation count 0
============================================================================
````

Based on this thread I tried to increase SYNTH_MAX_FANOUT to 100, and got far fewer violations:
```
===========================================================================
 report_check_types -max_slew -max_cap -max_fanout -violators
============================================================================
max fanout

Pin                                   Limit Fanout  Slack
---------------------------------------------------------
_3629_/X                                100    116    -16 (VIOLATED)
_3759_/X                                100    116    -16 (VIOLATED)
_3589_/X                                100    104     -4 (VIOLATED)


===========================================================================
max slew violation count 0
max fanout violation count 3
max cap violation count 0
============================================================================
```

I have attached the `config.tcl` from the runs directory below:
[openlane_config.txt](https://github.com/The-OpenROAD-Project/OpenLane/files/9133760/openlane_config.txt)

> If you look at the net of 42984/Y what are the fanouts? I'm wondering if they are something specific like antenna cells or are real fanouts.

How would I be able to check this?

I would appreciate any advice or guidance you might be able to give me.

**Comment by maliberty** [comment]
re: How would I be able to check this?
I would open the design in the GUI and select the net by name.  The inspector will show you the fanouts. 
You could script it in tcl instead but that would require more knowledge.

SYNTH_MAX_FANOUT = 100 is a bad idea.  You got fewer violations but they are much worse.

**Comment by maliberty** [comment]
This is up to the OL team to set @donn @kareefardi but I think the current value of 5 is far too low.  max cap/slew are much more useful in general.

**Comment by maliberty** [comment]
I see it is set in [base.sdc](https://github.com/The-OpenROAD-Project/OpenLane/blob/master/scripts/base.sdc) to
```
set_max_fanout $::env(SYNTH_MAX_FANOUT) [current_design]
```
so it is really a control for synthesis.  OL carries that through the whole flow and it shows up at the end which I think is a bug in the flow.  There is really no need for it at the end of the flow as max cap & slew are more useful at that point.

It is likely ok to leave at 5 at synthesis time (though I'm not sure if it is beneficial or not).   I guess my opinion is clear but I don't control OL's checks.  I don't see anything to fix in OR.

**Comment by maliberty** [comment]
Counting the antenna diodes as fanout effectively reduces max fanout to 2.5 which is even more absurd.

**Comment by antonblanchard** [comment]
@vvvverre as @maliberty says, you want to pay more attention to the cap/slew violations. It looks like your fan out violations are in clock tree synthesis (which pays no attention to max fan out constraints anyway) and antenna fix up, which is done after the resizer fixes fan outs. Unless the fan out issues are causing cap/slew violations, I'd ignore it.

As far as a setting for SYNTH_MAX_FANOUT, the current value (5) is almost certainly too low, but due to various issues 100 will be problematic too. I'm trying to get the Openlane default bumped to 10 as an interim improvement.

**Comment by vvvverre** [comment]
Thanks everyone for the helpful answers. I'll start paying more attention to max cap / slew.
