### ISSUE TITLE
Update OpenROAD app to get JSON metrics features

### ISSUE THREAD

**Issue by vvbandeira** [The-OpenROAD-Project/OpenLane#1224]
### Prompt

OpenROAD now has improved support for JSON metrics.

### Proposal

Update OpenROAD app to the latest version to pick up code changes to support JSON metrics.
https://github.com/The-OpenROAD-Project/OpenROAD/pull/2047

**Comment by donn** [comment]
I can assure you assigning me things won't get them done any faster

**Comment by vijayank88** [comment]
@donn 
Is there any automated PR to pick latest OpenROAD commit and update OpenLane automatically?

**Comment by donn** [comment]
https://github.com/The-OpenROAD-Project/OpenLane/pull/1219

**Comment by donn** [comment]
However, I'm not going to merge automatic OpenROAD updates if things are broken, which they are.

**Comment by maliberty** [comment]
@donn what is the next action here?  I don't see any failures in #1219 except a build timeout

**Comment by donn** [comment]
@maliberty I need to build OR for ARM and upload it

**Comment by maliberty** [comment]
@donn You unassigned yourself so I wasn't clear who is taking ownership at this point.  Do you require anything from OR?

**Comment by donn** [comment]
Nope.
