### ISSUE TITLE
How to fix antenna violations ?

### ISSUE THREAD

**Issue by AdhithyanHaridas** [The-OpenROAD-Project/OpenLane#1231]
My design has Antenna violations, I tried the following
1. Increasing the target density
2. Used different floorplan
3. Tried different DIODE_INSERTION_STRATEGY
4. Incresed GRT_MAX_DIODE_INS_ITERS
5. Increased GRT_ANT_ITERS

After trying all the above. I was able to reduce the no. of antenna violations down to 119.
But not able to fix it completely. 

![image](https://user-images.githubusercontent.com/61611374/180628991-e9c7259d-6aa4-4f25-9bf5-1af06dddcbd4.png)

Any suggestions ?

**Comment by AdhithyanHaridas** [comment]
On the Skywater slack, @RTimothyEdwards mentioned that most violations are not worth fixing unless they exceed the ratio by 2x.

Considering that, out of 117 violated nets, only 42 nets are valid (more than 2x).

_Below is the snapshot from Antenna report, where net 55 exceeds the 2x ratio._
![image](https://user-images.githubusercontent.com/61611374/181607679-02548ac2-1f5e-481b-868e-96dcc5f9d7f0.png)


_Below is the snapshot from OpenRoad gui, net 55 has antenna connected to it._
![image](https://user-images.githubusercontent.com/61611374/181608211-03d127a2-8dd9-434b-984f-1952bb971c7a.png)


I checked all the 42 Violating nets, and they have antenna cells connnected.

Although all violating nets have antenna cells connected, why are they still reported as violations ?

@maliberty @antonblanchard @vijayank88

**Comment by maliberty** [comment]
It depends where the diode is placed.  You could have an issue in another part of the net that isn't connected to this diode when the violation occurs.

**Comment by maliberty** [comment]
It would be good to include a test case
