### ISSUE TITLE
difference between sky130A and sky130B

### ISSUE THREAD

**Issue by pengpeng-lian** [The-OpenROAD-Project/OpenLane#1232]
I know that the PDK library includes Standard Cell Libraries, but I don't know the difference between sky130A and sky130B?

**Comment by donn** [comment]
For more context, the OpenLane team refers to "sky130A" and "sky130B" as **variants** of the sky130 PDK. It's the same PDK, just with different optional modules included.

**Comment by donn** [comment]
Was just thinking that.

**Comment by pengpeng-lian** [comment]
> Was just thinking that.

Thank you very much for your answer, it was very useful to me and I hope to work with you next time! Would be great if there was some documentation somewhere that you could link to for questions like this.
