### ISSUE TITLE
Incorporate JSON metrics report from OpenROAD into OpenLane

### ISSUE THREAD

**Issue by ravi-varadarajan** [The-OpenROAD-Project/OpenLane#1236]
OpenROAD currently dumps out metrics in JSON format with the use of -metrics <metrics_file_name>. There are also dedicated tcl commands to dump out the area/timing/power metrics  which can be called during the various stages of the flow.

We would like to modify the OpenLane scripts to use the -metrics option when invoking OpenROAD and also update the tcl scripts to set the design stage and invoke the appropriate metrics reporting functions. Once the final stage is done, we will need a utility function like genMetrics.py in ORFS  to aggregate all of the metrics.

I can help answer any questions regarding the changes required

**Comment by dralabeing** [comment]
@ravi-varadarajan Thanks. Is there a document to refer to the tcl command usage?. Is this a general metrics reporting api- i.e can users independently invoke these scripts to generate/customize metrics reporting  outside of OpenLane for example?

**Comment by donn** [comment]
Tracked in #1607.
