### ISSUE TITLE
Hello, what are the exact parameters of the stage for '-from -to'? I am looking forward to your answer.

### ISSUE THREAD

**Issue by pengpeng-lian** [The-OpenROAD-Project/OpenLane#1258]
############################question#########################################
Hello, what are the exact parameters of the stage for '-from -to'? I am looking forward to your answer.

**Comment by vijayank88** [comment]
Its good to keep this in discussion tab: https://github.com/The-OpenROAD-Project/OpenLane/discussions

**Comment by vijayank88** [comment]
https://github.com/The-OpenROAD-Project/OpenLane#command-line-arguments explained here

**Comment by pengpeng-lian** [comment]
Thank you very much, it has solved my problem!
