### ISSUE TITLE
init_design_config creates directory in the wrong path

### ISSUE THREAD

**Issue by armleo** [The-OpenROAD-Project/OpenLane#1263]
### Description
When running:
```
./flow.tcl -design mem_1r1w -init_design_config
```
It creates `$OPENLANE_ROOT/openlane/mem_1r1w` instead of  `$OPENLANE_ROOT/designs/mem_1r1w`

### Environment
OpenLane installation from commit: 6ab944bc23688cae6dc6fa32444891a1e57715c8

### Reproduction Material
Not relevant

### Expected behavior
It creates `$OPENLANE_ROOT/openlane/mem_1r1w` instead of  `$OPENLANE_ROOT/designs/mem_1r1w`

### Logs

```
[SUCCESS]: openlane/mem_1r1w/config.json created with the default configuration. Please update the values as you see fit.
```

**Comment by vijayank88** [comment]
@armleo 
The latest version of flow updated to add new designs into OpenLane flow by using following command.
```
./flow.tcl -design <design_name> -init_design_config -add_to_designs
```
Can you try with above command and let us know, is still creating new `openlane` directory for adding `designs`?

**Comment by armleo** [comment]
@vijayank88 

Thanks for the response. Yeah, I assumed that the behavior stayed the same. But the documentation clearly states the behavior.
