### ISSUE TITLE
Routing Congestion Problem

### ISSUE THREAD

**Issue by Ali-Sabir2** [The-OpenROAD-Project/OpenLane#1268]
![Screenshot from 2022-08-16 10-50-58](https://user-images.githubusercontent.com/104711127/184819679-4457dccf-5b89-4c86-a9af-fa75a4914c3c.png)
Hi!
**I am facing routing congestion issue,**
I did change density and area multiple time but didn't get positive response.
Thanks

**Comment by vijayank88** [comment]
@Ali-Sabir2 
Missing issue template and Please package a standalone test case with https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/using_or_issue.md and attach here

**Comment by vijayank88** [comment]
From the screenshot its looks like out of memory kill. Please increase your swap space and run the flow again.

**Comment by donn** [comment]
Please use the issue template. Help us help you.
