### ISSUE TITLE
Add support for EXTRA_LIBS

### ISSUE THREAD

**Issue by armleo** [The-OpenROAD-Project/OpenLane#1273]
### Prompt
Liberty files can be used to improve the precision of macro I/O timings. In scrips `EXTRA_LIBS` is referenced but never defined.

### Proposal
Add  `EXTRA_LIBS` and support for it similar to `EXTRA_LEF`.

**Comment by armleo** [comment]
Update: It also needs to have LIBS for each corner. Maybe even it is worth to have multiple LIBS handling to handle many corner cases at the same time?

**Comment by donn** [comment]
Folding into #1325- if you want to discuss adding multiple corners for macro timing files, please file a new issue.
