### ISSUE TITLE
Shall use docker v2 API?

### ISSUE THREAD

**Issue by johnjohnlin** [The-OpenROAD-Project/OpenLane#1276]
### Description
In `test_manifest_exists` in `docker/utils.py`, the url yields 410 gone http response.

### Environment
```
python3 ./env.py issue-survey
Kernel: Linux v5.18.15-arch1-1
Distribution: arch rolling
Python: v3.10.5 (OK)
Container Engine: docker v20.10.17 (OK)
OpenLane Git Version: 57f3f21d6e1d0403a88d7a7973f7447597aae160
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: FAILED
/home/johnjohnlin/workspace/opensilicon/OpenLane/pdks/sky130A not found.
Traceback (most recent call last):
  File "/home/johnjohnlin/workspace/opensilicon/OpenLane/dependencies/verify_versions.py", line 72, in verify_versions
    raise Exception(f"{pdk_dir} not found.")
Exception: /home/johnjohnlin/workspace/opensilicon/OpenLane/pdks/sky130A not found.

Failed to verify sky130A.
---
Git Log (Last 3 Commits)

57f3f21 2022-08-18T13:38:05+02:00 Add Very Early support for GF180MCU + `open_pdks` Tweaks  (#1251) - Mohamed Gaber -  (HEAD -> master, origin/master, origin/HEAD)
c0be543 2022-08-16T16:47:08+02:00 Update OpenROAD (#1267) - Mohamed Gaber -  (tag: 2022.08.17)
7b15116 2022-08-15T18:27:17+02:00 Revamp Net Unbuffering (#1261) - Mohamed Gaber -  (tag: 2022.08.16)
---
Git Remotes

origin  https://github.com/The-OpenROAD-Project/OpenLane (fetch)
origin  https://github.com/The-OpenROAD-Project/OpenLane (push)
```

### Reproduction Material

Simply `make openlane` on a clean repo.

And I get an error message like this.

```
efabless/openlane-tools:cvc-d172016a791af3089b28070d80ad92bdfef9c585-centos-7-amd64 not found in the repository.
```

This is because that docker v1 API https://index.docker.io/v1/repositories/efabless/openlane-tools/tags/magic-f7df5e7c86fb47c5fd445c846afddc6fbabad6ae-centos-7-amd64 returns 410 gone.

Instead, I suggest to use v2 API, which is https://registry.hub.docker.com/v2/repositories/efabless/openlane-tools/tags/magic-f7df5e7c86fb47c5fd445c846afddc6fbabad6ae-centos-7-amd64 .

### Expected behavior
The url is valid, and I can pull the image.

### Logs
N/A

**Comment by donn** [comment]
Okay so, the date was September 5th according to this article https://www.docker.com/blog/docker-hub-v1-api-deprecation/ but they decided to… start early?

Thanks for the heads up. I'm on it.
