### ISSUE TITLE
Save multi corner SPEF files to output directory

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenLane#1302]
### Prompt
We create multi corner SPEF files, but only save the nominal one. This makes it difficult to do multi corner hierarchical STA, because the SPEF files have to be pulled from a build directory instead from the output spef directory.

### Proposal
Modify `save_views` to save away all SPEF files, and symlink DESIGN.spef to the nominal one.

**Comment by kareefardi** [comment]
Solved by #1414
