### ISSUE TITLE
`DIODE_INSERTION_STRATEGY` 4 `DIODE_PADDING`

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenLane#1328]
### Prompt
`DIODE_INSERTION_STRATEGY` `4` (and possibly `5`) isn't using padding specified by `DIODE_PADDING` during legalizing inserted diodes

### Proposal
All strategies should respect `DIODE_PADDING`

**Comment by donn** [comment]
Moot as of #1686.
