### ISSUE TITLE
Add MPW CI as a badge

### ISSUE THREAD

**Issue by tspyrou** [The-OpenROAD-Project/OpenLane#1330]
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/README.md should have a badge pointing to the MPW CI's created by Vijayan.

### Prompt
A clear and concise description of what shortcoming you feel OpenLane has.

**Comment by donn** [comment]
Why.

**Comment by tspyrou** [comment]
@donn Tim had asked me to create improved CI to help avoid OpenLane needing to use a release branch but instead work from the head. This can be one step in that direction. We could start with just one set of the MPW designs and set them to be required to pass when a PR is made.

**Comment by donn** [comment]
I'm not against the idea, but we need to discuss it first.
