### ISSUE TITLE
Containerless/Local Installations is missing

### ISSUE THREAD

**Issue by boboballu** [The-OpenROAD-Project/OpenLane#1332]
## Description

https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/local_installs.md file is absent.
## Expected behavior

There should be a valid document to guide the installation of OpenLane locally without Docker.

**Comment by donn** [comment]
@armleo Did you delete the local install guide?

**Comment by armleo** [comment]
We discussed removing it, as it is no longer supported, correct? As discussed, I removed it.

I am okay for it to return, it is not up to me to decide.
