### ISSUE TITLE
multiple conflicting drivers gives warning in synth and did not stop the flow

### ISSUE THREAD

**Issue by mbaykenar** [The-OpenROAD-Project/OpenLane#1334]
### Prompt
For mpw7 tapeout, I wrongly connected output of a module inside the top module to one of the bits of the io_in input signal. This gave warning in synth stage stating:

"13. Executing CHECK pass (checking for obvious problems).
Checking module user_project_wrapper...
Warning: multiple conflicting drivers for user_project_wrapper.\io_in [16]:
	port tdo_o[0] of cell core_region_i (mba_core_region)
	module input io_in[16]"

The tool did not stop until LVS stage

This causes waste of time since multiple drive should not be acceptable in RTL to continue on flow

### Proposal
Openlane should give error instead of warning in synth stage for multiple conflicting driver issue

**Comment by mattvenn** [comment]
Definitely a good enhancement
