### ISSUE TITLE
Many DRC errors and that the cell does not appear in the layout of magic, only the space

### ISSUE THREAD

**Issue by juan2175606** [The-OpenROAD-Project/OpenLane#1350]
I am using a modified skywater standard cell, when I write in openlane ./flow.tcl -design nmosc, I get 530 DRC errors and when I open the cell in magic, the space of this standard cell appears. Does anyone know how I can fix it?

(https://github.com/juan2175606/tristate5.git)
[42-drc.txt](https://github.com/The-OpenROAD-Project/OpenLane/files/9541714/42-drc.txt)
[drc.txt](https://github.com/The-OpenROAD-Project/OpenLane/files/9541715/drc.txt)

![solu_2](https://user-images.githubusercontent.com/82684670/189511219-4747735a-6f16-4553-992d-401bafeffb99.JPG)

**Comment by maliberty** [comment]
Based on slack discussion this is a problem with the design of the user's std cell variant.  The cuts do not align correctly in the power grid.
