### ISSUE TITLE
Broken links with latest README.md

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#1357]
## Description
Latest `README.md` contains broken links.

## Expected behavior
Update the links for respective `README.md`

## Environment

```
Kernel: Linux v3.10.0-1160.49.1.el7.x86_64
Distribution: centos 7
Python: v3.6.8 (OK)
Container Engine: docker v20.10.16 (OK)
OpenLane Git Version: d609968cca9ebc6aae6ba8ada9c16b1ed3ce4d0a
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

d609968 2022-09-06T04:48:37+02:00 Replace mismatches' environment variables with flags (#1316) - Mohamed Gaber -  (HEAD -> master, origin/master, origin/HEAD)
2d97f88 2022-09-04T12:29:33+02:00 [BOT] Update magic (#1308) - Openlane Bot -  (tag: 2022.09.05)
460d3d8 2022-09-02T11:20:08+02:00 [BOT] Update yosys (#844) - Openlane Bot -  (tag: 2022.09.03)
---
Git Remotes

origin	https://github.com/The-OpenROAD-Project/OpenLane.git (fetch)
origin	https://github.com/The-OpenROAD-Project/OpenLane.git (push)

```

## Reproduction Material

Check the following links:
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/README.md#adding-a-design
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/designs/README.md --> missing

https://github.com/The-OpenROAD-Project/OpenLane/blob/master/README.md#flow-configuration
https://github.com/The-OpenROAD-Project/OpenLane/blob/master/configuration/README.md --> missing

## Logs

```
YOUR LOGS HERE
```

**Comment by donn** [comment]
Readme completely overhauled.
