### ISSUE TITLE
`QUIT_ON_LVS_ERROR` warning

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenLane#1360]
### Prompt
When `QUIT_ON_LVS_ERROR`, openlane doesn't report any lvs errors at the end of the flow. 

### Proposal
The intention behind the variable (if not then it should be) is to bypass quitting when an lvs error is detected. However, this shouldn't prevent reporting lvs errors even with low verbose level.

**Comment by donn** [comment]
Addressed in OpenLane 2: https://openlane2.readthedocs.io/en/latest/reference/step_config_vars.html#layout-vs-schematic-error-checker
