### ISSUE TITLE
-init_desgn_config not working

### ISSUE THREAD

**Issue by IngYordiDelgado** [The-OpenROAD-Project/OpenLane#1363]
### Discussed in https://github.com/The-OpenROAD-Project/OpenLane/discussions/1336

<div type='discussions-op-text'>

<sup>Originally posted by **IngYordiDelgado** September  7, 2022</sup>
hi I'm trying to generate a new design in openlane i use the following command ./flow.tcl -design <design_name> -init_design_config for it, but it says the design doesn't exist, and if i create a folder with the name of the design inside the design folder, it says it have create the conf file but nothing is in there. I hope you can help me I'm just new to this.  </div>

**Comment by vijayank88** [comment]
Update OpenLane to latest commit and try. This issue already raised and resolved. #1323 

Right command to create new design is:
```
./flow.tcl -design spm_new -init_design_config -add_to_designs
```
