### ISSUE TITLE
[OpenSTA] : "report_annotated_check"  in SPEF Based STA returns none are annotated

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenLane#1368]
## Description
I am bit confused on the "report_annotated_check"  in SPEF Based STA. Even though tool not reported any issue while reading spef, but "report_annotated_check" return none are annotated ?  Is there is any know issue in SPEF based STA or I need additional command ?
<pre>% report_annotated_check -list_annotated
                                                          Not   
Check type                        Total    Annotated   Annotated
----------------------------------------------------------------
cell setup arcs                    2746           0        2746
cell hold arcs                     2746           0        2746
cell recovery arcs                 1078           0        1078
cell removal arcs                  1078           0        1078
----------------------------------------------------------------
                                   7648           0        7648
</pre>
I have even cross-check the OpenSta Example4: https://github.com/The-OpenROAD-Project/OpenSTA/blob/master/examples/example4.tcl
It also say's none are annotated ?
<pre>                                                          Not   
Check type                        Total    Annotated   Annotated
----------------------------------------------------------------
cell setup arcs                       3           0           3
cell hold arcs                        3           0           3
----------------------------------------------------------------
                                      6           0           6

Unannotated Arcs
 setup              r1/CK -&gt; r1/D 
 hold               r1/CK -&gt; r1/D 
 setup              r2/CK -&gt; r2/D 
 hold               r2/CK -&gt; r2/D 
 setup              r3/CK -&gt; r3/D 
 hold               r3/CK -&gt; r3/D 
</pre>

## Expected behavior
As tool not reported any warning during spef reading, expectation is complete annotation for all the timing arc

## Environment
<pre><font color="#4E9A06"><b>dinesha@lenovo-i3-10100-07IMB05</b></font>:<font color="#3465A4"><b>~/workarea/efabless/MPW-7/OpenLane</b></font>$ python3 ./env.py issue-survey
Kernel: Linux v5.15.0-46-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.17 (OK)
OpenLane Git Version: b6bacc9d1ab469917fda7ceea61ea3a18984b818
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

b6bacc9 2022-08-24T21:21:29+02:00 Build Script Fixes (#1283) - Mohamed Gaber -  (HEAD -&gt; master)
f0f6055 2022-08-24T19:36:18+02:00 Remove `-echo` flags from `read_sdc` (#1284) - Anton Blanchard -  ()
9452129 2022-08-20T13:41:59+02:00 Fix &apos;run_yosys&apos; invocation during -synth_explore (#1278) - meta -  ()
---
Git Remotes

origin	https://github.com/efabless/OpenLane.git (fetch)
origin	https://github.com/efabless/OpenLane.git (push)
</pre>

I am running sta in standalone mode and using latest sta tool
<pre><font color="#C4A000">commit 5bfddf45183b64374835175f905bee9008b4bc19 (</font><font color="#06989A"><b>HEAD -&gt; </b></font><font color="#4E9A06"><b>master</b></font><font color="#C4A000">, </font><font color="#CC0000"><b>origin/master</b></font><font color="#C4A000">, </font><font color="#CC0000"><b>origin/HEAD</b></font><font color="#C4A000">)</font>
Author: James Cherry &lt;cherry@parallaxsw.com&gt;
Date:   Mon Sep 5 21:28:47 2022 -0700

    read_sdf missing liberty seg fault
    
    Signed-off-by: James Cherry &lt;cherry@parallaxsw.com&gt;

<font color="#C4A000">commit bb50746f72ab112819570abce352684f9114f624</font>
Author: James Cherry &lt;cherry@parallaxsw.com&gt;
Date:   Mon Aug 22 12:39:54 2022 -0700

    issue 107 xor activity
    
    Signed-off-by: James Cherry &lt;cherry@parallaxsw.com&gt;
</pre>

## Reproduction Material
[exp1.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/9593146/exp1.tar.gz)

## Logs
[sta.log](https://github.com/The-OpenROAD-Project/OpenLane/files/9593149/sta.log)

**Comment by maliberty** [comment]
report_annotated_check is for SDF annotations not SPEF.
