### ISSUE TITLE
Documentation on whenever the variable is a list or a single item

### ISSUE THREAD

**Issue by armleo** [The-OpenROAD-Project/OpenLane#1385]
### Prompt
There are a lot of variables in the OpenLane configuration. One of them is CLOCK_PORT and CLOCK_NET. However, the documentation is missing in regards to whenever these variables are lists or one item.

Example of these issue is presented here: https://github.com/The-OpenROAD-Project/OpenLane/pull/1355#discussion_r974565343

### Proposal
Change the configuration documentation to include this information. Add documentation in regards to internal variables, if they are lists or not.

**Comment by donn** [comment]
Addressed in OpenLane 2: https://openlane2.readthedocs.io/en/latest/reference/common_flow_vars.html
