### ISSUE TITLE
Pre-built tarball unpacking is getting aborted after downloading.

### ISSUE THREAD

**Issue by tanishq104** [The-OpenROAD-Project/OpenLane#1386]
When I run the command:    "./openlane_script_wo_depends.sh"
Downloading pre-built tarball for 82d61e2c9c265c0f0e994233cd2d024c90adb45…  7… 
Unpacking…                                                                   … 

Aborted!
make: *** [Makefile:112: pdk] Error 1
cd /home/tanishq/Desktop/vsdflow/work/tools/openlane_working_dir/OpenLane && \
	docker run --rm -v /home/tanishq/Desktop/vsdflow/work/tools/openlane_working_dir/OpenLane:/openlane -v /home/tanishq/Desktop/vsdflow/work/tools/openlane_working_dir/OpenLane/designs:/openlane/install -v /home/tanishq/Desktop/vsdflow/work/tools/openlane_working_dir/OpenLane/pdks:/home/tanishq/Desktop/vsdflow/work/tools/openlane_working_dir/OpenLane/pdks -e PDK_ROOT=/home/tanishq/Desktop/vsdflow/work/tools/openlane_working_dir/OpenLane/pdks -e PDK=sky130A  --user 0:0 -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /root/.Xauthority:/.Xauthority --network host efabless/openlane:87173889682b67c490c96ded79b93aa2bb570a48-amd64 sh -c "./flow.tcl -design spm -tag openlane_test -overwrite"
OpenLane 87173889682b67c490c96ded79b93aa2bb570a48
All rights reserved. (c) 2020-2022 Efabless Corporation and contributors.
Available under the Apache License, version 2.0. See the LICENSE file for more details.

[ERROR]: Failed to compare PDKs.
/home/tanishq/Desktop/vsdflow/work/tools/openlane_working_dir/OpenLane/pdks/sky130A not found.
Traceback (most recent call last):
  File "/openlane/dependencies/verify_versions.py", line 72, in verify_versions
    raise Exception(f"{pdk_dir} not found.")
Exception: /home/tanishq/Desktop/vsdflow/work/tools/openlane_working_dir/OpenLane/pdks/sky130A not found.

[ERROR]: Please update your environment. OpenLane will now quit.
make: *** [Makefile:167: test] Error 255

**Comment by donn** [comment]
I don't know what `./openlane_script_wo_depends.sh` is and this does not adhere to the issue template.
