### ISSUE TITLE
[OpenSTA] Need command to show the statistic on inter-connect Timing arc/parasitic load by the the Spef

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenLane#1393]
This request raised based on Slack discussion with @tspyrou 

### Prompt
OpenSTA tool has option to show the annotated status for SDF reading, But Similar details are not available for SPEF reading.

% report_annotated_check -list_annotated
                                                          Not   
Check type                        Total    Annotated   Annotated
----------------------------------------------------------------
cell setup arcs                     2746           0        2746
cell hold arcs                        2746           0        2746
cell recovery arcs                 1078           0        1078
cell removal arcs                  1078           0        1078
----------------------------------------------------------------
                                             7648           0        7648

### Proposal
Looking for STA command to show the SPEF annotation status shows number of timing arc loaded/not loaded.

**Comment by tspyrou** [comment]
@dineshannayya I opened https://github.com/The-OpenROAD-Project/OpenSTA/issues/120 for this issue. I am closing this one since we can track it there.

**Comment by tspyrou** [comment]
I am reopening this since github automatically links the issues.

**Comment by jjcherry56** [comment]
openroad commit 91b326968 updates opensta to include the report_parasitic_annotation command
