### ISSUE TITLE
Google: Please update OpenLANE to OpenROAD HEAD for GF180MCU

### ISSUE THREAD

**Issue by QuantamHD** [The-OpenROAD-Project/OpenLane#1422]
### Prompt
OpenROAD has fixed a number of issues related to GF180MCU, and OpenLANE needs to update to take advantage of them.

### Proposal
Update OpenLANE to use OpenROAD head.

**Comment by vijayank88** [comment]
@QuantamHD 
https://github.com/The-OpenROAD-Project/OpenLane/pull/1303 PR CI metrics failing.
@maliberty fixing this in https://github.com/The-OpenROAD-Project/OpenROAD/issues/2346.
Once CI passes ready to merge.
