### ISSUE TITLE
What to do about the timing ECO flow?

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenLane#1424]
The current timing ECO flow is:

A. Untested in CI, Broken
B. sky130_fd_sc_hd-specific
https://github.com/The-OpenROAD-Project/OpenLane/blob/32da932761213af689f10088d671e1e3dc38f273/scripts/odbpy/eco.py#L87
C. Uses a clone of report.py, `scripts/report/report_routing.py`, which has gone out of sync for a couple of months now.

It appears UMich is no longer interested in maintaining the ECO flow, so I wonder what we should do about it. I'm leaning towards disabling it at the moment until the Core OL team has more time to rewrite it.

**Comment by vijayank88** [comment]
@antonblanchard 
Have you using currently `ECO_ENABLE` any of your design currently?
