### ISSUE TITLE
Synthesis strategy `DELAY4` produces bad netlist

### ISSUE THREAD

**Issue by marwaneltoukhy** [The-OpenROAD-Project/OpenLane#1430]
When trying to do synthesis with synthesis strategy `DEALY4` on `caravel_mgmt_core_litex`, macro `mgmt_core_wrapper` fails verification.

**Comment by kareefardi** [comment]
@marwaneltoukhy can you provide a passing netlist and a failing netlist. Maybe then we can run LEC on them.

**Comment by donn** [comment]
Staled out.
