### ISSUE TITLE
Custom PDK

### ISSUE THREAD

**Issue by ashkanr65** [The-OpenROAD-Project/OpenLane#1433]
### Prompt
Porting Custom PDk documentation lack a lot of information

### Proposal
Since OpenLane is capable of working with any custom PDK, the lack of documentation in this section, makes developers hard to create a custom PDK.

**Comment by hanm2019** [comment]
I have the same question. I am curious that how can I use a custom pdk instead of the 130nm pdk and what files should i prepare ?

**Comment by kareefardi** [comment]
@hanm2019 @ashkanr65 is something missing here? https://openlane.readthedocs.io/en/latest/for_developers/pdk_structure.html

**Comment by donn** [comment]
Staled out.
