### ISSUE TITLE
Update CVC to newer version

### ISSUE THREAD

**Issue by hpretl** [The-OpenROAD-Project/OpenLane#1443]
### Prompt
The currently used CVC version (d172016a791af3089b28070d80ad92bdfef9c585, v1.1.0, Oct/5/2021) fails to build on RockyLinux9, and requires a patch to a newer version for a correct build.

### Proposal
Please update CVC to a newer version, e.g., 6295fd962aa0fbd11937018867797d01aff17778 (v1.1.3, May/20/2022) works fine and builds correctly.

**Comment by donn** [comment]
I think #1440 could fix that presuming I could get it working

**Comment by donn** [comment]
Done
