### ISSUE TITLE
OpenRoad will add or_tools as a dependency

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenLane#1468]
### Prompt
We are adding a new build time dependency in the near future on or-tools.

### Proposal
Include it in your docker setup.   You can see our setup in https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/etc/DependencyInstaller.sh

**Comment by donn** [comment]
Thanks for the heads up

**Comment by vvbandeira** [comment]
@donn do you have an eta? We have merged the code, thus the dependency is required to build newer version of OR. Our nightly build of OL with the latest OR is failing due to the missing dependency.
