### ISSUE TITLE
How to change the pdk ?

### ISSUE THREAD

**Issue by radhe-2022** [The-OpenROAD-Project/OpenLane#1473]
Can anyone tell help to change the pdk from sky130 to gf180mcu??

**Comment by maliberty** [comment]
@proppy

**Comment by vijayank88** [comment]
@radhe-2022 
Follow below steps:
```
export PDK_ROOT=<absolute path to GF180 PDK >`
export PDK=gf180mcuC
make mount
```

**Comment by proppy** [comment]
Alternatively:
```
export PDK_FAMILY=gf180mcu # set environment variable for volare
export PDK=gf180mcuC # set environment variable for the rest of the toolchain
make
make test
```
should allow volare to resolve and download the new GF180MCU PDK.

See also https://caravel-user-project.readthedocs.io/en/latest/ for instructions on how to set up the caravel_user_project environment to submit a project to the recently announced GF-MPW0 Open MPW shuttle:
https://opensource.googleblog.com/2022/10/announcing-globalfoundries-open-mpw-shuttle-program.html

**Comment by radhe-2022** [comment]
What should be the directory of executing all this instructions??

**Comment by proppy** [comment]
@radhe-2022 fresh checkout of OpenLane, see https://github.com/The-OpenROAD-Project/OpenLane#installation-the-short-version

**Comment by radhe-2022** [comment]
I'm a beginner 
I followed..
launched terminal in home directory
>> git clone https://github.com/The-OpenROAD-Project/OpenLane.git
>> cd OpenLane
>> EXPORT PDK_FAMILY=gf180mcu
>> EXPORT PDK=gf180mcuC
>> sudo make
>> sudo make test


I exported the gf180 pdk but still after make command docker fetches sky130A pdk image

Please help if Im doing any blunder .. 

Thankyou @proppy @vijayank88

**Comment by vijayank88** [comment]
@radhe-2022 
Where GF180 pdk installed in your machine?

**Comment by proppy** [comment]
> launched terminal in home directory

Can you paste the full command outout?

> EXPORT PDK_FAMILY=gf180mcu
> EXPORT PDK=gf180mcuC

`export` should be in lowercase.


> sudo make
> sudo make test

`sudo` shouldn't be strictly required.

**Comment by radhe-2022** [comment]
Done..! Thankyou so much sir @proppy @vijayank88 

Heading towards my first design to get tapeout
