### ISSUE TITLE
Post routing timing not met with STA

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#1493]
Testing this design with GF180 PDK with Latest OpenLane flow.

Description:

The problem is design meets timing till global routing stage, but post routing its not met timing.

Global routing log:
```
===========================================================================
 report_tns
============================================================================
tns -28.20
tns_report_end
wns_report

===========================================================================
 report_wns
============================================================================
wns -1.06
wns_report_end
worst_slack

===========================================================================
 report_worst_slack -max (Setup)
============================================================================
worst slack -1.06

===========================================================================
 report_worst_slack -min (Hold)
============================================================================
worst slack 0.18
worst_slack_end
clock_skew

===========================================================================
 report_clock_skew
============================================================================
Clock clock
Latency      CRPR       Skew
_58809_/CLK ^
  12.52
_57348_/CLK ^
   3.84      0.00       8.69

clock_skew_end
==========================================================
```
Post routing Timing report:
```
===========================================================================
max slew violation count 130
max fanout violation count 3420
max cap violation count 39
============================================================================
check_slew_end
tns_report

===========================================================================
 report_tns
============================================================================
tns -29404.88
tns_report_end
wns_report

===========================================================================
 report_wns
============================================================================
wns -33.46
wns_report_end
worst_slack

===========================================================================
 report_worst_slack -max (Setup)
============================================================================
worst slack -33.46

===========================================================================
 report_worst_slack -min (Hold)
============================================================================
worst slack 0.20
worst_slack_end
clock_skew

===========================================================================
 report_clock_skew
============================================================================
Clock clock
Latency      CRPR       Skew
_58809_/CLK ^
  22.80
_57348_/CLK ^
   6.12      0.00      16.69

clock_skew_end
power_report
==============================================
```
Due to file size limit Test case uploaded here: 

Gloabl route timing report test case: https://slack-files.com/T01699QAZBQ-F046PFRL7G9-afec1c94e3
Post route timing report test case: https://slack-files.com/T01699QAZBQ-F046DAESGNQ-dc6600cb16

**Comment by vijayank88** [comment]
@RTimothyEdwards 
Can you please check this test case? 
Is this related RCX extraction? 
Help me for timing signoff

**Comment by tspyrou** [comment]
@RTimothyEdwards https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/flow/util/correlateRC.py can be used to read a set of spefs and generate a setRC.tcl which is accurate to the extractor used at the end of the flow.

**Comment by tspyrou** [comment]
@vijayank88  there have been several fixes to the PDK including one in the liberty from @quantumhd. Could you rerun this and report if its any better? There was a liberty cap issue.

**Comment by vijayank88** [comment]
@tspyrou 
I followed ORFS based PVT [corner](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/2fda96e4225f325f183e014ca3fe4347852d3359/flow/platforms/gf180/config.mk#L151)

By updating [config.tcl](https://github.com/RTimothyEdwards/open_pdks/blob/3af133706e554a740cfe60f21e773d9eaa41838c/gf180mcu/openlane/config.tcl#L17) to following PVT corner able to meet timing signoff without violations.
```
# Lib Files
set ::env(LIB_SYNTH) "$::env(PDK_ROOT)/$::env(PDK)/libs.ref/$::env(STD_CELL_LIBRARY)/liberty/$::env(STD_CELL_LIBRARY)__tt_025C_5v00.lib"
set ::env(LIB_FASTEST) "$::env(PDK_ROOT)/$::env(PDK)/libs.ref/$::env(STD_CELL_LIBRARY)/liberty/$::env(STD_CELL_LIBRARY)__ff_n40C_5v50.lib"
set ::env(LIB_SLOWEST) "$::env(PDK_ROOT)/$::env(PDK)/libs.ref/$::env(STD_CELL_LIBRARY)/liberty/$::env(STD_CELL_LIBRARY)__ss_125C_4v50.lib"
```

Also I've updated [Resizer optmization list](https://github.com/RTimothyEdwards/open_pdks/blob/3af133706e554a740cfe60f21e773d9eaa41838c/gf180mcu/openlane/config.tcl#L56) with `gf180mcu_fd_sc_mcu7t5v0__*_1` to avoid high net delay cells.

**Comment by maliberty** [comment]
@vijayank88 are you doing multi-corner signoff?

**Comment by vijayank88** [comment]
@maliberty Only typical corner is our focus.
Customer wants to use 3.3V library, but its failed with timing violations during signoff.
I tried with 5V library, now signoff stage passed without any violations.

**Comment by tspyrou** [comment]
@vijayank88 can you make a PR to openPDK with your config.tcl fix and tag me in it?

**Comment by QuantamHD** [comment]
@jeffdi @mkkassem heads up on a potential chip breaking issue.

**Comment by vijayank88** [comment]
@tspyrou 
I am not able to tag in open_pdks repo. Please check above PR link

**Comment by vijayank88** [comment]
By using latest GF180 PDK with 5V library able to meet timing during post routing for my design.
