### ISSUE TITLE
log showing manufacturability report has wrong path

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenLane#1541]
### Description

![image](https://user-images.githubusercontent.com/634220/205080849-fcf9566a-f9f2-47d6-8a41-0f3a4a83e9bd.png)

remove the ../ at the start so I can copy and paste the whole line easily and get the correct path

**Comment by mattvenn** [comment]
same for metrics

**Comment by donn** [comment]
The paths are always printed relative to your current working directory...

**Comment by mattvenn** [comment]
but they are wrong, that path doesn't exist. It's like it's prepending .. to the absolute directory
I'm running this command from /home/matt/work/asic-workshop/shuttle8/tinytapeout-02

**Comment by kareefardi** [comment]
This has to do with the makefile of caravel user project. I will have to check it

**Comment by donn** [comment]
Don't see what's actionable for OpenLane here. This has to do with how caravel user project mounts your home folder.
