### ISSUE TITLE
Allowing Wildcards in filenames

### ISSUE THREAD

**Issue by thesourcerer8** [The-OpenROAD-Project/OpenLane#1548]
### Description

In previous OpenLane versions with the TCL config files I was using wildcards with filenames, which was working properly:  
"EXTRA_LEFS": ["dir::../../cells/lef/*.lef"],

With the latest OpenLane version, it doesn't work anymore, I only get errors when trying, so I had to provide all the filenames in the config file as a workaround.

### Proposal

Please make sure that wildcards work again, if that is possible.

**Comment by donn** [comment]
We allow wildcards so long as in they are *inside* a directory referenced by an environment variable: `https://openlane.readthedocs.io/en/latest/reference/configuration_files.html#variable-reference` for more info. This is for security reasons.

A possible workaround is something like `"EXTRA_LEFS": "ref::$CELLS_DIR/lef/*.lef"` and then launching flow.tcl as follows:

```sh
export CELLS_DIR=/path/to/cells 
flow.tcl -design xxx -expose_env CELLS_DIR
```
