### ISSUE TITLE
[ERROR]: Failed to compare PDKs.

### ISSUE THREAD

**Issue by msaideroglu** [The-OpenROAD-Project/OpenLane#1556]

**Comment by msaideroglu** [comment]
Hi again. I'm facing another issue now. When I clone latest version of Openlane and run make test command, it successfully runs with Magic's recent version of 8.3.348. However when I run make mount on terminal, it clones additional docker images:
![Screenshot from 2022-12-07 14-14-42](https://user-images.githubusercontent.com/107807649/206165007-7d1240b1-65d2-4a03-98ca-4cb0048a4b35.png)
and I leave make mount environment and try to re-run make test command on terminal, it gives this error:
![Screenshot from 2022-12-07 14-15-50](https://user-images.githubusercontent.com/107807649/206165261-7da67811-b040-4e6a-971d-372abd363155.png)

**Comment by vijayank88** [comment]
```
python3 ./env.py issue-survey
```
Provide environment report to proceed further

**Comment by msaideroglu** [comment]
Kernel: Linux v5.15.0-56-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.21 (OK)
OpenLane Git Version: 235fa7a4a2872e779588919c58fc4fa32568e075
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: MISMATCH
The version of open_pdks used in building the PDK does not match the version OpenLane was tested on (installed: b8c6129fb60851c452a3136c2b8c603bb92cb180, tested: 35c7265f51749ad8d9fdbb575af22c7c8fab974e)
This may introduce some issues. You may want to re-install the PDK by invoking `make pdk`.
---
Git Log (Last 3 Commits)

235fa7a 2022-11-28T17:17:32+02:00 [BOT] Update PDK (#1516) - Openlane Bot -  (grafted, HEAD, tag: 2022.11.29)
---
Git Remotes

origin	https://github.com/The-OpenROAD-Project/OpenLane (fetch)
origin	https://github.com/The-OpenROAD-Project/OpenLane (push)

**Comment by vijayank88** [comment]
Update your OpenLane master with following commands and re-try:
```
git checkout master
git pull
make
``

**Comment by msaideroglu** [comment]
~/OpenLane$ git checkout master
error: pathspec 'master' did not match any file(s) known to git

**Comment by vijayank88** [comment]
Delete complete OpenLane directory or install in new directory location and follow steps from here: https://openlane.readthedocs.io/en/latest/getting_started/installation/installation_ubuntu.html#download-and-install-openlane

**Comment by msaideroglu** [comment]
I installed OpenLane. OpenLane's the last commit installs with Magic's recent version of 8.3.348 but when make mount runned it converts Magic's version to 8.3.331. Then my design flow is giving this error:
![Screenshot from 2022-12-07 16-03-32](https://user-images.githubusercontent.com/107807649/206186433-720ace12-4be0-458b-9e83-ab10950bd8e6.png)
[issue_reproducible.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/10176259/issue_reproducible.zip)

**Comment by vijayank88** [comment]
Its mean you want to update Magic version to latest and want to try right? 
Is that got fixed with upstream magic? or its new issue you're facing with your design?

**Comment by msaideroglu** [comment]
Yes it is fixed with upstream Magic and OpenLane did an update for it. However when I install OpenLane from master branch Magic's recent version comes. However when I run make mount, OpenLane dos additional docker image clones. Magic's version changes. I think there are disagreements between the last commit and the previous ones. You can see same issue in [https://github.com/The-OpenROAD-Project/OpenLane/issues/1531](url)

**Comment by donn** [comment]
This is a different issue and your issue form is invalid- please re-file.
