### ISSUE TITLE
OpenLane should verify VDD and GND nets exist

### ISSUE THREAD

**Issue by xobs** [The-OpenROAD-Project/OpenLane#1575]
### Description

OpenLane should verify that the nets defined in `GND_NETS` and `VDD_NETS` actually exist before using them, and that they match the names used in the current PDK. If these nets do not exist, a fatal error should be produced.

### Proposal

It may be possible to modify the Yosys script to check for nets that match these names as part of an early pass.

**Comment by kareefardi** [comment]
It is allowed to change `GND_NETS` and `VDD_NETS` to values other the one in the PDK. The result show be a layout whose power pins are named per these variables. If something else happens then likely there is a problem with macro hooks or power defines in the RTL.
