### ISSUE TITLE
OpenROAD tools with debugging symbols

### ISSUE THREAD

**Issue by thesourcerer8** [The-OpenROAD-Project/OpenLane#160]
Please provide the OpenROAD tools in 2 variants in the Docker container: Both with and without debugging symbols. And please make sure that they are always in sync, that they are functionally always exactly the same.
The goal is to have the flow using normally the tools without debugging symbols, and when a crash is detected to automatically switch to the version with the debugging symbols and try that step again to debug and report it.

**Comment by donn** [comment]
Given that local installs are now a thing and require you to bring your own OpenROAD application (see here https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/local_installs.md,) you can just do that to use OpenLane with an OpenROAD binary compiled with debug symbols.

I'm locking for this now.
