### ISSUE TITLE
-init_design_config puts the new design in the wrong place

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenLane#1602]
### Description

it should be in ./designs/<new design name>

instead it gets made in ./openlane/<new design name>

**Comment by mattvenn** [comment]
Also it doesn't make the src directory any more

**Comment by vijayank88** [comment]
@mattvenn 
Have you used `-add_to_designs` switch?
```
# JSON Configuration File
./flow.tcl -design <design_name> -init_design_config -add_to_designs

# Tcl Configuration File
./flow.tcl -design <design_name> -init_design_config -add_to_designs -config_file config.tcl
```
https://openlane.readthedocs.io/en/latest/usage/designs.html#adding-your-designs

**Comment by donn** [comment]
the behavior has been altered and the docs were updated.
