### ISSUE TITLE
Not able to upload issue reports larger than 25 MB

### ISSUE THREAD

**Issue by xobs** [The-OpenROAD-Project/OpenLane#1604]
The template for submitting a bug report instructs users to upload the issue report by compressing it as either a `.tar.gz` or as a `.zip` (https://github.com/The-OpenROAD-Project/OpenLane/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml#L43)

However, sometimes issues can be very large, and even the compressed report can exceed this issue (e.g. https://github.com/The-OpenROAD-Project/OpenLane/issues/1603).

The issue template should provide advice on acceptable alternatives, especially given that it emphatically states that the issue report is a requirement for submitting the issue.

Possible solutions include:

* Suggest a file hosting service that users should use
* Describe what alternatives are acceptable for splitting files
* Provide a Makefile target to compress and/or split issue reports into acceptable chunks
* Support additional file types with better compression, such as `.tar.xz`

**Comment by donn** [comment]
> Suggest a file hosting service that users should use
Some security/privacy concerns having OL devs click on random links… We don't mind if someone dumps something on Dropbox or Google Drive though but we kinda also don't want to codify that policy.
> Describe what alternatives are acceptable for splitting files
Anything that can be extracted with free and open source software, i.e. not RAR. I can add that to the issue form.
> Provide a Makefile target to compress and/or split issue reports into acceptable chunks
We used to have it automatically create a tgz file, but the reproducible being a best-effort; it didn't encourage people to inspect the folder content much before uploading it.
> Support additional file types with better compression, such as .tar.xz
Sadly a GitHub limitation. I much prefer `xz` myself.
