### ISSUE TITLE
`issue_reproducible` doesn't include everything required to reproduce an issue

### ISSUE THREAD

**Issue by xobs** [The-OpenROAD-Project/OpenLane#1624]
### Description

I'm not sure what's supposed to be included in the `issue_reproducible`, but while filing https://github.com/The-OpenROAD-Project/OpenROAD/issues/2758 I attached the `issue_reproducible` file in the hopes that it would help to narrow down the bug. Unfortunately, this file was missing some critical details that made it impossible for the team to reproduce the issue.

### Expected Behavior

The directory "issue_reproducible" should contain everything necessary to reproduce the issue.

### Environment report

```shell
Kernel: Linux v5.15.79.1-microsoft-standard-WSL2
Distribution: ubuntu 22.04
Python: v3.10.6 (OK)
Container Engine: docker v20.10.21 (OK)
OpenLane Git Version: 06b26813465d8745c2cdfe6605ac3233cef89dec
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: MISMATCH
The version of open_pdks used in building the PDK does not match the version OpenLane was tested on (installed: 0059588eebfc704681dc2368bd1d33d96281d10f, tested: 327e268bdb7191fe07a28bd40eeac055bba9dffd)
This may introduce some issues. You may want to re-install the PDK by invoking `make pdk`.
---
Git Log (Last 3 Commits)

06b26813 2023-01-11T17:40:47+02:00 Fix Netlist STA Reproducible + Update Docs (#1610) - Mohamed Gaber -  (HEAD, tag: 2023.01.12)
1ed36219 2023-01-11T15:58:54+03:00 set_def and sef_odb after padringer execution (#1614) - Kareem Farid -  ()
09e2095f 2023-01-11T10:21:07+02:00 Update KLayout + Script Tweaks (#1612) - Mohamed Gaber -  ()
---
Git Remotes

origin  https://github.com/The-OpenROAD-Project/OpenLane (fetch)
origin  https://github.com/The-OpenROAD-Project/OpenLane (push)
```

### Reproduction material

The issue can be reproduced by trying to debug `caravel-minimax`:

```
git clone -b global-routing-segfault --recurse-submodules https://github.com/xobs/caravel-minimax.git
cd caravel-minimax
. activate-caravel.sh
make setup
make minimax_rf
make mimi
```

This will generate an `issue_reproducible` due to the segfault, and that file does not seem to contain everything required to reproduce the issue.

### Relevant log output

```shell
> The reproducible doesn't contain the needed files I mentioned above.
```

**Comment by maliberty** [comment]
@donn can you get as it appears the issue script is missing files.
