### ISSUE TITLE
Hierarchical Area Report in Synthesis?

### ISSUE THREAD

**Issue by ghost** [The-OpenROAD-Project/OpenLane#166]
I am beginning to use `openlane` to prepare a design for the next open shuttle.  I am wondering, the area report is at the top level. Is there a way to do a hierarchical synthesis area report (shows full hierarchy, area for each module, hopefully in csv) so I can better understand my area?

**Comment by ax3ghazy** [comment]
This probably depends on https://github.com/efabless/openlane/issues/171 for now.
