### ISSUE TITLE
At first, didn't solve it but now `openroad -gui` works for me when mounting the image with --privileged switch. Thank you.

### ISSUE THREAD

**Issue by PisatiRaghavendraReddy** [The-OpenROAD-Project/OpenLane#1661]
At first, didn't solve it but now `openroad -gui` works for me when mounting the image with --privileged switch. Thank you.

_Originally posted by @yunuseryilmaz18 in https://github.com/The-OpenROAD-Project/OpenLane/issues/1525#issuecomment-1367747166_
            can you expand the full command

**Comment by donn** [comment]
Issue template
