### ISSUE TITLE
load timing data in gui.tcl

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenLane#1692]
### Description

When you run the flow with -gui the layout is loaded with the SDC & Liberty but no parasitics are loaded (or estimated).  

### Proposal

Load the spef parasitics if available or otherwise estimate some.  This will enable timing to be meaningfully used.

(I don't have time to work on this but hope someone will pick it up)

**Comment by donn** [comment]
Fixed in #1729
