### ISSUE TITLE
Klayout DRC integration

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenLane#1702]
### Description

Processes/PDKs have varying methods for defining their klayout deck(s) and different ways to invoke them.  

### Proposal

Just some ideas:
A long term solution would be requesting a specific interface from a PDK. 
A short term solution would be having an OL wrapper per PDK.

**Comment by mithro** [comment]
FYI - @proppy

**Comment by kareefardi** [comment]
@proppy are you doing similar work ?

**Comment by kareefardi** [comment]
Fixed by https://github.com/The-OpenROAD-Project/OpenLane/pull/2059
