### ISSUE TITLE
Error in Global routing stage

### ISSUE THREAD

**Issue by 18341A04A6** [The-OpenROAD-Project/OpenLane#1744]
### Description

In global routing stage, net not properly covered error is being shown.
![error2](https://user-images.githubusercontent.com/102498426/231430111-7dbb3ed6-722f-4098-bc76-9b05fd0ab662.png)

### Expected Behavior

Global routing should pass without errors

### Environment report

```shell
Google colab
```

### Reproduction material

[DWT.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/11210348/DWT.zip)

### Relevant log output

```shell
uploaded above
```

**Comment by vijayank88** [comment]
If the guidelines not followed it will closed without any response. Read carefully and update each column.

Which OpenLane commit you're working? it is missing in Environment setup.

`Reproduction material`, you should upload the `issue_reproducible` as a compressed file in `.zip` or `.tar.gz`

**Comment by 18341A04A6** [comment]
unable to download issue_reproducible . I am running openlane flow in google colab

**Comment by vijayank88** [comment]
Follow this instruction: https://predictivehacks.com/?all-tips=how-to-download-files-and-folders-from-colab

**Comment by 18341A04A6** [comment]
I updated and sent my files in zip format.

**Comment by vijayank88** [comment]
your zip file only has
```
DWT.ipynb
```

**Comment by kareefardi** [comment]
Closing this as stale. Please file a new issue if needed.
