### ISSUE TITLE
More Accurate IR Drop Report Values

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenLane#1749]
### Description

IR drop analysis currently assumes there's a power source across all edges of the design, which is unrealistic and results in comically low IR-drop values.

### Proposal

Power pads should be listed explicitly so that IR drop analysis is useful.

---

@mo-hosni Comments?

**Comment by kareefardi** [comment]
This should have been handled by addition of `VSRC_LOC_FILES` but lets wait when https://github.com/The-OpenROAD-Project/OpenLane/pull/2066 is merged

**Comment by maliberty** [comment]
Would you say more about this problem?  If you have pads then psm should try to use them as sources.

**Comment by donn** [comment]
The problem was we had no variable nor examples for `VSRC_LOC_FILES` - not really a problem with PSM per se. We've added an example. The PSM trying to use pads thing is news to us though.

@mo-hosni Have you tried that? Just including the padframe and no `VSRC_LOC_FILES`?
