### ISSUE TITLE
Head Maps Power Density 0.00 fW

### ISSUE THREAD

**Issue by Baungarten-CINVESTAV** [The-OpenROAD-Project/OpenLane#1752]
### Description

The OpenROAD -GUI Head Map Power DEnsity view shows 0.00 fW when loading .def and .lef files or when the .odb file is loaded

### Expected Behavior

1) Hardening a module with the OpenLANE workflow
2) Loading .def and .lef files in OpenROAD GUI
3) Showing the power density of Head Map

![0W_OpenROAD](https://user-images.githubusercontent.com/101527680/232257049-80e67ebd-862b-4728-8525-a439d7afe0ca.png)

### Environment report

```shell
N/A
```

### Reproduction material

[user_proj_example.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/11240861/user_proj_example.zip)

### Relevant log output

```shell
N/A
```

**Comment by vijayank88** [comment]
Can you check the log/report file, report_power it has?

**Comment by maliberty** [comment]
I'm guessing from:
![image](https://user-images.githubusercontent.com/761514/232266871-9603ac36-4b32-472d-9460-5af0f112021d.png)

that you haven't loaded the liberty files.

**Comment by Baungarten-CINVESTAV** [comment]
@vijayank88 and @maliberty thanks for your quick answer.

I'm running the OpenLANE flow with Caravel, and then i export the ".def"  and ".lef" file in to "OpenROAD-flow-scripts".

With your answers i noticed two thinks first, the power report will be 0 W if the module its composed only for sub modules. Second as Matt says probably i haven't loaded the liberty files, i just import to OpenROAD the ".def" and ".lef" file. 

I attached you two different files:

- Top module power report & OpenROAD Power Density view
![Screenshot from 2023-04-16 11-51-27](https://user-images.githubusercontent.com/101527680/232331927-822863cb-94c2-4c41-9df4-d877e42e4629.png)
[Power reports top module.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/11243021/Power.reports.top.module.zip)

- Sub module power report & OpenROAD Power Density view
![Screenshot from 2023-04-16 11-56-07](https://user-images.githubusercontent.com/101527680/232332167-e122dba4-15de-43b9-bd34-050e43fa5d68.png)

[Sub Module Power report.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/11243033/Sub.Module.Power.report.zip)

Now my question is how can i import those files ( liberty files) to OpenROAD-flow-scripts?

**Comment by vijayank88** [comment]
@Baungarten-CINVESTAV Seems you're using 2 months old OpenLane commit.
Update your OpenLane to latest and run the flow.
Power density information loaded with `.odb` file to view in gui. Nothing can be done with `.rpt` file.
Load `.odb` and check the results.

**Comment by Baungarten-CINVESTAV** [comment]
![Screenshot from 2023-04-19 22-49-16](https://user-images.githubusercontent.com/101527680/233261132-a7fcc923-6790-4b8d-b981-cb3eead6dca6.png)

I installed the newest version of OpenROAD & OpenLANE, then i ran the PPU OpenLANE example, and finally i exported opened the ".odb" with OpenROAD -GUI and i had the same result.

What could be the problem?

**Comment by vijayank88** [comment]
@Baungarten-CINVESTAV 
Follow below steps to view power density in OpenROAD GUI
```
% openroad
> read_liberty <path to>/sky130B/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
>read_db <path to>/routing/PPU.odb
>gui::show
```
From `Heat Maps > Power Density`  menu you can view expected results.

**Comment by Baungarten-CINVESTAV** [comment]
Thanks, it works for OpenLANE direct workflow.

![Screenshot from 2023-04-20 01-12-13](https://user-images.githubusercontent.com/101527680/233288565-ec4523e4-8888-4696-9288-0d146c9eda1c.png)

Maybe this is not the right issues but do you know why when I load a ".odb" file from caravel it still shows up with 0 fW, could it be the version of OpenLANE that Caravel uses?

**Comment by vijayank88** [comment]
Have you load the `.lib` file?

**Comment by Baungarten-CINVESTAV** [comment]
Yes, I followed the same steps
```
openroad
OpenROAD v2.0-7480-g8a4065b09 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
openroad> read_liberty sky130A/libs.ref/sky130_fd_sc_hd/lib/sky130_fd_sc_hd__tt_025C_1v80.lib
1
openroad> read_db user_project_wrapper.odb
openroad> gui::show
```


![Screenshot from 2023-04-20 01-25-40](https://user-images.githubusercontent.com/101527680/233291681-2402473c-0632-4595-a7c9-83abab80bc94.png)

**Comment by Baungarten-CINVESTAV** [comment]
well, just now i tried to see the power map of a sub-module, and it works. so i think the problem is when we see the power map of the core module.

**Comment by kareefardi** [comment]
@Baungarten-CINVESTAV Please open a new issue if needed. I tried viewing PPU using the above instructions it worked.
