### ISSUE TITLE
Remove `-from` and `-to`

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenLane#1753]
### Description

`-from` and `-to` were hacked together by an intern. OpenLane 1 was not designed with repeatable steps in mind, unlike its successor.

### Proposal

`-from` and `-to` should be removed from the documentation and the CLI flags should throw an error.

**Comment by mguthaus** [comment]
Can you clarify why this was dropped and not fixed if there was an issue? This seems like it should be a supported option.

**Comment by donn** [comment]
As the prompt says, OpenLane 1 was not written with `-from` and `-to` in mind. Flow steps are not designed to be re-entrant and a variable set in a later step may permanently alter the behavior of a previous step. The effort to track down and fix all of this would be effort better spent on the rewrite (which WAS written with `-from` and `-to` in mind), so we simply chose to remove it from this version.
