### ISSUE TITLE
TritonRoute creates new via2_FR/via4_FR vias

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenLane#179]
This doesn't appear to cause problems, but it's a bit strange that TritonRoute creates new via2_FR/via4_FR vias. Ahmed confirms that we should be providing it in the techLEF:

```
Warning: met2 does not have viaDef align with layer direction, generating new viaDef via2_FR...
Warning: met4 does not have viaDef align with layer direction, generating new viaDef via4_FR...
```

**Comment by antonblanchard** [comment]
I chased this down and submitted a PR to OpenROAD: https://github.com/The-OpenROAD-Project/OpenROAD/pull/595

**Comment by antonblanchard** [comment]
The fix is now upstream in OpenROAD, so we can close this once openlane does an update.

**Comment by donn** [comment]
OpenROAD was since updated,  closed.
