### ISSUE TITLE
Import timing scripts functionality to OpenLane

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenLane#1792]
### Description

Title

### Proposal

Title

**Comment by donn** [comment]
This has been already re-implemented pretty cleanly in OpenLane 2: https://github.com/efabless/openlane2/commit/f7aea83ad6bfcf5c29bd5a02bcc881c4548dd51d

The caravel script in question is *very* hacky. Importing it in OpenLane may cause more issues than it is worth. Importing the OpenLane 2 script on the other hand is less hacky but still not straightforward. We need to discuss if this is absolutely necessary.

**Comment by kareefardi** [comment]
Since https://github.com/The-OpenROAD-Project/OpenLane/pull/2135 we are not adding new features.
