### ISSUE TITLE
Warn when default `base.sdc` file is used

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenLane#1832]
### Description

OpenLane uses the included `base.sdc` file transparently if an SDC file is not set.

### Proposal

Designers should generally be using a more... tailored SDC file. Nothing inherently wrong with using `base.sdc` but at the very least, a warning should be printed.

**Comment by kareefardi** [comment]
Fixed by https://github.com/The-OpenROAD-Project/OpenLane/pull/1944
