### ISSUE TITLE
some commands are not working for me. 

### ISSUE THREAD

**Issue by YashpalRathod14** [The-OpenROAD-Project/OpenLane#1841]
### Description

![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/135158197/dfc4321f-cbe7-40b8-bf13-641688241937)

### Expected Behavior

it should show net connections. 

### Environment report

```shell
% python3 ./env.py issue-survey
/usr/bin/python3: can't open file './env.py': [Errno 2] No such file or directory
child process exited abnormally
% exit
bash-4.2$ python3 ./env.py issue-survey
python3: can't open file './env.py': [Errno 2] No such file or directory
bash-4.2$ exit
exit
vsduser@vsdsquadron:~/Desktop/work/tools/openlane_working_dir/openlane$ python3 ./env.py issue-survey
python3: can't open file './env.py': [Errno 2] No such file or directory
```

### Reproduction material

na

### Relevant log output

```shell
na
```

**Comment by vijayank88** [comment]
@YashpalRathod14 
Try with valid command. with `report_` only following commands available.
```
report_cts                report_dft_config         report_global_connect     report_physical_clusters  report_wire_length        
report_design_area        report_floating_nets      report_group              report_voltage_domains
```

**Comment by YashpalRathod14** [comment]
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/135158197/6a57c65a-df4b-45a4-a6f1-8b6ead729e5f)

Its saying command invalid, not net.

**Comment by YashpalRathod14** [comment]
look at this too : 
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/135158197/a0d32cc2-b46c-40bf-87a0-428e3f897448)

**Comment by maliberty** [comment]
Are you running openroad?  I normally gives a "openroad>" prompt

**Comment by YashpalRathod14** [comment]
i am running openlane. This is after floorplanning.

**Comment by maliberty** [comment]
Please describe the exact steps.

**Comment by maliberty** [comment]
report_net is an openroad or sta command not an openlane command.  You need to be in the application to use such.

@donn @kareefardi would you explain how to open the app from OL.  I'm not current on these things.

**Comment by vijayank88** [comment]
Inside openlane container, Just type `openroad` and enter and try report_net

**Comment by maliberty** [comment]
You'll need to load the design to get any meaningful output

**Comment by YashpalRathod14** [comment]
@maliberty could you give an example

**Comment by YashpalRathod14** [comment]
> Inside openlane container, Just type `openroad` and enter and try report_net

![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/135158197/1cb755bb-2aef-4b9d-9965-b08838e342cc)   
@vijayank88

**Comment by vijayank88** [comment]
```
%openroad
%read_db <path to>/results/cts/spm.odb
%report_nets -connections net1
```
output as follows,

```
Net net1
Driver pins
 input1/X output (sky130_fd_sc_hd__clkbuf_1) (0, 0)

Load pins
 _372_/A input (sky130_fd_sc_hd__clkbuf_4) (0, 0)
```
I shown for spm design. Similarly choose net name from your design

**Comment by YashpalRathod14** [comment]
@vijayank88 

I want to replace buffers in openlane after floorplan. Where should my read point to? 
To check .

Using Skywalker 130nm with picorv32a

**Comment by vijayank88** [comment]
`insert_buffer` option available. But not sure replace buffer.
One issue handled as per the topic.
Open a new github issue with test case and your requirement.
What is problem of existing buffers?

**Comment by YashpalRathod14** [comment]
> `insert_buffer` option available. But not sure replace buffer.
> One issue handled as per the topic.
> Open a new github issue with test case and your requirement.
> What is problem of existing buffers?

Ok, how should i do any of the task in openroad, even if i want to do report_net after floorplan, what file should i point to in openroad?

**Comment by vijayank88** [comment]
@YashpalRathod14 
here is the steps:
```
OpenLane Container (85e9dc6):/openlane$ openroad
OpenROAD ceae0ad175e8b0183c3a64af79ba18139dcda63a 
This program is licensed under the BSD-3 license. See the LICENSE file for details.
Components of this program may be licensed under more restrictive licenses which must be honored.
warning: `//.tclsh-history' is not writable.
openroad> read_db designs/picorv32a/runs/RUN_2023.06.10_07.56.41/results/floorplan/ 
openroad> read_db designs/picorv32a/runs/RUN_2023.06.10_07.56.41/results/floorplan/picorv32.odb 
openroad> report_net -connections reg_out\[1\]
```
Output:
```
Net reg_out[1]
Driver pins
 _16321_/Q output (sky130_fd_sc_hd__dfxtp_2)

Load pins
 _09430_/A0 input (sky130_fd_sc_hd__mux2_2)
```

**Comment by YashpalRathod14** [comment]
Thank you @maliberty @vijayank88
