### ISSUE TITLE
Update `magic` to 8.3.404

### ISSUE THREAD

**Issue by hpretl** [The-OpenROAD-Project/OpenLane#1851]
### Description

This update incorporates important changes to extraction, please update to this version in `OL`.

**Comment by kareefardi** [comment]
Handled here https://github.com/The-OpenROAD-Project/OpenLane/pull/1850

**Comment by hpretl** [comment]
https://github.com/The-OpenROAD-Project/OpenLane/pull/1850 updated `magic` to `9b131fa`/`8.3.403`, but I need `482d753`/`8.3.404` or later!
