### ISSUE TITLE
Global placement failed on small design

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenLane#1872]
### Description

`RePlAce divergence detected`

Tiny Tapeout Wokwi project: https://wokwi.com/projects/368241820443546625

Seems like a repeat of these issues:

* https://github.com/The-OpenROAD-Project/OpenLane/issues/1763
* https://github.com/The-OpenROAD-Project/OpenLane/issues/1559
* https://github.com/The-OpenROAD-Project/OpenLane/issues/1183

### Expected Behavior

OpenLane shouldn't fail to complete on small designs

### Environment report

```shell
Kernel: Linux v5.15.0-75-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.21 (OK)
OpenLane Git Version: 4cd0986b3ae550cdf7a6d0fba4e0657012f635d8
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

4cd0986 2023-02-13T14:32:59+02:00 Bugfixes (#1658) - Kareem Farid -  (grafted, HEAD, tag: 2023.02.14)
---
Git Remotes

origin  https://github.com/The-OpenROAD-Project/OpenLane.git (fetch)
origin  https://github.com/The-OpenROAD-Project/OpenLane.git (push)
```

### Reproduction material

[issue_reproducible.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/11848386/issue_reproducible.tar.gz)

### Relevant log output

```shell
[ERROR]: Last 10 lines:
[NesterovSolve] Iter: 230 overflow: 0.403024 HPWL: 1971297
[NesterovSolve] Iter: 240 overflow: 0.400985 HPWL: 1969262
[NesterovSolve] Iter: 250 overflow: 0.403169 HPWL: 1971452
[NesterovSolve] Iter: 260 overflow: 0.387428 HPWL: 1964099
[NesterovSolve] Iter: 270 overflow: 0.403145 HPWL: 1971453
[NesterovSolve] Iter: 280 overflow: 0.380688 HPWL: 1949681
[NesterovSolve] Iter: 290 overflow: 0.373598 HPWL: 1949994
[ERROR GPL-0307] RePlAce divergence detected. Re-run with a smaller max_phi_cof value.
Error: gpl.tcl, 69 GPL-0307
child process exited abnormally
```

**Comment by vijayank88** [comment]
Cell padding set to 0. If I use `set ::env(GPL_CELL_PADDING) {4};` it is passing. @mattvenn

**Comment by vijayank88** [comment]
@maliberty fyi

**Comment by mattvenn** [comment]
can you link to the GPL_CELL_PADDING documentation, I can't find it.

**Comment by mattvenn** [comment]
Does that setting mean we'll get less utilisation?
I would rather not waste space just because it fails on small designs.

**Comment by vijayank88** [comment]
> 

https://github.com/search?q=repo%3AThe-OpenROAD-Project%2FOpenLane%20GPL_CELL_PADDING&type=code

**Comment by vijayank88** [comment]
> Does that setting mean we'll get less utilisation? I would rather not waste space just because it fails on small designs.

Whenever there is less number of pins or < 100 std cells this issue occurs randomly. Waiting for @maliberty reviews.

**Comment by vijayank88** [comment]
> > 
> 
> https://github.com/search?q=repo%3AThe-OpenROAD-Project%2FOpenLane%20GPL_CELL_PADDING&type=code

Check this link, padding variable involved placement density calculation as well.

**Comment by vijayank88** [comment]
![Screenshot from 2023-06-23 18-37-47](https://github.com/The-OpenROAD-Project/OpenLane/assets/85787913/05f1802d-a6d1-4114-81b7-04d336a7848d)

**Comment by mattvenn** [comment]
I just checked a larger design and I can see no difference in the final GDS. I guess if there is plenty of space then I wouldn't expect the design to be bigger?

**Comment by mattvenn** [comment]
CELL_PADDING 4 fails with this: https://wokwi.com/projects/346662028519146068

I also tried setting it to 6 and 8 and it fails with all those.

**Comment by maliberty** [comment]
I ran the attached issue with the head of OR (0ea657420682722c1867b4c4ac6817de05235bde) and got no error.

**Comment by maliberty** [comment]
> > do you know what it does? like what does 4 actually mean?
> 
> 4 micron spacing around each standard cell.

Actually the cell padding is measuring in SITEs not microns.

**Comment by kareefardi** [comment]
I will update OpenROAD as soon as I can. Currently, one of the dependencies website is down.

**Comment by maliberty** [comment]
If you mean the lemon library then we have already fixed that by putting a copy in GH

**Comment by kareefardi** [comment]
@maliberty https://github.com/The-OpenROAD-Project/lemon-graph is this what are you referring to ?

**Comment by maliberty** [comment]
> @maliberty https://github.com/The-OpenROAD-Project/lemon-graph is this what you are referring to ?

Yes

**Comment by kareefardi** [comment]
OpenROAD updated an testcase is passing now.

**Comment by mattvenn** [comment]
@kareefardi could you let me know what tag openlane should I try to check this resolves my issue?
