### ISSUE TITLE
SYNTH_MAX_TRAN is unset by default which causes maximum transition violations

### ISSUE THREAD

**Issue by mo-hosni** [The-OpenROAD-Project/OpenLane#1888]
### Description

When `SYNTH_MAX_TRAN` is unset, the library’s default maximum transition time is used which is 1.5ns for sky130. When the resizer only repair the nets that has transitions larger than in 1.5ns in placement, CTS, and routing, we end up with higher transitions than 1.5ns after spef extraction in signoff. A typical value of 0.8-1.0 for SYNTH_MAX_TRAN solves most of the transition violations for sky130. 

### Proposal

Move `SYNTH_MAX_TRAN` to the pdk configuration variables and set its default value to `1.0`

**Comment by kareefardi** [comment]
Fixed in https://github.com/The-OpenROAD-Project/OpenLane/pull/1892
