### ISSUE TITLE
CLOCK_NET should not be in the Required variables section in documentation

### ISSUE THREAD

**Issue by mo-hosni** [The-OpenROAD-Project/OpenLane#1909]
### Description

I noticed that `CLOCK_NET` is a required variable in the documentation. I never used it and I don't think it is utilized anywhere in the code

### Proposal

`CLOCK_NET` to be removed from the Required variables in the documentation

**Comment by donn** [comment]
I find that interesting because the only test case we have for this variable has been created by you: https://github.com/efabless/openlane-ci-designs/tree/1a29190eeba1ead8126ec9dee0de103233de6d5f/io_placer

**Comment by mo-hosni** [comment]
I don't think I added anything to openlane CI designs. 
Anyway, if it is used in only one test case, it shouldn't be a "required variable".
