### ISSUE TITLE
documentation for starting klayout is broken

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenLane#1913]
### Description

running klayout inside docker according to instructions fails

https://openlane.readthedocs.io/en/latest/getting_started/installation/installation_ubuntu.html#optional-viewing-test-design-outputs

### Expected Behavior

should show design in klayout

### Environment report

```shell
Kernel: Linux v5.15.0-76-generic
Distribution: ubuntu 20.04
Python: v3.8.10 (OK)
Container Engine: docker v20.10.21 (OK)
OpenLane Git Version: 3bc9d02d0b34ad032921553e512fbe4bebf1d833
pip: INSTALLED
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

3bc9d02 2023-06-26T07:48:24+03:00 Use OpenROAD mirror of `lemon-graph` (#1873) - Kareem Farid -  (grafted, HEAD, tag: 2023.06.26)
---
Git Remotes

origin  https://github.com/The-OpenROAD-Project/OpenLane.git (fetch)
origin  https://github.com/The-OpenROAD-Project/OpenLane.git (push)
```

### Reproduction material

I just used the spm example

### Relevant log output

```shell
OpenLane Container (3bc9d02):/openlane$ klayout -e -nn $PDK_ROOT/sky130A/libs.tech/klayout/tech/sky130A.lyt \
>    -l $PDK_ROOT/sky130A/libs.tech/klayout/tech/sky130A.lyp \
>    ./designs/spm/runs/openlane_test/results/final/gds/spm.gds
process 2306: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
  D-Bus not built with -rdynamic so unable to print a backtrace
```

**Comment by vijayank88** [comment]
@mattvenn 
As per latest guide: https://openlane.readthedocs.io/en/latest/reference/gui.html
you have to use 
```
python3 gui.py --viewer klayout ./designs/spm/runs/openlane_test
```

**Comment by mattvenn** [comment]
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/634220/b0b7a026-c349-4273-a600-1d77b7e1ac7f)

**Comment by mattvenn** [comment]
also, can you give a command that would work for caravel?

**Comment by vijayank88** [comment]
It's working fine with Centos7, getting error has above in Ubuntu20.04

**Comment by mattvenn** [comment]
yes I'm on ubuntu 20

**Comment by mattvenn** [comment]
also just to note that most people for the shuttle will be running inside caravel_user_project. They'll run make user_project_wrapper, and then what should they do to examine the resulting gds?

**Comment by kareefardi** [comment]
> ![image](https://user-images.githubusercontent.com/634220/255159860-b0b7a026-c349-4273-a600-1d77b7e1ac7f.png)

Does the workaround here fix the problem ? https://github.com/The-OpenROAD-Project/OpenLane/issues/1772

**Comment by kareefardi** [comment]
> also just to note that most people for the shuttle will be running inside caravel_user_project. They'll run make user_project_wrapper, and then what should they do to examine the resulting gds?

OpenLane now mounts the home directory. In most cases, this guide (https://openlane.readthedocs.io/en/latest/reference/gui.html) should work.

**Comment by wilfredkisku** [comment]
I too am unable to start klayout for the test generated gds. Anyone who knows a workaround?

OS: Ubuntu 20.04 LTS

**Comment by donn** [comment]
Kindly find a new issue @wilfredkisku.

As for this issue, staled out.
