### ISSUE TITLE
Error while doing make in Openlane

### ISSUE THREAD

**Issue by aster3440** [The-OpenROAD-Project/OpenLane#1927]
I tried installing the newer version of Openlane but the pdks and most of the files don't get downloaded completely. I did follow the openlane documentation.

This is the version I was using prior a0b19fa68b79eff3e29b674106b06d20aab637f1

So I tried to commit the previous stable version which I was using by git checkout <version>

When I run make I am getting this error, How do I fix it?
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/135579098/c95048f4-a3ef-4e56-a493-c6aa46a2ed10)

**Comment by vijayank88** [comment]
@aster3440 
Please provide the steps you used to update the OpenLane.

**Comment by kareefardi** [comment]
I believe this is an old error. https://github.com/The-OpenROAD-Project/OpenLane/issues/1915. Can you post the issues that you are facing with the latest OpenLane?

**Comment by donn** [comment]
Staled out.
