### ISSUE TITLE
STA corners folders in singoff/reports have the same name "mca"

### ISSUE THREAD

**Issue by mo-hosni** [The-OpenROAD-Project/OpenLane#1943]
### Description

STA corners folders in singoff/reports have the same name `mca` and the interconnect corners are not clear in the reports.

### Proposal

The corners to be represented in the folders' names

**Comment by kareefardi** [comment]
This was handled in https://github.com/The-OpenROAD-Project/OpenLane/pull/1922. Please make sure that you are using the latest OpenLane before openning an issue

**Comment by danger2520** [comment]
Footer
 © 2023 GitHub, Inc.
Footer navigation
