### ISSUE TITLE
IO Pads generation in OpenLANE

### ISSUE THREAD

**Issue by akhilesh911** [The-OpenROAD-Project/OpenLane#1973]
Good morning all,
I am trying to create IO pads frame for my design following https://github.com/efabless/OpenLane/tree/master/scripts/topModuleGen
I have written json files required by topModuleGen.py 
It gives an error
![Screenshot from 2023-08-11 15-37-59](https://github.com/The-OpenROAD-Project/OpenLane/assets/121286671/e27b3e7e-3ff5-491f-b173-db631e72e377)
kindly let me know how to use this script.

**Comment by kareefardi** [comment]
There is a method that can be used in OpenLane interactive mode `padframe_gen_batch`. There is an example of using it here https://github.com/efabless/caravel/blob/93596a3651699b91f461954c6d7d3140c3aca0e0/openlane/chip_io/interactive.tcl#L36. There are bunch of configuration variables needed here https://github.com/efabless/caravel/blob/chip_io_config_updates/openlane/chip_io/config.tcl. Ultimately the script that's being used is https://github.com/The-OpenROAD-Project/OpenLane/blob/master/scripts/odbpy/padringer.py.

The documentation needs to be updated to reflect that.

Note:
You shouldn't be using https://github.com/The-OpenROAD-Project/OpenLane not https://github.com/efabless/OpenLane

**Comment by akhilesh911** [comment]
@kareefardi is there any way to create padframe using https://github.com/efabless/OpenLane ??
Kindly suggest.

**Comment by donn** [comment]
There is no padframe generation in OpenLane.
