### ISSUE TITLE
 Issue Running OpenLane's flow.tcl Without Docker

### ISSUE THREAD

**Issue by prajnaputhran17** [The-OpenROAD-Project/OpenLane#2014]
I am currently facing difficulties in running flow.tcl in OpenLane without using Docker. The documentation primarily focuses on Docker usage, but I need guidance on running the flow directly without Docker.

**Comment by donn** [comment]
We do not actively support running OpenLane without Docker as the complexity of the OpenLane environment makes it very likely that something will go wrong.

If you're willing to tinker, see this guide: https://openlane.readthedocs.io/en/latest/getting_started/installation/installation_local.html
