### ISSUE TITLE
Issue in PL resizer

### ISSUE THREAD

**Issue by KanishR1** [The-OpenROAD-Project/OpenLane#2042]
### Description

I have created a custom riscv processor and trying to use sky130 ram macro. While doing the normal openlane flow i am getting an error, in placement. I have attached the image here. Even after changing the MAX_TRANSITION time switch in config.json as 0.5ns, it is not getting updated. I have also attached the issue reproducible.
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/88330171/bd7dd72b-c5e8-4258-93cf-55dd6146ecf8)
[RUN_2023.11.10_19.50.23.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/13326025/RUN_2023.11.10_19.50.23.zip)

**Comment by donn** [comment]
Hello, please re-file this as a bug report as shown below:

![IMG_7825](https://github.com/The-OpenROAD-Project/OpenLane/assets/12652988/ba1ae3bd-6c8a-4de6-9825-6d1b907a6450)

**Comment by donn** [comment]
Hello- please re-file this issue as a bug report as shown below:

![Screenshot 2023-11-12 at 00 11 10](https://github.com/The-OpenROAD-Project/OpenLane/assets/12652988/9c3dc912-4c10-4a44-a297-120c518ae370)
