### ISSUE TITLE
Request to Bump Yosys (downgrade) to 0.33+6 (git sha1 41b34a193)

### ISSUE THREAD

**Issue by dlmiles** [The-OpenROAD-Project/OpenLane#2050]
### Description

Please consider revising the recent closed PR #2027  (Bump Yosys) back a few weeks to:

`Yosys 0.33+6 (git sha1 41b34a193, clang 10.0.0-4ubuntu1 -fPIC -Os)`

Due to flow issues concerning:

https://github.com/YosysHQ/yosys/issues/4039

Please feel free to close this issue once you have considered the situation and made a verdict no matter the outcome, I provide this issue to advise of on-going matter.

Thanks

### Expected Behavior

yosys-abc Assertion triggered after processing a significant number of designs (estimated worse than 3%)

Assertion causes STEP1 to fail due to abort/core-dump like crash, exit status 134

### Environment report

```shell
Linux OpenLane docker
```

### Reproduction material

See linked Yosys issue for test case and log outputs.

### Relevant log output

See linked Yosys issue for test case and log outputs.

**Comment by kareefardi** [comment]
@dlmiles Just to confirm. Downgrading fixes the crash. In addition, using the new commands in #2051 also fixes the crash ?

**Comment by dlmiles** [comment]
> @dlmiles Just to confirm. Downgrading fixes the crash. In addition, using the new commands in #2051 also fixes the crash ?

Yes that is correct

**Comment by donn** [comment]
Sorry, I don't think we'll be downgrading- for OpenLane 1 it may be doable, for OpenLane 2 we have a number of plugins that rely on this newer version of Yosys, including `eqy`, `verible`, `lighter`… And we do keep the tool versions synchronized for now.

I've reported the true issue in isolation in #2052.
