### ISSUE TITLE
 [ERROR]: There are violations in the design after Magic DRC.

### ISSUE THREAD

**Issue by tdtu1002** [The-OpenROAD-Project/OpenLane#2058]
I'm a newbie and I'm having problems with my design. when running Magic DRC. Magic says I have no DRC errors but there are 56000 violations, what are the violations here? how to fix it ? thanks

![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/76868791/ca9933f3-c1e6-4eec-824c-d49153b34fb1)
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/76868791/9e84f6de-77c1-4ea2-8b3b-1fe9ba5c3b1d)
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/76868791/e5d4290e-e572-43a6-a1a2-31c1320b53a0)

**Comment by d-m-bailey** [comment]
Are you using openram? openram has different rules - normal drc will flag a lot of errors. You might try temporarily replacing the sram mag file with maglef.

**Comment by tdtu1002** [comment]
i follow openlane flow, and it generate this above image :(((

**Comment by tdtu1002** [comment]
@dm-bailey how can i replace mag to maglef, SRAM i have gds, lef and lib file.

**Comment by d-m-bailey** [comment]
For running DRC in magic, I think you load the maglef views of the sram first and then load your design and then run DRC.
maglef views may still have drc errors, but I think they're just false wide metal spacing and maybe invalid overlaps.
@RTimothyEdwards ?

**Comment by RTimothyEdwards** [comment]
There are multiple ways of doing it, but it depends on whether your run DRC on a .mag file or a .gds file.  If it's a .mag file then you can either (1) load the maglef view of the SRAM or load the LEF view of the SRAM first, then load the design, which is what Mitch suggested above, or (2) load the design, then use `cellname filepath` to change the location of the SRAM to the maglef directory before expanding;  and if it's being run from GDS, then (3) load the maglef view of the SRAM first and set `gds noduplicates true` before reading the GDS.  Even after expansion, you can still replace the SRAM with `cellname filepath` followed by `flush`.

**Comment by kareefardi** [comment]
@tdtu1002 can you upload a GDS or a DEF file ?

**Comment by tdtu1002** [comment]
> @tdtu1002 can you upload a GDS or a DEF file ?

thanks so much everyone, i solve it by add an options to my config.tcl "MAGIC_DRC_USE_GDS" : 0,
