### ISSUE TITLE
add macro.cfg to the read the docs manual

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenLane#2070]
### Description

There are ways to rotate and flip macros that not many people know about.

https://github.com/The-OpenROAD-Project/OpenLane/blob/66e938bcb87d7f5b9a0487c018e6a0083b289d5d/scripts/odbpy/manual_macro_place.py#L21

### Proposal

Add a section to the docs about macro.cfg options.

**Comment by kareefardi** [comment]
Fixed by #2071
