### ISSUE TITLE
the script being called is missing

### ISSUE THREAD

**Issue by nikitaminiaev** [The-OpenROAD-Project/OpenLane#2091]
### Description

when running commands interactively:
run_magic
scrot_layout

An error occurs:
bash: /openlane/scripts/klayout/scrotLayout.sh: No such file or directory

### Expected Behavior

generating masks in png

### Environment report

```shell
[STEP 45]
[INFO]: Creating a screenshot using KLayout (log: designs/spm/runs/RUN_2024.02.13_19.59.01/logs/cts/45-screenshot.log)...
[ERROR]: during executing: "bash /openlane/scripts/klayout/scrotLayout.sh /home/nekit/.volare/sky130A/libs.tech/klayout/tech/sky130A.lyt /openlane/designs/spm/runs/RUN_2024.02.13_19.59.01/results/signoff/spm.gds |& tee /dev/null /openlane/designs/spm/runs/RUN_2024.02.13_19.59.01/logs/cts/45-screenshot.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
bash: /openlane/scripts/klayout/scrotLayout.sh: No such file or directory
child process exited abnormally
```

### Reproduction material

[STEP 45]
[INFO]: Creating a screenshot using KLayout (log: designs/spm/runs/RUN_2024.02.13_19.59.01/logs/cts/45-screenshot.log)...
[ERROR]: during executing: "bash /openlane/scripts/klayout/scrotLayout.sh /home/nekit/.volare/sky130A/libs.tech/klayout/tech/sky130A.lyt /openlane/designs/spm/runs/RUN_2024.02.13_19.59.01/results/signoff/spm.gds |& tee /dev/null /openlane/designs/spm/runs/RUN_2024.02.13_19.59.01/logs/cts/45-screenshot.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
bash: /openlane/scripts/klayout/scrotLayout.sh: No such file or directory
child process exited abnormally

### Relevant log output

```shell
[STEP 45]
[INFO]: Creating a screenshot using KLayout (log: designs/spm/runs/RUN_2024.02.13_19.59.01/logs/cts/45-screenshot.log)...
[ERROR]: during executing: "bash /openlane/scripts/klayout/scrotLayout.sh /home/nekit/.volare/sky130A/libs.tech/klayout/tech/sky130A.lyt /openlane/designs/spm/runs/RUN_2024.02.13_19.59.01/results/signoff/spm.gds |& tee /dev/null /openlane/designs/spm/runs/RUN_2024.02.13_19.59.01/logs/cts/45-screenshot.log"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
bash: /openlane/scripts/klayout/scrotLayout.sh: No such file or directory
child process exited abnormally
```

**Comment by donn** [comment]
The issue template is invalid, as the two sections "Environment report" and "Reproduction Material" are just copies of the relevant log output.
