### ISSUE TITLE
Max fanout violation

### ISSUE THREAD

**Issue by MuhammadWamiq003** [The-OpenROAD-Project/OpenLane#2097]
### Description

I have encountered a warning indicating the presence of maximum fanout violations within the design at the Typical corner. I am seeking assistance in resolving this issue. Does anyone have insights or suggestions on how to address this matter effectively?

the warning look like:
[WARNING]: There are max fanout violations in the design at the Typical corner.

### Expected Behavior

Solve fanout violation

### Environment report

```shell
open_pdks cd1748bb197f9b7af62a54507de6624e30363943
WARNING: issue-survey appears to be running inside the OpenLane
container.

This makes it difficult to rule out issues with your
environment.

Unless instructed specifically to do so, please run this command
outside the OpenLane container.
---

Kernel: Linux v6.5.0-21-generic
Distribution: centos 7
Python: v3.6.8 (OK)
OpenLane Git Version: 9dbd8b5ea2bd891bed4dcc97df5c7439083f0368
python-venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

9dbd8b5e 2024-01-11T15:26:56+02:00 Fix `-synth_explore` crash (#2085) - Kareem Farid -  (HEAD -> master, tag: 2024.01.12, origin/master, origin/HEAD)
a005df1f 2024-01-08T10:51:06+02:00 Updated link to newer version of spanish docs (#2082) - Laboratorio de Investigación en Microelectrónica y Arquitectura de Computadoras, EIE -- UCR -  (tag: 2024.01.09)
8bea8c51 2023-12-26T13:17:21+02:00 Update `OpenROAD` (#2062) - Kareem Farid -  (tag: 2023.12.27)
---
Git Remotes

origin	https://github.com/The-OpenROAD-Project/OpenLane (fetch)
origin	https://github.com/The-OpenROAD-Project/OpenLane (push)
```

### Reproduction material

[config.json](https://github.com/The-OpenROAD-Project/OpenLane/files/14443101/config.json)
[dff_8x72.txt](https://github.com/The-OpenROAD-Project/OpenLane/files/14443115/dff_8x72.txt)

[dff.txt](https://github.com/The-OpenROAD-Project/OpenLane/files/14443113/dff.txt)

### Relevant log output

```shell
[WARNING]: There are max fanout violations in the design at the Typical corner. Please refer to 'designs/ram_8x72/runs/first_run/reports/signoff/33-sta-rcx_nom/multi_corner_sta.checks.rpt'.
```

**Comment by donn** [comment]
Should be safe to ignore as long as there are no max capacitance violations.
