### ISSUE TITLE
Clock Network Delay is 0.0 in timing reports after CTS

### ISSUE THREAD

**Issue by Jaswanth-Pappula** [The-OpenROAD-Project/OpenLane#2120]
Clock Network Delay is showing as 0.00 in timing reports of Max and Min after CTS step even though CTS routing is completed.

You can find it in the  image attached below.

<img width="523" alt="Picture1" src="https://github.com/The-OpenROAD-Project/OpenLane/assets/95895531/5e800b4f-f93c-4acc-b7aa-ba6482ef21b4">

Can someone help me in resolving this issue.

**Comment by maliberty** [comment]
Most likely you need `set_propagated_clock [all_clocks]`

**Comment by Jaswanth-Pappula** [comment]
> Most likely you need `set_propagated_clock [all_clocks]`

set_propagated_clock [get_clocks {Clk}] is generated in the cts.sdc file inside results section of the design but nor replicated in the min, max or nominal timing reports and it is just showing ideal.

so, is there any other way to do it instead of using set_propagated_clock [all_clocks].
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/95895531/24fd75dc-fa1d-4770-a2e0-4608ea9f460d)

**Comment by Jaswanth-Pappula** [comment]
> Most likely you need `set_propagated_clock [all_clocks]`

set_propagated_clock [get_clocks {Clk}] is generated in the cts.sdc file inside results section of the design but nor replicated in the min, max or nominal timing reports and it is just showing ideal.

so, is there any other way to do it instead of using set_propagated_clock [all_clocks].
<img width="953" alt="image" src="https://github.com/The-OpenROAD-Project/OpenLane/assets/95895531/a0f6c489-4845-4bbf-86e0-c2fe10d3f6e6">

**Comment by donn** [comment]
Should be fixed by now.

**Comment by Jaswanth-Pappula** [comment]
> Should be fixed by now.

Yes, the problem is fixed. Thanks for the reply
