### ISSUE TITLE
Issue with installation of OpenLane, while running make cmd "Error: Command '['/home/HP/OpenLane/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1."

### ISSUE THREAD

**Issue by WrathofBhuvan11** [The-OpenROAD-Project/OpenLane#2129]
![image](https://github.com/The-OpenROAD-Project/OpenLane/assets/36232037/4dec7b27-e257-4061-803e-2097aacb7873)

Here one can see when I run the make command for installation, it throws an error with Python. Please help me with resolving the issue.
**_Error: Command '['/home/HP/OpenLane/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1."_**

**Comment by donn** [comment]
Are you following the installation guide in https://openlane.readthedocs.io/en/latest/getting_started/installation/index.html ?

**Comment by WrathofBhuvan11** [comment]
Yes, I'm using Cygwin-X Terminal which is integrated with Windows python (Anaconda installed). I'm running this in Cygwin-X

**Comment by WrathofBhuvan11** [comment]
Please someone reply

**Comment by donn** [comment]
We're leaving it open so someone in the community could maybe reply but we don't have much experience with neither Cygwin nor Conda…

**Comment by WrathofBhuvan11** [comment]
> We're leaving it open so someone in the community could maybe reply but we don't have much experience with neither Cygwin nor Conda… 

Actually I'm currently trying in Ubuntu env windows. Cygwin is just that path but I'm using Ubuntu Linux WSL to run these.

The last reply screenshot is from Ubuntu WSL

**Comment by kareefardi** [comment]
@WrathofBhuvan11 did you update and install required packages in WSL?
```
sudo apt-get update
sudo apt-get upgrade
sudo apt install -y build-essential python3 python3-venv make git
```

**Comment by donn** [comment]
I'm afraid we cannot support a conda installation, period. Too many variables.
