### ISSUE TITLE
Where is "Estimated Congestion(RUDY)" report 

### ISSUE THREAD

**Issue by Pxx-X** [The-OpenROAD-Project/OpenLane#2163]
### Description

I use openlane and use the command "python gui.py --viewer openroad -s **placement** designs/chacha/runs/RUN_XXX" to open openroad gui. He can display correctly of **"Estimated congestion (RUDY)"**, but where is its data. Is there a report file? I can't find it

![image](https://github.com/user-attachments/assets/d13afbd8-2897-48bc-bc0c-ed4c08e506ad)

**Comment by maliberty** [comment]
Heatmaps can be dumped with https://openroad.readthedocs.io/en/latest/main/src/gui/README.html#dump-heatmap-to-file
