### ISSUE TITLE
invalid command name set::env(PDK)

### ISSUE THREAD

**Issue by srknkrdnz** [The-OpenROAD-Project/OpenLane#2165]
Hi,
when running synthesis,ı have this problem. ı could not solve. Please help me.
![Ekran Alıntısı](https://github.com/user-attachments/assets/aa5883c4-f846-4e57-9695-7571187197f5)

**Comment by donn** [comment]
Please follow the issue template.

That said, this is an easy one. In your config file, you need to leave a space between `set` and `::env(PDK)`.

**Comment by srknkrdnz** [comment]
thanks. problem has been solved .
