### ISSUE TITLE
Warning PNR_SDC_FILE

### ISSUE THREAD

**Issue by srknkrdnz** [The-OpenROAD-Project/OpenLane#2166]
How could ı fix this error. Please Help me.
![screen_shot_1](https://github.com/user-attachments/assets/f4661b97-473e-428a-9a93-4784393c1159)
![screen_shot_2](https://github.com/user-attachments/assets/8fb76ec7-5cca-4fe8-8345-23599e8926ae)

**Comment by srknkrdnz** [comment]
How could  ı do it ? Please help me

**Comment by donn** [comment]
https://github.com/The-OpenROAD-Project/OpenLane/issues/new?assignees=&labels=&projects=&template=bug_report.yml
