### ISSUE TITLE
Warning PDC_FILE

### ISSUE THREAD

**Issue by srknkrdnz** [The-OpenROAD-Project/OpenLane#2167]
### Description

This is my config.tcl file which is not running properly 
![screen_shot_5](https://github.com/user-attachments/assets/811ec4cf-59ed-4dd1-b252-60eb5cefd5b5)
![screen_shot_6](https://github.com/user-attachments/assets/1847e0ef-031f-41cf-a311-fec0385bc4f4)

### Expected Behavior

I got this report How can ı fix 
![screen_shot_1](https://github.com/user-attachments/assets/64980824-0a53-4723-8508-5b6cc519cf46)
![screen_shot_2](https://github.com/user-attachments/assets/7519bd1b-7425-4abf-850e-196945ed6950)

### Environment report

```shell
x
```

### Reproduction material

z

### Relevant log output

```shell
z
```

**Comment by srknkrdnz** [comment]
![screen_shoot_3](https://github.com/user-attachments/assets/a1b24974-8a30-49a5-830c-82206c1c29cf)

**Comment by vijayan-krishna** [comment]
@srknkrdnz 
Problem not related to warning... Real error in logs/synthesis/linter.log
Check the log and fix it.

**Comment by srknkrdnz** [comment]
Thanks for recommendation. I found error.
