### ISSUE TITLE
Issue Regarding Placement error in OPENLANE RTL to GDS flow

### ISSUE THREAD

**Issue by DarshanGuled** [The-OpenROAD-Project/OpenLane#231]
![16130429352022204265884663927299](https://user-images.githubusercontent.com/53936406/107631085-76d6b000-6c8a-11eb-821d-0295f6fa14d6.jpg)
Hello,
This is Darshan here.
We are working on OPENLANE FLOW. We have installed and tested example of SPM which was already present in the design folder.
Now we are trying to add our own design like counter and D - FF design, but we are facing the following errors in the in Detailed Placement.
Please Anyone help is to debug the error``

**Comment by agorararmard** [comment]
Hi @DarshanGuled: Have you checked [this](https://github.com/efabless/openlane/wiki#what-to-do-if-the-flow-failed-in-any-of-the-steps-from-floorplan-up-to-routing)? 
In a nutshell, lower your `FP_CORE_UTIL` and `PL_TARGET_DENSITY`; defaults are 50 and 0.55, respectively.
You can also try setting `CELL_PAD` to 4. However, this may not be needed, depending on the OpenLane/open_pdks version you're using.

[This](https://github.com/efabless/openlane/wiki#how-to-get-to-0-drc-violations) is also relevant.

**Comment by DarshanGuled** [comment]
> Hi @DarshanGuled: Have you checked [this](https://github.com/efabless/openlane/wiki#what-to-do-if-the-flow-failed-in-any-of-the-steps-from-floorplan-up-to-routing)?
> In a nutshell, lower your `FP_CORE_UTIL` and `PL_TARGET_DENSITY`; defaults are 50 and 0.55, respectively.
> You can also try setting `CELL_PAD` to 4. However, this may not be needed, depending on the OpenLane/open_pdks version you're using.
> 
> [This](https://github.com/efabless/openlane/wiki#how-to-get-to-0-drc-violations) is also relevant.

Thank you for the reply @agorararmard I have set the default FP_CORE_UTIL and PL_TARGET_DENSITY Its still giving same error. When i try to change the value and try again and again. It passed the placement error but its showing  
Instance cannot fit in to the core area 
What can i do for this error??!

**Comment by agorararmard** [comment]
@DarshanGuled: You should keep reducing the values until they work. An exploration script would be useful in that case. [This](https://github.com/efabless/openlane/wiki#how-to-get-to-0-drc-violations) is still relevant.

**Comment by DarshanGuled** [comment]
> @DarshanGuled: You should keep reducing the values until they work. An exploration script would be useful in that case. [This](https://github.com/efabless/openlane/wiki#how-to-get-to-0-drc-violations) is still relevant.

Thank you soo much @agorararmard This really helps me alot. One last thing if we are facing the OVERLAPPING IS FAILED in Openlane placement process then what can we do to eliminate that error?.

Thank you so much for the information. The links are really helpful to understand the constraints.

**Comment by agorararmard** [comment]
@DarshanGuled: Also, the general solution to that is to reduce `FP_CORE_UTIL` and `PL_TARGET_DENSITY`. It's advisable to have PL_TARGET_DENSITY=(FP_CORE_UTIL+5)/100. (i.e the default values are 50, 0.55).

Also, make sure your `CELL_PAD` is set to 4.

**Comment by agorararmard** [comment]
@DarshanGuled: Did you manage to resolve the issue?

**Comment by agorararmard** [comment]
@DarshanGuled: I will assume this issue is resolved and close it. Please reopen if the issue still stands.

**Comment by DarshanGuled** [comment]
Hello sir,
I have attached 2 snaps 
One consisting of error which we are facing.
And another one is .sdc file of our design.
Sir till Technology mapping its working but after that we are getting the above error.
Please help us to resolve the error

**Comment by agorararmard** [comment]
@DarshanGuled: I'm unable to view your second snap. Please try re-uploading it.

As for the error above, this is still the solution:

> @DarshanGuled: Also, the general solution to that is to reduce `FP_CORE_UTIL` and `PL_TARGET_DENSITY`. It's advisable to have PL_TARGET_DENSITY=(FP_CORE_UTIL+5)/100. (i.e the default values are 50, 0.55).
> 
> Also, make sure your `CELL_PAD` is set to 4.

If you could provide me with the design and your configurations I can look further into it.

On that note, which openlane version are you using?

**Comment by harshithsn** [comment]
> Hi @DarshanGuled: Have you checked [this](https://github.com/efabless/openlane/wiki#what-to-do-if-the-flow-failed-in-any-of-the-steps-from-floorplan-up-to-routing)?
> In a nutshell, lower your `FP_CORE_UTIL` and `PL_TARGET_DENSITY`; defaults are 50 and 0.55, respectively.
> You can also try setting `CELL_PAD` to 4. However, this may not be needed, depending on the OpenLane/open_pdks version you're using.
> 
> [This](https://github.com/efabless/openlane/wiki#how-to-get-to-0-drc-violations) is also relevant.

How to change FP_CORE_UTIL and PL_TARGET_DENSITY & CELL_PAD value?
And in which file i need to change /edit it?

**Comment by harshithsn** [comment]
> Hi @DarshanGuled: Have you checked [this](https://github.com/efabless/openlane/wiki#what-to-do-if-the-flow-failed-in-any-of-the-steps-from-floorplan-up-to-routing)?
> In a nutshell, lower your `FP_CORE_UTIL` and `PL_TARGET_DENSITY`; defaults are 50 and 0.55, respectively.
> You can also try setting `CELL_PAD` to 4. However, this may not be needed, depending on the OpenLane/open_pdks version you're using.
> 
> [This](https://github.com/efabless/openlane/wiki#how-to-get-to-0-drc-violations) is also relevant.

How to change FP_CORE_UTIL and PL_TARGET_DENSITY & CELL_PAD value?
And in which file do i need to change /edit it? @DarshanGuled @agorararmard 
please help me!

**Comment by DarshanGuled** [comment]
Hello @harshithsn .
In Openlane folder there is one folder called configuration in that go to Placement and you can see all configuration file select placement.tcl file and change the values

**Comment by vanishka-tanwar** [comment]
Hello OL Team,


As, I am working in openlane , and is trying to make the Ip layout design of my selected circuit but when I am executing it so, at the time of execution of my design file its showing this same error to me at the time of placement 


![Screenshot from 2021-08-15 15-36-33](https://user-images.githubusercontent.com/72103059/129475841-0ec808c5-9c72-4ace-bfac-1841580bd1fd.png)

![Screenshot from 2021-08-15 15-36-54](https://user-images.githubusercontent.com/72103059/129475843-c5a35871-f0d7-4267-9f68-92cf15f31909.png)


as I have also tried it by inserting this command 
set ::env(PL_TARGET_DENSITY) "0.68"
into config.tcl file of my design but still the same problem perist

**Comment by harshithsn** [comment]
@vanishka-tanwar 
Try to change FP_CORE_UTIL value.
which design are you executing ? Design Name?

**Comment by vanishka-tanwar** [comment]
@harshithsn 
How much value should I give to Fp_CORE_UTIL value
My design is 4 bit magintude comparator and I saved it by this name dvsd_cmp.
