### ISSUE TITLE
sha3.v wrong implementation

### ISSUE THREAD

**Issue by guidobertoni** [The-OpenROAD-Project/OpenLane#249]
I was reading the code of sha3.v and noticed that the actual implementation in it is SHA2-512, you can read the end of file comment reporting sha512_core.v or read the implementation to see that is not containing the Keccak algorithm in it.
line 595 contains the implementation of the Ch function of SHA 512 as described in
https://en.wikipedia.org/wiki/SHA-2

this function is not part of the SHA3 algorithm

**Comment by donn** [comment]
Sorry, we don't really care. We make no promises about these designs doing what's on the tin: just that OpenLane can harden them. We're not opposed to a PR to fix them but we are not going to dedicate time to this ourselves.
