### ISSUE TITLE
Could you tell the exact procedure to implement the io pads in openlane

### ISSUE THREAD

**Issue by shafnaskm** [The-OpenROAD-Project/OpenLane#281]
Could you tell the exact procedure to implement the io pads in openlane

**Comment by Manarabdelaty** [comment]
You can check the documentation at https://github.com/efabless/openlane/blob/master/docs/source/chip_integration.md#hardening-the-full-chip . It explains how to generate the padframe and references [caravel](https://github.com/efabless/caravel) chip IO as an example.

**Comment by donn** [comment]
@shafnaskm Has your issue been resolved?

**Comment by shafnaskm** [comment]
Yes thanks
