### ISSUE TITLE
INSTALL_SRAM does not work when set to enabled

### ISSUE THREAD

**Issue by armleo** [The-OpenROAD-Project/OpenLane#294]
**Describe the bug**
Unable to install openlane with INSTALL_SRAM. It's disabled by default and "enabled" does not do anything.

**To Reproduce**
INSTALL_SRAM=enabled make openlane pdk test

**Expected behavior**
SRAM Macro installation is supposed to work.

**Desktop in VM**
 - OS: Manjaro XFCE
 - Openlane Version [v0.12]

**Assumption**
When configured the enabled parameter should be replaced with a path to SRAM cell installation OR be left out to automatically pulled from Github. I might be doing something completely wrong but I don't understand how to force OpenLANE to use SRAM Macro cells.

**Comment by d-m-bailey** [comment]
@armleo The way to install the default SRAM is to `export INSTALL_SRAM=yes`.

However, this would only work on native builds until https://github.com/The-OpenROAD-Project/OpenLane/pull/570

Should work now for docker builds too.

You can close the issue if you think it's fixed.
