### ISSUE TITLE
Not able to install PDK on Mac M1 

### ISSUE THREAD

**Issue by guris12** [The-OpenROAD-Project/OpenLane#320]
**Describe the bug**
chmod a+x /Users/gursimransodhi/Documents/OpenLane/openlane/pdk/skywater-pdk/env/downloads/Miniconda3-latest-MacOSX-arm64.sh
/Users/gursimransodhi/Documents/OpenLane/openlane/pdk/skywater-pdk/env/downloads/Miniconda3-latest-MacOSX-arm64.sh -p /Users/gursimransodhi/Documents/OpenLane/openlane/pdk/skywater-pdk/env/conda -b -f
touch "/Users/gursimransodhi/Documents/OpenLane/openlane/pdk/skywater-pdk/env/conda/bin/python"
touch: /Users/gursimransodhi/Documents/OpenLane/openlane/pdk/skywater-pdk/env/conda/bin/python: No such file or directory
make[1]: *** [/Users/gursimransodhi/Documents/OpenLane/openlane/pdk/skywater-pdk/env/conda/bin/python] Error 1
make: *** [skywater-library] Error 2

**To Reproduce**
git clone https://github.com/efabless/openlane.git
    cd openlane/
    make openlane
   
    make pdk
--> Getting Error 

**Expected behavior**
Should have installed PDK 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac M1 chip 
 - Openlane Version Latest
 - open_pdks Version: Latest
 - skywater-pdk Version: Latest
<img width="1127" alt="Screenshot 2021-05-04 at 1 21 44 PM" src="https://user-images.githubusercontent.com/83633890/116974382-ae7a5480-acdb-11eb-8bb3-15d9c4a32edf.png">

**Additional context**

**Comment by donn** [comment]
Hi Guris, we're going to need a full log so we can help you here. The last 5 lines are not sufficient.

**Comment by guris12** [comment]
hello donn, is there any log file which is generated ? I am not able to find it , could you please point me  to the right place

**Comment by donn** [comment]
Just copy & paste more lines from the terminal.

**Comment by donn** [comment]
Or alternatively, run:

  make pdk 2>&1 > ./make_pdk.log

Then find a file called make_pdk.log.

**Comment by guris12** [comment]
[4may_error.log](https://github.com/efabless/openlane/files/6420154/4may_error.log)

please find the error.lo attached

**Comment by donn** [comment]
…Might be me, but I don't see any errors in this log. Have you added the `2>&1`?

**Comment by guris12** [comment]
Dumping a new file with above command

**Comment by guris12** [comment]
please find the new log file 
[make_pdk.log](https://github.com/efabless/openlane/files/6421180/make_pdk.log)
