### ISSUE TITLE
Showing "Cannot find any macros in this design" on placement stage

### ISSUE THREAD

**Issue by shafnaskm** [The-OpenROAD-Project/OpenLane#330]
Commands in config.tcl related to macro have shown below

set ::env(VERILOG_FILES_BLACKBOX) [glob $::env(DESIGN_DIR)/src/pte.v]

set ::env(EXTRA_LEFS) [glob $::env(DESIGN_DIR)/runs/final_130/results/magic/pte.lef]
set ::env(EXTRA_GDS_FILES) [glob $::env(DESIGN_DIR)/runs/final_130/results/magic/pte.gds]

**Comment by sjkelly** [comment]
Do you have a full link to the source code? I noticed in the past yosys will mangle the names on parametric modules which can trigger this issue. The other possibility, something is not blackboxed for the synthesis step.

**Comment by shafnaskm** [comment]
i forgot to add black box for macros
