### ISSUE TITLE
PDK_ROOT (and other paths passed) must be absolute

### ISSUE THREAD

**Issue by thesourcerer8** [The-OpenROAD-Project/OpenLane#348]
**Describe the bug**
When PDK_ROOT contains "../" to refer to the PDK, openlane fails.
Workaround: Make sure that PDK_ROOT does not contain ../ for example in the following way: export PDK_ROOT=$(readlink -f $(pwd)/../pdk )
Due to good the workaround, this bug is not urgent.

**To Reproduce**
export PDK_ROOT=../pdk
make user_proj_example

The resulting error:

cd openlane && make user_proj_example
make[1]: Verzeichnis „/media/philipp/Daten/skywater/caravel_stdcelllib_stdcells_project/openlane“ wird betreten
###############################################
[INFO]: 
	___   ____   ___  ____   _       ____  ____     ___
	/   \ |    \ /  _]|    \ | |     /    ||    \   /  _]
	|     ||  o  )  [_ |  _  || |    |  o  ||  _  | /  [_
	|  O  ||   _/    _]|  |  || |___ |     ||  |  ||    _]
	|     ||  | |   [_ |  |  ||     ||  _  ||  |  ||   [_
	\___/ |__| |_____||__|__||_____||__|__||__|__||_____|

[INFO]: Version: mpw-one-a
[INFO]: Running non-interactively
[INFO]: Using design configuration at /project/openlane/user_proj_example/config.tcl
[INFO]: Sourcing Configurations from /project/openlane/user_proj_example/config.tcl
[INFO]: PDKs root directory: /media/philipp/Daten/skywater/caravel_stdcelllib_stdcells_project/../pdk
[INFO]: PDK: sky130A
[INFO]: Setting PDKPATH to /media/philipp/Daten/skywater/caravel_stdcelllib_stdcells_project/../pdk/sky130A
[INFO]: Standard Cell Library: sky130_fd_sc_hd
couldn't read file "/media/philipp/Daten/skywater/caravel_stdcelllib_stdcells_project/../pdk/sky130A/libs.tech/openlane/config.tcl": no such file or directory
    while executing
"source $pdk_config"
    (procedure "prep" line 126)
    invoked from within
"prep {*}$args"
    (procedure "run_non_interactive_mode" line 9)
    invoked from within
"run_non_interactive_mode {*}$argv"
    invoked from within
"if { [info exists flags_map(-interactive)] || [info exists flags_map(-it)] } {
	puts_info "Running interactively"
	if { [info exists arg_values(-file)..."
    (file "/openLANE_flow/flow.tcl" line 162)
make[1]: *** [Makefile:43: user_proj_example] Fehler 1

**Expected behavior**
It should work normally

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Openlane Version v0.15
 - open_pdks Version: [commit hash]
 - skywater-pdk Version: [commit hash]

**Comment by donn** [comment]
This has to do primarily with how Docker works- all paths need to be absolute. Sadly, this is not an easily fixable issue.

Please `readlink -f` or `realpath` all paths used.
