### ISSUE TITLE
Error in routing stage

### ISSUE THREAD

**Issue by Mansi-VLSI-3** [The-OpenROAD-Project/OpenLane#426]
**Describe the bug**
The following error is obtained while running the routing. It says the **design congestion is too high**. 

**To Reproduce**
Necessary design files are uploaded here https://github.com/vsdip/rvmyth_avsddac_interface/tree/main/rvmyth_avsddac

1. In the docker type: ./flow.tcl -design rvmyth_avsddac -interactive
2. package require openlane 0.9
3. prep -design rvmyth_avsddac -overwrite
4. set lefs 	 [glob $::env(DESIGN_DIR)/src/lef/*.lef]
5. add_lefs -src $lefs
6. run_synthesis
7. init_floorplan
8. place_io
9. global_placement_or
10. detailed_placement
11. tap_decap_or
12. detailed_placement
13. gen_pdn
14. run_routing

**Expected Behaviour**
Routing should run normally.

**Screenshots**
The snapshots of the error obtained: 

![image](https://user-images.githubusercontent.com/79994584/120915577-fff27680-c6c1-11eb-946f-b9dca7820bc1.png)

![image](https://user-images.githubusercontent.com/79994584/120915660-a3dc2200-c6c2-11eb-83f7-1d87ef1d309d.png)

![image](https://user-images.githubusercontent.com/79994584/120915662-ac345d00-c6c2-11eb-84e7-ea0e23942f15.png)

**Desktop (please complete the following information):**
 - OS: ubuntu

**Comment by maliberty** [comment]
That message comes from the global router not the detailed router.  It's not clear that this is a bug and not just an over congested design that needs more routing area.

**Comment by Mansi-VLSI-3** [comment]
> That message comes from the global router not the detailed router. It's not clear that this is a bug and not just an over congested design that needs more routing area.

Hi, yes you are right the error came from the global router itself. Also tried it by reducing the initial utilization to 1% and 5% but eventually the **same error: design congestion is too high**  is obtained.

**For 1% utilization:** 
Following error is obtained while running the detailed_placement :
![image](https://user-images.githubusercontent.com/79994584/120934241-2a245280-c71b-11eb-92bf-3df0f6c30f05.png)

and the following error at the run_routing ( while running global routing ) :
![image](https://user-images.githubusercontent.com/79994584/120934299-6bb4fd80-c71b-11eb-99e5-fcc3daeddbab.png)


**For 5% utilization:**
Following error is obtained in the run_routing stage ( while running global routing) :
![image](https://user-images.githubusercontent.com/79994584/120934343-9dc65f80-c71b-11eb-8b20-19a7bf550b02.png)

**Comment by maliberty** [comment]
Standalone opendp was integrated into openroad over a year ago is not being developed anymore.  OpenLane should move forward.

**Comment by donn** [comment]
Will do

**Comment by donn** [comment]
You can probably try now.

**Comment by donn** [comment]
Yes, please always use the latest OpenLane.

**Comment by vijayank88** [comment]
@Mansi-VLSI-3 possible share your config.tcl and source RTL. its easy to debug.

**Comment by Mansi-VLSI-3** [comment]
> Yes, please always use the latest OpenLane.

Hi  , am already using the latest one that is docker rc6 so is there an update even after that because the issue still persists?

**Comment by donn** [comment]
The latest tag is 2021.09.05_03.29.19.

rc6 is from December 2020.

**Comment by vijayank88** [comment]
@18341A04A6 
Goto https://github.com/The-OpenROAD-Project/OpenLane/issues, start new issue and follow the guidelines to file an issue.
With screenshot it will not get resolved.
