### ISSUE TITLE
Failing LEC on design which went through complete flow when LEC was disabled.

### ISSUE THREAD

**Issue by madgo1991** [The-OpenROAD-Project/OpenLane#467]
Case I : LEC Disabled : The design ran full flow and GDSII was generated.
Case II : LEC Enabled : The LEC failed on the same designed.

Is there any logfile which is generated where more details on this error can be found ? Right now the error description is quite limited.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Openlane Version v0.9
 - open_pdks Version: [commit hash]  1.0.141
 - skywater-pdk Version: [commit hash]  v0.0.0-308-gdb2e067

**Comment by donn** [comment]
Sorry for the extremely late reply- a lot has changed and OpenLane has not been v0.9 for a year now. I would kindly ask you to re-make the issue if it persists.
