### ISSUE TITLE
make openlane always pulls efabless/openlane:current irregardless of the openlane version

### ISSUE THREAD

**Issue by Manarabdelaty** [The-OpenROAD-Project/OpenLane#490]
This is creating an issue where an older version of openlane is used and `make openlane` is pulling a docker image that doesn't correspond to that version.

**Comment by donn** [comment]
This is documented: 
<img width="1003" alt="Screen Shot 2021-07-08 at 21 17 12" src="https://user-images.githubusercontent.com/12652988/124978319-e7171100-e031-11eb-8967-debeb8f4aa35.png">

I'm not necessarily opposed to making it resolve the version of OpenLane being used, but it'd have to be a heuristic of some kind given that we'd have to extract it from a git repository and some people might elect to download OpenLane as a tarball.
