### ISSUE TITLE
make merge in docker_build copies the pdks directory unnecessarily

### ISSUE THREAD

**Issue by d-m-bailey** [The-OpenROAD-Project/OpenLane#495]
**Describe the bug**
Running `make merge` in `docker_build` copies the `../../pdks` directory unnecessarily

**To Reproduce**
1. `mkdir -p pdks/ignore_me`
2. `cd docker_build`
2. `make merge`
3. `vi tar/openLANE_flow.tar.gz`
  Search for `pdks/ignore_me`

**Expected behavior**
Should ignore the pdks directory

**Screenshots**

**Desktop (please complete the following information):**
 - OS: centOS
 - Openlane Version v0.20

**Additional context**
The following change fixes the problem. Remove the trailing '/'.
```
diff --git a/docker_build/Makefile b/docker_build/Makefile
index 96ed0a3..0866a52 100644
--- a/docker_build/Makefile
+++ b/docker_build/Makefile
@@ -41,7 +41,7 @@ tar/openroad_tools.tar.gz: $(TOOL_EXPORT_TARGETS_REAL)
        cd tar && tar -czf openroad_tools.tar.gz ../build
 
 tar/openLANE_flow.tar.gz: FORCE
-       cd tar && tar --exclude='../../.git' --exclude='../../docker_build' --exclude="../../designs" --exclude="../../pdks/" --exclude="../../logs/*" -czf openLANE_flow.tar.gz 
+       cd tar && tar --exclude='../../.git' --exclude='../../docker_build' --exclude="../../designs" --exclude="../../pdks" --exclude="../../logs/*" -czf openLANE_flow.tar.gz .
 
 FORCE:
```

**Comment by donn** [comment]
Thanks for the fix, I'll merge it within the next few days.
