### ISSUE TITLE
set_propagate_clock [all_clocks] not working

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#501]
**Describe the bug**
in OpenLane flow scripts/openroad/or_resizer_timing.tcl  below lines available. 

```
# CTS and detailed placement move instances, so update parastic estimates.
estimate_parasitics -placement
set_propagated_clock [all_clocks]
repair_timing
```

The respective log is 15-fastroute.log don't have propagated delay, still running with ideal delay. Log shown below:

```
Startpoint: _898_ (rising edge-triggered flip-flop clocked by clk)
Endpoint: _884_ (rising edge-triggered flip-flop clocked by clk)
Path Group: clk
Path Type: max

Fanout     Cap    Slew   Delay    Time   Description
-----------------------------------------------------------------------------
                  0.00    0.00    0.00   clock clk (rise edge)
                          0.00    0.00   **clock network delay (ideal)**
                  0.00    0.00    0.00 ^ _898_/CLK (sky130_fd_sc_hd__dfxtp_1)
                  0.06    0.84    0.84 v _898_/Q (sky130_fd_sc_hd__dfxtp_1)
     2    0.00                           uart_rx_inst.prescale_reg[1] (net)
                  0.06    0.00    0.84 v _485_/A (sky130_fd_sc_hd__or2_1)
                  0.18    0.59    1.43 v _485_/X (sky130_fd_sc_hd__or2_1)
     4    0.01                           _328_ (net)
                  0.18    0.00    1.43 v _486_/C (sky130_fd_sc_hd__or3_1)
                  0.22    0.87    2.31 v _486_/X (sky130_fd_sc_hd__or3_1)
     4    0.01                           _329_ (net)
                  0.22    0.00    2.31 v _487_/D (sky130_fd_sc_hd__or4_1)
                  0.26    1.12    3.43 v _487_/X (sky130_fd_sc_hd__or4_1)
     3    0.01                           _330_ (net)
```
**To Reproduce**

Take any available design in OpenLane flow and check design/<name>/runs/logs/routing/fastroute.log

**Expected behavior**

Once we add set_propagated_clock [all_clocks] this clock dealy should be used in all next stages. If we included in cts, routing stage should be used same propagated clocks. Example log shown below:
```
Startpoint: _897_ (rising edge-triggered flip-flop clocked by clk)
Endpoint: _874_ (rising edge-triggered flip-flop clocked by clk)
Path Group: clk
Path Type: max

Fanout     Cap    Slew   Delay    Time   Description
-----------------------------------------------------------------------------
                          0.00    0.00   clock clk (rise edge)
                          1.26    1.26   **clock network delay (propagated)**
                  0.67    0.00    1.26 ^ _897_/CLK (sky130_fd_sc_hd__dfxtp_1)
                  0.10    0.87    2.13 v _897_/Q (sky130_fd_sc_hd__dfxtp_1)
     3    0.01                           uart_rx_inst.prescale_reg[0] (net)
                  0.10    0.00    2.13 v _485_/B (sky130_fd_sc_hd__or2_1)
                  0.15    0.53    2.66 v _485_/X (sky130_fd_sc_hd__or2_1)
     4    0.01                           _328_ (net)
                  0.15    0.00    2.66 v _486_/C (sky130_fd_sc_hd__or3_1)
                  0.20    0.84    3.50 v _486_/X (sky130_fd_sc_hd__or3_1)
     4    0.01                           _329_ (net)
```
As per standard EDA flow clock propagation delay should be initialized before start of CTS.This clock tree added .def and .lef should be used in routing stage and our tns and wns should be optimized to meet our constraints.

**Comment by maliberty** [comment]
This report is mistaken, or_resizer_timing.tcl does not generate 15-fastroute.log, it generates 12-resizer-timing.log (which has no timing report). 

or_groute.tcl does generate 15-fastroute.log but it has no call to set_propagated_clock.  The tool results are correct and this is a flow issue so return to @donn

**Comment by vijayank88** [comment]
@maliberty After CTS, or_resizer_timing.tcl running and respective log is 12_resizer_timing.log. I think detailed timing checks not added at this stage. In routing stage again timing checks happening at 15-fastroute.log. In this fastroute.log i see data path checks only ideal clock not a propagated clock.
My question is as we initialized propagation dealy in run_resizer_timing, in routing stage why its been reset to ideal clock? 
Maybe instead of reading base.sdc, run_resizer_timing stage generated ***.sdc if we use this issue will be resolved (Its just my view)

**Comment by maliberty** [comment]
The tool is exited and restarted between steps so there is no carry over.

**Comment by donn** [comment]
@maliberty Thanks for the tip, Matt- I'll look into it

**Comment by dralabeing** [comment]
@donn Please point to the source tcl code to write sdc files at each of the required stages for correct carryover into global route. We are trying to fix it and test locally first. Thanks
