### ISSUE TITLE
.rpt files are empty

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#506]
As i see scripts/openroad/or_cts.tcl shows dumping all reports, even other stages too. But in reports directory all xxx.rpt files are empty/ 0Bytes.
**Refer attachement: or_cts_tcl.png and report_files.png first image**

**Enhancement need:**
Expecting respective xxx.rpt files to be dumped in each stage of flow.

![or_cts_tcl](https://user-images.githubusercontent.com/85787913/127116848-96af92f5-2729-454a-834f-849f8c74351b.png)
![report_files](https://user-images.githubusercontent.com/85787913/127116862-4ade8044-c6c6-4558-b5aa-11d546835b5e.png)

**Comment by donn** [comment]
A fix for this was merged. (#515 for posterity.)
