### ISSUE TITLE
Updating Yosys in OpenLane

### ISSUE THREAD

**Issue by shariethernet** [The-OpenROAD-Project/OpenLane#529]
Hi, How to make openlane use a new version of yosys (0.9+4245). Currently it uses a older version where yosys lacks support for `tri` keyword.
How to edit the dockerfile in  `openlane/docker_build/docker/yosys/Dockerfile` to make openlane use this yosys version
TIA!

**Comment by d-m-bailey** [comment]
@shariethernet You should be able to do this from your openlane installation.
1. edit `IMAGE_NAME` in `Makefile` (optional: default is to use the current image)
2. `cd docker_build`
2. edit `IMAGE_NAME` in `Makefile` (optional: default is to use the current image).
3. edit `YOSYS_COMMIT` in `docker/yosys/Dockerfile` to the version you want
4. `make build-yosys`
5. `make merge`

That's it.

**Comment by shariethernet** [comment]
I edited `YOSYS_COMMIT` and then ran `make build-yosys`. It was successsful. I am getting this error after running `make merge`

**Comment by d-m-bailey** [comment]
@shariethernet not sure, but maybe try `sudo make merge`? Looks like you don't have write access to a file system.

**Comment by shariethernet** [comment]
Thanks @d-m-bailey. I just did a `git reset --hard` to undo the changes and repeated the same as `su` worked!
