### ISSUE TITLE
make pdk fails with :: ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#544]
**Describe the bug**
When we install openlane with "git clone https://github.com/The-OpenROAD-Project/OpenLane.git" and following step #make pdk command fail with below error:
Traceback (most recent call last):
  File "./dependencies/tool.py", line 15, in <module>
    import yaml <---
ModuleNotFoundError: No module named 'yaml'
git clone  /home/indir/OpenLane/pdks/skywater-pdk
fatal: repository '/home/indir/OpenLane/pdks/skywater-pdk' does not exist
make: *** [Makefile:87: /home/indir/OpenLane/pdks/skywater-pdk] Error 128

**Desktop (please complete the following information):**
Important Note::This issue arise only when using below OS.
 - OS:Ubuntu 20.04 and Centos 7 and above

Workaround is install pyymal with below command and then try #make pdk 
#sudo pip3 install pyyaml
#make pdk

I have tested at end above solution working fine. 
@donn  Please verify is this valid and approve it, then I will Close this GitHub issue.
Thanks..

**Comment by donn** [comment]
This isn't a workaround. This is in the Readme.

<img width="698" alt="Required, amongst other things: click, pyyaml" src="https://user-images.githubusercontent.com/12652988/129719135-ddb4628f-31de-41e7-9231-41b25708272a.png">
