### ISSUE TITLE
 Klayout GDSII PNG

### ISSUE THREAD

**Issue by Badboy1307** [The-OpenROAD-Project/OpenLane#548]
### Prompt
Bringing back Klayout generating GDSII image in PNG format will help a lot of students  and working professionals who are still new to using this flow. As I find Klayout only creates GDS files but not including PNG format. Pls look on this feature.

**Comment by donn** [comment]
All you'd have to do is add `set ::env(TAKE_LAYOUT_SCROT) 1` to your design's config.tcl.

This feature has been known to crash, so that's why we've disabled it by default.

**Comment by Badboy1307** [comment]
Oh ok thanks for replying will try and let ya know how it's working.

**Comment by Badboy1307** [comment]
Is it normal while installing  pdk to run out of range? Or is there a fix for that?

**Comment by donn** [comment]
No, not really. You’d have to share the full error (in a new issue) so we can help with that.

**Comment by Badboy1307** [comment]
Sure will do so as soon as possible
