### ISSUE TITLE
Error during  diode_insertion can't find opendb python module 

### ISSUE THREAD

**Issue by 20Mhz** [The-OpenROAD-Project/OpenLane#585]
Hi, 
This is needed by: ./scripts/write_powered_def.py
Not sure where is this is suppose to come from, didn't see it on OpenROAD repo. please advise.
Thanks!
Ronald

**Comment by 20Mhz** [comment]
I think is here now: src/odb/src/swig/python

It seems it has change its name as well....

**Comment by vijayank88** [comment]
@20Mhz also mention which version of openlane you are using?  Install latest openlane version and try it. still error repeats share source file along with steps to reproduce the issue

**Comment by donn** [comment]
We can’t help you if you just nuke the issue template.

**Comment by 20Mhz** [comment]
OpenLane f7fd774a762629bc56d31a94ff03138fbc2e176c
OpenROAD 527cd5d8e82308baa1a46265c1338e6c1757858f

It seems the swig module has changed name, but it also broken backwards compatibility.
Related to: https://github.com/The-OpenROAD-Project/OpenROAD/issues/1028

**Comment by 20Mhz** [comment]
https://gist.github.com/20Mhz/be34125a6747a559b4da7f073043ee9f

**Comment by donn** [comment]
Ronald, that's not a workaround, that's a fix! If you can open a PR, I'd be happy to approve it.

**Comment by donn** [comment]
Incorporated as part of #609, thanks
