### ISSUE TITLE
[WARNING]: The version of open_pdks installed not matching with openlane flow scripts

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#611]
### Description
Whenever I make PR for latest update or install in new path I'm getting this warning message. Last time #553 .. now mismatch for open_pdks. I have installed full-pdk.

### Environment
* Operating System Information: `uname -a` 20.04.1-Ubuntu
* Docker Version: `docker --version`
    * If you're using an alternative container service, please also include this information.
* OpenLane Tag in use: `python3 ./dependencies/get_tag.py` in the main OpenLane directory. 2021.09.09_03.00.48

### Reproduction Material
make test will throw this warning message

### Expected behavior
Script should match pdk version

### Logs
```
[root@48989487a315 openLANE_flow]# ./flow.tcl -design spm -tag 1stTest
[INFO]: 
	 ___   ____   ___  ____   _       ____  ____     ___
	/   \ |    \ /  _]|    \ | |     /    ||    \   /  _]
	|   | |  o  )  [_ |  _  || |    |  o  ||  _  | /  [_
	| O | |   _/    _]|  |  || |___ |     ||  |  ||    _]
	|   | |  | |   [_ |  |  ||     ||  _  ||  |  ||   [_
	\___/ |__| |_____||__|__||_____||__|__||__|__||_____|


[INFO]: Version: 2021.09.09_03.00.48-3-gecc62b4
[WARNING]: The version of open_pdks installed in the environment does not match the one required by the OpenLane flow scripts (installed: 81d28fd0423ca6bbf3f3bf00b7d407958cf8f0f3, expected: 14beb9c5386c21be5ad0d644986c839619d5f983)
child process exited abnormally
[WARNING]: OpenLane may not function properly.
[INFO]: Running non-interactively

```

**Comment by donn** [comment]
This isn't a bug. This is a normal warning to show that the version of OpenLane you're using requires a different PDK version. You can `make pdk` to ensure you're using the PDK required by a specific OpenLane version.
