### ISSUE TITLE
How to change the core_area and die_area of the project.

### ISSUE THREAD

**Issue by peijunh** [The-OpenROAD-Project/OpenLane#617]
Hello, I am running my design with OpenLane flow. I specify the core area and die area in my config.tcl as below
>set ::env(DESIGN_IS_CORE) "1"
>set ::env(DIE_AREA) "0 0 7000 7000"
>set ::env(CORE_AREA) "50 50 6950 6950"

However, the resulting .def file in floorplan keep giving me this: DIEAREA ( 0 0 ) ( 655195 665915 ) ;
When I open the design/mydesign/runs/18-09_01-38/config.tcl, I find that there are two sets of AREA. One set is at the top of this config.tcl, which is exactly what I write in my config.tcl, also shown above. The other set is around 300 lines lower, which give me this:
>set ::env(CORE_AREA) "5.52 10.88 649.52 652.8
>set ::env(DIE_AREA) "0.0 0.0 655.195 665.915

And I have the error in the figure, which I guess is because my area is too small. Is there anyway to specify my own die area and core area?
![5f2c22bb2cadbaa3ce91650aff07db3](https://user-images.githubusercontent.com/79550986/133890540-ceeb0c75-e7d8-4d18-a5ef-309947e5ce00.png)

**Comment by vijayank88** [comment]
@peijunh Use absolute keyword followed by your die size.  use below format. Refer floorplan readme for more options.

set ::env(FP_SIZING) absolute
set ::env(DESIGN_IS_CORE) "1"
set ::env(DIE_AREA) "0 0 7000 7000"
set ::env(CORE_AREA) "50 50 6950 6950"

**Comment by donn** [comment]
As vijayank88 wrote.
