### ISSUE TITLE
Add `_PATH` postfix to all configuration variables that store the path of a file or a directory

### ISSUE THREAD

**Issue by ahmednofal** [The-OpenROAD-Project/OpenLane#628]
### Prompt
Currently there are configuration environment variables that store the paths to certain directories or files but do not have the `_PATH` postfix in the name of the variable which they should. 
1. From a consistency stand point there should not be some variables that point to paths that have `_PATH` postfix and others that do not (which is the case right now)
2. From a usability stand point the configuration file serves as an interfacing mechanism between openlane and the user, the user in this case might just be another tool. If there are any processing that needs to be done on the paths (relative vs absolute paths, or other types of resolution) before passing them to openlane, there are not any way to do them automatically (figuring out which variables represent a path and which do not) without manually specifying each variable that represents a path
How it would work in code:
`if 'PATH' in configuration_var_name: # this is for sure a path that I might or might not need to resolve`
An example of an issue: `SOME_VAR_NAME: "somevalue"` This `"somevalue"` might just be a directory that is relative to where the configuration file resides and it might be something that has a string as its value. This means that a simple check if the path exists or not in the filesystem does not work (because the same name could be a directory and it could also be a string value, a good example would be a directory named after the design_name, it could be referencing the relative path to the directory and it could be referencing the design_name) 
### Proposal
Add `_PATH` postfix to all configuration variables that store the path of a file or a directory
### Alternatives
No alternative comes to mind

**Comment by donn** [comment]
Not vibing with a breaking change for the sake of consistency, sorry. I vote no.
