### ISSUE TITLE
request for source codes of striVe SoC Family

### ISSUE THREAD

**Issue by magicwave18** [The-OpenROAD-Project/OpenLane#632]
I didn't find the source codes of striVe  SoC Family when I was reading the paper "Building OpenLANE: A 130nm OpenROAD-based
Tapeout-Proven Flow". Could you please send a copy to my email: chenyu98@hust.edu.cn or 1277614190@qq.com. Thank you.

**Comment by vijayank88** [comment]
@magicwave18  I think you have to contact respective publisher for source codes or tag right person to reach this to get quick response
