### ISSUE TITLE
[ERROR DRT-0073] No ap for u_dac/inp1:   Need more details on this error indication

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenLane#638]
I am using efabless openlane for sky130nm project,  During flow i see openroad tool exiting with below error

[INFO DRT-0077]   Complete 1000 pins.
[ERROR DRT-0073] No ap for u_dac/inp1.
terminate called after throwing an instance of 'std::runtime_error'
  what():  DRT-0073

Need more details on ERROR

**Comment by maliberty** [comment]
Can you provide a packaged test case or at least a screen shot of the relevant pin?

**Comment by dineshannayya** [comment]
Attached the pin screen shot and GDS/LEF of the block .. PIN: inp1 Location: 3.980 252.940 Micron

![OpenRoadIssue1](https://user-images.githubusercontent.com/8286294/136646006-7b26a3da-f4e1-4223-a6b6-0af4c926fb9e.png)
[8BITDAC.gds.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7315042/8BITDAC.gds.gz)
[8BITDAC.lef.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7315043/8BITDAC.lef.gz)

**Comment by dineshannayya** [comment]
Attached the test case
Run command: ./run_cmd

ERROR Message:
<pre>[INFO DRT-0077]   complete 1000 pins
[ERROR DRT-0073] no ap for u_dac/inp1
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  DRT-0073
</pre>

Let me know any additional information needed

[exp10.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7316978/exp10.tar.gz)

**Comment by maliberty** [comment]
![image](https://user-images.githubusercontent.com/761514/136732734-c238e3de-fc41-411d-a7ed-149ff8314675.png)
