### ISSUE TITLE
Openroad PDNgen halo issue, where it works in Older version OpenRoad

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenLane#640]
### Description
I have using the Efabless openlane for detail routing, which uses openroad version: 
<pre>1 eca774ae4c0f2b383f859887d9e5ddd608b6d3b3
</pre>

I see details route fails with MetSpc DRC violation around the SRAM memory generated by OpenPDK on Sky130 technology

Attached the setup at exp1.tar.gz, command: run_cmd

[exp1.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7319821/exp1.tar.gz)

Attached one the MetSpec violating Pin (sram_addr1[0] screen shoot

![MetSpec_Vio_sram_addr1_0](https://user-images.githubusercontent.com/8286294/136740794-1d2cbc2f-023f-481f-86e8-04147c613f74.png)

### Working Case
Same Database works Openroad version : OpenROAD 0.9.0 1415572a73 (This Openlane RC7 Version)
[exp2.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7319824/exp2.tar.gz)

working setup is available at exp2.tar.gz  command: run_cmd

Attached the working sram_add1[0] screeshoot

![Working_sram_addr1_0](https://user-images.githubusercontent.com/8286294/136740848-6826ed6b-d1e3-49f1-a4be-ad62d9c1ebde.png)

Let me know any additional information needed

**Comment by maliberty** [comment]
@dineshannayya in the upper picture there is a large added red rectangle that isn't in the lower picture.  What is that shape part of?  I'm wondering if this is a pdngen change.

**Comment by dineshannayya** [comment]
@maliberty yes this looks to PDN issue, I see issue specific to SRAM Pads which are in MET4 and Vertical Power Rail is overlapping as in image below
 
![PDN-SRAM-Issue1](https://user-images.githubusercontent.com/8286294/137103883-3d5d088e-85f6-482c-9a15-4aac9e9238dc.png)

I see PDN tool is not taking account of FP_HORIZONTAL_HALO & FP_VERTICAL_HALO value

What update needed in PDN scripts when  SRAM integrated ?
Attached the sample setup.

[exp1.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7336749/exp1.tar.gz)

**Comment by donn** [comment]
God... @maliberty Any suggestions here?

**Comment by Colin-Holehouse** [comment]
You can try out if setting ::halo is working by calling `pdngen::get_default_halo`
This should always return a 4 valued expressing the halo in db units

```
openroad> set ::halo [list $::env(FP_HORIZONTAL_HALO) $::env(FP_VERTICAL_HALO)]
5 7
openroad> pdngen::get_default_halo
10000 14000 10000 14000
```

**Comment by dineshannayya** [comment]
Thanks Colin, Issue resolved after defining ::halo before specif_grid_macro

![pdn_halo_fix](https://user-images.githubusercontent.com/8286294/137184703-ceac3595-8d05-4d2f-ba90-fd10f84291d1.png)

Issue need to fixed in sky130  PDK file : sky130A/libs.tech/openlane/common_pdn.tcl
Is this possible to share this issue with them ?

**Comment by maliberty** [comment]
So this issue needs to be resolved by OL so back to @donn

**Comment by mattvenn** [comment]
this also seems to result in the PDN being routed such that 1 in every 4 vertical straps (VSSD1) goes right up to the edge of the macro.
