### ISSUE TITLE
Enable the OR GUI

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenLane#642]
Please enable the OR GUI in your docker build of OR.  You will need to have Qt installed in your container.  See https://github.com/The-OpenROAD-Project/OpenROAD/blob/master/etc/DependencyInstaller.sh for the OR setup.

**Comment by dralabeing** [comment]
@donn Could you please provide an ETA on this? GUI is becoming increasingly important based on several user requests
