### ISSUE TITLE
Unable to rebuild the openroad application using make build-openroad_app command

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenLane#647]
I am trying to rebuild the latest openroad tools using command : make build-openroad_app

Under folder: make build-openroad_app

Command Return with below error

<pre>make export-openroad_app
make[1]: Entering directory &apos;/home/dinesha/workarea/efabless/MPW-3/openlane/docker_build&apos;
rm -f tar/openroad_app.tar.gz &amp;&amp; echo &quot;Deleted existing tar/openroad_app.tar.gz&quot;
Deleted existing tar/openroad_app.tar.gz
mkdir -p tar
id=$( docker create openroad_app) ; \
   docker cp $id:/build.tar.gz tar/openroad_app.tar.gz ; \
   docker rm -v $id
Unable to find image &apos;openroad_app:latest&apos; locally
Error response from daemon: pull access denied for openroad_app, repository does not exist or may require &apos;docker login&apos;: denied: requested access to the resource is denied
must specify at least one container source
&quot;docker rm&quot; requires at least 1 argument.
See &apos;docker rm --help&apos;.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
make[1]: *** [Makefile:29: export-openroad_app] Error 1
make[1]: Leaving directory &apos;/home/dinesha/workarea/efabless/MPW-3/openlane/docker_build&apos;
make: *** [Makefile:20: build-openroad_app] Error 2
</pre>

**Comment by vijayank88** [comment]
@dineshannayya Have you used 
#git checkout master
#git pull 
followed by your make command.
Or else list detailed steps what you used.

**Comment by dineshannayya** [comment]
@vijayank88 
My project is targeted to Efabless MPW-3 Shuttle and using openlane tag: 2021.09.19_20.25.16
Here is the git status
<pre><font color="#C4A000">commit 6905a12d2efe18502c37c3207b5ee84cdf720d9c (</font><font color="#3465A4"><b>grafted</b></font><font color="#C4A000">, </font><font color="#06989A"><b>HEAD</b></font><font color="#C4A000">, </font><font color="#C4A000"><b>tag: 2021.09.19_20.25.16</b></font><font color="#C4A000">)</font>
Author: Donn &lt;me@donn.website&gt;
Date:   Sun Sep 19 11:47:53 2021 +0200

     Revert #607, #601 (#619)
    
    - #607 - Lack of legalization was causing routing issues with OpenROAD.
    
    - #601 - There is a cryptic &quot;maze ripup wrong&quot; message that makes aes_cipher fail: see The-OpenROAD-Project/OpenROAD#1110
    
    - CU of aes_cipher reduced to 40 (50 was causing issues with TR)
    
    - Fixed or_issue
</pre>

Here are the command details
1.  git pull
2.  cd docker_build
3.  I have updated the GIT COMMIT ID  openroad_app/Dockerfile 
#ARG OPENROAD_APP_COMMIT=4d4d7205fd0292dbf3fae55fad9109b3f0bd5786
ARG OPENROAD_APP_COMMIT=f23af6f4b7126ea34d8e5d141fa43033ff9d7a3a  (Latest Openroad Apps)
4. make build-openroad_app

<pre>mkdir -p logs/docker
docker build --rm --build-arg OPENROAD_APP_REPO=https://github.com/The-OpenROAD-Project/OpenROAD --build-arg OPENROAD_APP_COMMIT=fb8ae93b6c7a5eb0e6fac83360a8a48d76c41885 -t openroad_app docker/openroad_app | tee logs/docker/openroad_app.build.txt
Sending build context to Docker daemon  23.55kB
Step 1/30 : FROM centos:centos7 AS base-dependencies
 ---&gt; eeb6ee3f44bd
Step 2/30 : RUN yum groupinstall -y &quot;Development Tools&quot;
 ---&gt; Using cache
 ---&gt; 6d791c11b99f
Step 3/30 : RUN yum install -y https://repo.ius.io/ius-release-el7.rpm     &amp;&amp; yum install -y centos-release-scl     &amp;&amp; yum install -y wget devtoolset-8     devtoolset-8-libatomic-devel tcl-devel tcl tk libstdc++ tk-devel pcre-devel     python36u python36u-libs python36u-devel python36u-pip &amp;&amp;     yum clean -y all &amp;&amp;     rm -rf /var/lib/apt/lists/*
 ---&gt; Using cache
 ---&gt; a34360cc6cf9
Step 4/30 : ENV CC=/opt/rh/devtoolset-8/root/usr/bin/gcc     CPP=/opt/rh/devtoolset-8/root/usr/bin/cpp     CXX=/opt/rh/devtoolset-8/root/usr/bin/g++     PATH=/opt/rh/devtoolset-8/root/usr/bin:$PATH     LD_LIBRARY_PATH=/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:/opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/usr/lib/dyninst:/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:$LD_LIBRARY_PATH
 ---&gt; Using cache
 ---&gt; b1dbc4d6fd24
Step 5/30 : RUN wget https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.sh &amp;&amp;     chmod +x cmake-3.14.0-Linux-x86_64.sh  &amp;&amp;     ./cmake-3.14.0-Linux-x86_64.sh --skip-license --prefix=/usr/local &amp;&amp; rm -rf cmake-3.14.0-Linux-x86_64.sh     &amp;&amp; yum clean -y all
 ---&gt; Using cache
 ---&gt; ac2d0c97a410
Step 6/30 : RUN yum -y remove bison
 ---&gt; Using cache
 ---&gt; 5164add8ffe2
Step 7/30 : RUN wget https://ftp.gnu.org/gnu/bison/bison-3.0.5.tar.gz &amp;&amp;     tar -xvzf bison-3.0.5.tar.gz
 ---&gt; Running in ae6038f0472c
<font color="#EF2929">--2021-10-16 13:04:28--  https://ftp.gnu.org/gnu/bison/bison-3.0.5.tar.gz</font>
<font color="#EF2929">Resolving ftp.gnu.org (ftp.gnu.org)... 209.51.188.20, 2001:470:142:3::b</font>
<font color="#EF2929">Connecting to ftp.gnu.org (ftp.gnu.org)|209.51.188.20|:443... connected.</font>
<font color="#EF2929">ERROR: cannot verify ftp.gnu.org&apos;s certificate, issued by &apos;/C=US/O=Let\&apos;s Encrypt/CN=R3&apos;:</font>
<font color="#EF2929">  Issued certificate has expired.</font>
<font color="#EF2929">To connect to ftp.gnu.org insecurely, use `--no-check-certificate&apos;.</font>
The command &apos;/bin/sh -c wget https://ftp.gnu.org/gnu/bison/bison-3.0.5.tar.gz &amp;&amp;     tar -xvzf bison-3.0.5.tar.gz&apos; returned a non-zero code: 5
make export-openroad_app
make[1]: Entering directory &apos;/home/dinesha/workarea/efabless/MPW-3/openlane/docker_build&apos;
rm -f tar/openroad_app.tar.gz &amp;&amp; echo &quot;Deleted existing tar/openroad_app.tar.gz&quot;
Deleted existing tar/openroad_app.tar.gz
mkdir -p tar
id=$( docker create openroad_app) ; \
   docker cp $id:/build.tar.gz tar/openroad_app.tar.gz ; \
   docker rm -v $id
Unable to find image &apos;openroad_app:latest&apos; locally
Error response from daemon: pull access denied for openroad_app, repository does not exist or may require &apos;docker login&apos;: denied: requested access to the resource is denied
must specify at least one container source
&quot;docker rm&quot; requires at least 1 argument.
See &apos;docker rm --help&apos;.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
make[1]: *** [Makefile:29: export-openroad_app] Error 1
make[1]: Leaving directory &apos;/home/dinesha/workarea/efabless/MPW-3/openlane/docker_build&apos;
make: *** [Makefile:20: build-openroad_app] Error 2
</pre>

**Comment by donn** [comment]
Sorry... if you wanna build OpenROAD you're gonna have to move beyond the MPW3 version. A critical fix was merged lo, two days ago.
