### ISSUE TITLE
Diode Insertion Problem at TritonRoute

### ISSUE THREAD

**Issue by BYCakar** [The-OpenROAD-Project/OpenLane#655]
### Description
To reduce antenna violations, I tried the configuration DIODE_INSERTION_STRATEGY = 5. When I did that, I got an error message in detailed routing phase. The log file is full of these warning messages, which can be seen in attachments.
```
...
[WARNING DRT-0246] ANTENNA__17693__A/DIODE from _00054_ has nullptr as prefAP.
[WARNING DRT-0246] ANTENNA__17694__A2/DIODE from _00054_ has nullptr as prefAP.
[WARNING DRT-0246] ANTENNA__17695__A/DIODE from _00054_ has nullptr as prefAP.
[WARNING DRT-0246] ANTENNA__17703__A/DIODE from _00054_ has nullptr as prefAP.
[WARNING DRT-0246] ANTENNA__17711__A/DIODE from _00054_ has nullptr as prefAP.
[WARNING DRT-0246] ANTENNA__23141__S/DIODE from _00116_ has nullptr as prefAP.
...
```
Flow successfully finishes when DIODE_INSERTION_STRATEGY = 3. In that case there is no diode usage. It seems like the problem is with diode usage, but I have no clue what is wrong. 

### Environment Survey
I've run or_issue.py and the output file is below
```
[RUN_2021.10.25_21.12.54_or_droute_packaged.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7415856/RUN_2021.10.25_21.12.54_or_droute_packaged.tar.gz)
```

### Reproduction Material
There is a tarball file with a source folder and configuration file in. This can be reproduced in openlane bash.
```
[sources.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7386389/sources.tar.gz)
```
### Logs
```
[24-tritonRoute.log](https://github.com/The-OpenROAD-Project/OpenLane/files/7415864/24-tritonRoute.log)
```

**Comment by donn** [comment]
What version of OpenLane are you using?

**Comment by dralabeing** [comment]
@vijayank88 - Can you run this test case and check to see if the antenna violations persist with the latest OL Tag?

**Comment by vijayank88** [comment]
@dralabeing yes with latest OL tag 2021.10.25_20.35.00-11-g18a17f4 got same issue as user reported.

@BYCakar  with default DIODE_INSERTION technique passed flow successfully, why you're trying DIODE_INSERTION_STRATEGY = 5 again. Can your share number of antenna violation left with DIODE_INSERTION_STRATEGY = 3 and flow_summary.log to understand your issue?

**Comment by BYCakar** [comment]
I've updated my design but same problem still exists. Thus I uploaded my latest run's antenna report and flow summary files.
[antenna_and_summary.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/7521230/antenna_and_summary.zip)

**Comment by maliberty** [comment]
This still needs a packaged test case in order to make any progress.  Logs & reports are not enough.
