### ISSUE TITLE
Expired certificate from klayout.org

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/OpenLane#660]
### Description

```bash
$ cd docker_build
Step 5/9 : RUN wget https://www.klayout.org/downloads/CentOS_7/klayout-0.27.3-0.x86_64.rpm
 ---> Running in 056b38d72b4e
--2021-10-21 13:08:53--  https://www.klayout.org/downloads/CentOS_7/klayout-0.27.3-0.x86_64.rpm
Resolving www.klayout.org (www.klayout.org)... 178.77.102.107
Connecting to www.klayout.org (www.klayout.org)|178.77.102.107|:443... connected.
ERROR: cannot verify www.klayout.org's certificate, issued by '/C=US/O=Let\'s Encrypt/CN=R3':
  Issued certificate has expired.
To connect to www.klayout.org insecurely, use `--no-check-certificate'.
```

**Comment by dralabeing** [comment]
@vijayank88 Could you please check if this is a Centos 7 specific issue or something related only to a docker build ?

**Comment by donn** [comment]
I've already addressed this issue in an upcoming branch: @vvbandeira already figured out a fix that we use for building OpenROAD, namely, `yum update ca-certificates`.

Bypassing SSL is setting off an unbelievable amount of alarms for me. We'll wait for a proper fix to be merged.

**Comment by oharboe** [comment]
> I've already addressed this issue in an upcoming branch: @vvbandeira already figured out a fix that we use for building OpenROAD, namely, `yum update ca-certificates`.
> 
> Bypassing SSL is setting off an unbelievable amount of alarms for me. We'll wait for a proper fix to be merged.

Very good!

Yes: don't merge my hack, it was labled as "DO NOT MERGE".... It was just to test something locally and verify that I had identified all the problems.
