### ISSUE TITLE
Max fanout default considered ?

### ISSUE THREAD

**Issue by cloudxcc** [The-OpenROAD-Project/OpenLane#670]
I'm wondering if the max fanout default = 5 setting is considered at all. For example, the default regression output of the zipdiv design shows fanouts > 10 (for all synthesis results, including zipdiv.synthesis_preroute.v):

Report: _0081_: 32
Report: pre_sign: 68
Report: r_busy: 65

It can be verified by running the design and by making a grep of the above signals on the synthesis results netlists.

This is eventually the reason for the slow design performance. I see similar problems on other designs. 

I'm using a 3 wwek old version and the default regression run commands. If you really need more information (logs) let me know. For fanout analysis I'm using a private (not open-sourced yet) EDA tool. A log wouldn't provide more information than the above.

**Comment by vijayank88** [comment]
@cloudxcc as per zipdiv config.tcl fanout values are:
set ::env(CLOCK_BUFFER_FANOUT) "16"
set ::env(SYNTH_MAX_FANOUT) "6"
I checked fastroute.log and fanout values within this value only.
So closing this issue. If you've issue re-open this again with valid log file.

**Comment by cloudxcc** [comment]
I'm not a flow expert, but any netlist in the reports\synthesis results directory on any medium or larger size project I have been toying with so far has fanout violations, somtimes even > 100 depending on the RTL.

The zipdiv testcase is an example when you do a grep on the signal pre_sign.

So either the netlists are not the one implemented or the fanout.log file is wrong. But as I said, I'm not a flow expert.
