### ISSUE TITLE
High Clk Skew number observed with Latest OpenRoad CTS Tool

### ISSUE THREAD

**Issue by dineshannayya** [The-OpenROAD-Project/OpenLane#671]
Openroad version:  v2.0-1424-gf864efbae

I am trying to harden small design with Openlane flow with MPW-3 Tag.  I see  Clk Skew number in order of 2.33ns.
If if use the same design in Openlane:RC7 tag the skew number are with-in 0.12ns or 130ps

1) Here is the Clock Skew Number with Openroad version:  v2.0-1424-gf864efbae
<pre>Clock bist_clk
Latency      CRPR       Skew
_1822_/CLK ^            3.67
_1704_/CLK ^           1.34     
                   0.00       2.33

wns -3.88
tns -131.54
</pre>

Attached the Example Setup:
[mpw-3.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/7388335/mpw-3.tar.gz)

2) Here is result based on RC7 Tag  &  Clock Skew are in the order of 0.12ns or 130ps
<pre> Clock bist_clk
Latency      CRPR       Skew
_1771_/CLK ^      0.56
_1794_/CLK ^      0.44      
               0.00       0.12

wns 0.00  
tns 0.00
</pre>

Attached the Example Setup
[mpw-2.tar.gz](https://github.com/The-OpenROAD-Project/OpenROAD/files/7388337/mpw-2.tar.gz)

I have used or_cts.tcl file from openlane for my analysis.

One observation: In MPW-3 CTS uses both slow and fast corner library where as MPW-2 CTS uses only one corner Typical corner library ..

Not clear is CTS reporting worst violation between two corner (Slow and Fast corner) ?

**Comment by dineshannayya** [comment]
@donn I have cross-checked the setup in https://github.com/efabless/openlane, with mpw-3a tag.  I still see large Clock Skew of 1.74 ns which looks to be in the high end.
<pre>Clock bist_clk
Latency      CRPR       Skew
_2021_/CLK ^    3.86 
_2039_/CLK ^      2.12      
                          0.00       1.74
</pre>

When i report timing on these highest skew reporting path, it looks to be around 0.51ns (2.63-2.12), Not sure why report_clock_skew shows 1.74ns skew

<pre>% report_checks -from _2021_ -to _2039_   
Startpoint: _2021_ (rising edge-triggered flip-flop clocked by bist_clk)
Endpoint: _2039_ (rising edge-triggered flip-flop clocked by bist_clk)
Path Group: bist_clk
Path Type: max

  Delay    Time   Description
---------------------------------------------------------
   0.00    0.00   clock bist_clk (rise edge)
   2.63    2.63   clock network delay (propagated)
   0.00    2.63 ^ _2021_/CLK (sky130_fd_sc_hd__dfxtp_1)
   0.70    3.33 v _2021_/Q (sky130_fd_sc_hd__dfxtp_1)
   0.33    3.67 v _1907_/X (sky130_fd_sc_hd__mux2_1)
   0.65    4.31 v _1952_/X (sky130_fd_sc_hd__mux4_2)
   0.00    4.32 v _2039_/D (sky130_fd_sc_hd__dfrtp_1)
           4.32   data arrival time

   8.00    8.00   clock bist_clk (rise edge)
   2.12   10.12   clock network delay (propagated)
  -0.25    9.87   clock uncertainty
   0.47   10.34   clock reconvergence pessimism
          10.34 ^ _2039_/CLK (sky130_fd_sc_hd__dfrtp_1)
   0.07   10.42   library setup time
          10.42   data required time
---------------------------------------------------------
          10.42   data required time
          -4.32   data arrival time
---------------------------------------------------------
           6.10   slack (MET)
</pre>

When I added single operating condition before the clock skew report, the i see clock reporting as 0.51ns which is expected

<pre>% set_operating_conditions -analysis_type single
% report_clock_skew
Clock bist_clk
Latency      CRPR       Skew
_2021_/CLK ^       2.63
_2039_/CLK ^       2.12      
                0.00       0.51
</pre>

Attached the example for your reference
[exp4.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7446236/exp4.tar.gz)

**Comment by donn** [comment]
@Manarabdelaty fyi

**Comment by dralabeing** [comment]
@dineshannayya Can your try with the MPW-3a release tag? This is most likely fixed.

**Comment by donn** [comment]
Staled out.
