### ISSUE TITLE
getting Segmantation fault (core dumped) error during magic compile

### ISSUE THREAD

**Issue by msaideroglu** [The-OpenROAD-Project/OpenLane#725]
When I try to check spm design test results in /openlane/designs/spm/../results/magic, the result of "magic spm.mag", or "magic -rcfile sky130A.magicrc"
it gives -Segmentation fault (core dumped) error
->When I reinstall magic, it solved.

**Comment by Reeaz1998** [comment]
What is the solution ? I am getting the same error
