### ISSUE TITLE
DRC violations

### ISSUE THREAD

**Issue by rahulrbharadwaj** [The-OpenROAD-Project/OpenLane#735]
### Description
I have an analog module which I have layed out in hand using the latest version of magic with no DRC violations. I have called this analog module as a macro in openlane and the ran the flow. At the end of the flow there are DRC violations. The DRC violations are on the standard cells that are already layed out. 

### Environment
```
PDK Version Verification Status: OK

```

### Reproduction Material

[Openlane.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/7602420/Openlane.zip)

### Expected behavior
There must be no DRC violations.

### Logs
```
The log file is included in the tar compressed file.
```

**Comment by vijayank88** [comment]
@rahulrbharadwaj 
follow instruction properly and add your tar file to reproduce the issue.
Given Reproduction Material link is empty.

**Comment by rahulrbharadwaj** [comment]
@vijayank88 can you view the files now?

**Comment by donn** [comment]
Your environment survey is also pretty empty, only including the PDK part and nothing else. We need the whole thing.
