### ISSUE TITLE
Incorrect "Basic test failed" notification after 'make test'

### ISSUE THREAD

**Issue by stevvik** [The-OpenROAD-Project/OpenLane#743]
OpenLane installation with the latest tag 2021.12.01_01.29.55  fails at 'make test' step and returns error that "Basic test failed".
But test design passes successful!

Info from LOG:
--------------------------
make test
...
[SUCCESS]: Flow complete.
Basic test failed
-------------------------

The problem is that the path to resulted GDS file is changed in design directory structure (now it is located in results/finishing dir), but in Makefile the GDS existence is checked by old path (in results/magic dir):

Code from Makefile:
----------------------------
test:
	cd $(OPENLANE_DIR) && \
		$(ENV_COMMAND) sh -c "./flow.tcl -design $(TEST_DESIGN) -tag openlane_test -disable_output -overwrite"
	@[ -f $(OPENLANE_DIR)/designs/$(TEST_DESIGN)/runs/openlane_test/results/magic/$(TEST_DESIGN).gds ] && \
		echo "Basic test passed" || \
		echo "Basic test failed"
-----------------------------

**Comment by donn** [comment]
Fixed in https://github.com/The-OpenROAD-Project/OpenLane/pull/742.
