### ISSUE TITLE
drop -clk_nets in cts.tcl

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/OpenLane#769]
### Description
In cts.tcl you have:
clock_tree_synthesis {*}arg_list\
...
    -clk_nets $::env(CLOCK_NET)\

-clk_nets isn't needed if the clocks are defined in SDC.  CTS will automatically find the clock nets from STA.

### Environment
master

### Reproduction Material
any design

### Expected behavior
simpler flow

**Comment by donn** [comment]
not sure how this affects a situation where someone skips sta but performs cts

**Comment by maliberty** [comment]
Given that you have "read_sdc -echo $::env(CURRENT_SDC)" it hard to see how they avoid it.

**Comment by donn** [comment]
touche. let me look into this further monday
