### ISSUE TITLE
Skipping few steps

### ISSUE THREAD

**Issue by ratul619** [The-OpenROAD-Project/OpenLane#779]
hi , 

I need to skip some steps in openlane , because i have an analog macro which i want to package . 

1) For ONLY analog block - do we need to run openlane ? Or is there a direct way to package in caravel ? 
2) if not , then how to skip PDN and CTS steps ? 

Thanks

**Comment by donn** [comment]
1. For caravel help, please try the sky130 slack community. We can't help you much here.
2. You can't skip steps per se. You can run OpenLane in interactive mode by invoking `flow.tcl -interactive` and then you can run steps manually if you'd need to.
