### ISSUE TITLE
Multiple designs with Sky130 fakerams/SRAMs face 'routing congestion too high' error at Global Routing step

### ISSUE THREAD

**Issue by lakshmi-sathi** [The-OpenROAD-Project/OpenLane#824]
### Description
Designs ([BSG manycore_proc_vanilla](https://github.com/The-OpenROAD-Project/OpenLane/files/7787765/bsg_manycore_proc_vanilla_fakeram.tar.gz), [BlackParrot frontend](https://github.com/The-OpenROAD-Project/OpenLane/files/7787768/bp_fe.tar.gz)) face 'routing congestion too high' error at Global Routing Step. This congestion issue has been occurring on many designs using sky130 fakerams/real SRAMs. Another previous design on which this was faced was a Serv processor design with SRAM macros (Similarly even on other designs with Sky130 SRAMs). This issue was also occurring on _OpenROAD-flow-scripts_ but they have fixed it in this [pull request](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/220). After this fix, all these designs (with sky130 SRAMs) that were failing to pass global routing (on _OpenROAD-flow-scripts_) due to congestion were able to pass global routing easily (on _OpenROAD-flow-scripts_).

The fix they applied was to remove a certain option used to avoid routing too close to macros (it's the 'set_macro_extension' option in the fastroute config). Could this congestion issue on OpenLane also be stemming from the same root cause?
I tried looking through the OpenLane scripts but could not figure out quite how the fasteroute config. might be getting handled.

### Environment
```
Python: v3.8.10
Kernel: Linux v4.19.128-microsoft-standard
Distribution: ubuntu 20.04
Container Engine: docker v20.10.8
OpenLane Git Version: 2021.12.25_01.36.09
---
PDK Version Verification Status: FAILED
Could not find SOURCES file for the installed sky130A PDK.
Traceback (most recent call last):
  File "/mnt/c/Users/LENOVO/Documents/gsocbp/OpenLane/dependencies/verify_versions.py", line 66, in verify_versions
    sources_str = open(sources_file).read()
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/LENOVO/Documents/gsocbp/OpenLane/pdks/sky130A/SOURCES'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/LENOVO/Documents/gsocbp/OpenLane/dependencies/verify_versions.py", line 68, in verify_versions
    raise Exception("Could not find SOURCES file for the installed sky130A PDK.")
Exception: Could not find SOURCES file for the installed sky130A PDK.

Failed to compare PDKs.
---
Git Log (Last 3 Commits)

commit efc75133f0e7ea23424febcdbf8b56203bcef6ab
Author: Donn <me@donn.website>
Date:   Fri Dec 24 13:08:02 2021 +0200

    Typo (#801)

    [skip ci]

commit 16d977225a3982e5e5c7887dfcbb903b21f68b1f
Author: Donn <me@donn.website>
Date:   Fri Dec 24 13:07:50 2021 +0200

    The Perl Purge (#800)

    `cts_simple.pl`, `analyze.pl` and `libtrim.pl` translated as literally as possible to Python.

commit ec1e6bec68a94a0aa37964cf6aa1a62f930eaf66
Author: Donn <me@donn.website>
Date:   Fri Dec 24 01:45:19 2021 +0200

    Update environment survey, allow configuring python versions (#794)

    * Update environment survey

    This updates the issue environment survey to better detect whether it's running inside the OpenLane container or not, and properly discourage people from doing so.

    * Make the version of Python used configurable via environment variable

    [skip ci]
```

### Reproduction Material
* Designs: 
[bsg_manycore_proc_vanilla_fakeram.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7787765/bsg_manycore_proc_vanilla_fakeram.tar.gz)
[bp_fe.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/7787768/bp_fe.tar.gz)

* Command used: `./flow.tcl -design bsg_manycore_proc_vanilla_fakeram`, `./flow.tcl -design bp_fe`

### Expected behavior
These two designs (and the others previously seen to face this issue) easily complete the flow on _OpenROAD-flow-scripts_, so expecting the designs to be able to complete the flow without congestion on OpenLane too.

### Logs
```
[INFO GRT-0102] Iteration 19
[INFO GRT-0126] Overflow report:
[INFO GRT-0127] Total usage          : 1737041
[INFO GRT-0128] Max H overflow       : 7
[INFO GRT-0129] Max V overflow       : 7
[INFO GRT-0130] Max overflow         : 7
[INFO GRT-0131] Number overflow edges: 46803
[INFO GRT-0132] H   overflow         : 31704
[INFO GRT-0133] V   overflow         : 41400
[INFO GRT-0134] Final overflow       : 73104

[WARNING GRT-0227] Reached 20 congestion iterations with less than 15% of reduction between iterations.
[INFO GRT-0104] Minimal overflow 67743 occurring at round 10.
Usage checked
[INFO GRT-0105] Maze routing finished.
Final 2D results:
[INFO GRT-0126] Overflow report:
[INFO GRT-0127] Total usage          : 1737041
[INFO GRT-0128] Max H overflow       : 7
[INFO GRT-0129] Max V overflow       : 7
[INFO GRT-0130] Max overflow         : 7
[INFO GRT-0131] Number overflow edges: 46803
[INFO GRT-0132] H   overflow         : 31704
[INFO GRT-0133] V   overflow         : 41400
[INFO GRT-0134] Final overflow       : 73104

[INFO GRT-0106] Layer assignment begins.
[INFO GRT-0107] Layer assignment finished.
[INFO GRT-0197] Via related to pin nodes: 190337
[INFO GRT-0198] Via related Steiner nodes: 136
[INFO GRT-0199] Via filling finished.
[INFO GRT-0111] Final number of vias: 272661
[INFO GRT-0112] Final usage 3D: 2555024
[ERROR GRT-0118] Routing congestion too high.
Error: groute.tcl, 66 GRT-0118
[ERROR]: during executing openroad script /openlane/scripts/openroad/groute.tcl
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
child process exited abnormally

```

### Congestion Map (taken using OpenROAD GUI)
Congestion map of bsg_manycore_proc_vanilla_fakeram design (taken at global route step)
![congestion_map_global_route_issue_macros_together](https://user-images.githubusercontent.com/58559090/147637464-f734486c-4cd9-4345-a703-235a05f420fb.png)

**Comment by tspyrou** [comment]
Propagate macro_extension from openroad to openlane as shown in the pull request.
