### ISSUE TITLE
Openlane should have way to specify size of placement halo around macros

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenLane#832]
I'm having global routing issues around some hard macros in Microwatt. On the OpenROAD flow, you can specify a placement halo around macros, giving more resources to route out of them. I can't find a way to do this in Openlane.

**Comment by donn** [comment]
Will look into it- do you have a link to the requisite variable(s) in ORFS?

**Comment by maliberty** [comment]
MACRO_PLACE_HALO & MACRO_PLACE_CHANNEL

**Comment by antonblanchard** [comment]
Thanks @donn. However what happens if we are manually placing macros (`MACRO_PLACEMENT_CFG`)? `manual_macro_place.py` inserts macros directly into the database, and doesn't use openroad.

**Comment by antonblanchard** [comment]
The syntax for the Openroad and Openlane manual macro placement files is different unfortunately.
