### ISSUE TITLE
Update PDK parameters for global placement and global routing

### ISSUE THREAD

**Issue by tspyrou** [The-OpenROAD-Project/OpenLane#848]
### Prompt

Update PDK parameters for global placement and global routing

### Proposal

[Efabless should study these changes to the default parameters in global placement padding fastroute parameters which we found improve results.](https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/commit/05ac93113f01a496c29f51775595cc5727dc5c62)

### Alternatives

None

**Comment by donn** [comment]
Routing adjustments added to #856, cell pad thing I think needs a dedicated PR

**Comment by kareefardi** [comment]
Padding now matches ORFS.
