### ISSUE TITLE
Keep Track Of Warnings

### ISSUE THREAD

**Issue by donn** [The-OpenROAD-Project/OpenLane#850]
Reported by @kareefardi 

### Prompt
Warnings are printed mid-flow, where they can easily be ignored.

### Proposal
Warnings should be also be stored in an individual log file and printed at the very end.

**Comment by dralabeing** [comment]
@donn Does OpenLane use a logger like spdlog (like OpenROAD- https://openroad.readthedocs.io/en/latest/contrib/Logger.html?highlight=logger)

**Comment by donn** [comment]
We do not, no.
