### ISSUE TITLE
Macro not found in Macro placement

### ISSUE THREAD

**Issue by microSharjeel** [The-OpenROAD-Project/OpenLane#852]
Hi,
I am trying to place a already hardened Macro in my design. I have followed the manual_macro_placement_test design example and am encountering the following error
Traceback (most recent call last):
  File "/openLANE_flow/scripts/manual_macro_place.py", line 119, in <module>
    assert not macros, ("Macros not found:", macros)
AssertionError: ('Macros not found:', {'ram': ['5590', '168230', 'N']})
If anyone can guide me what is the problem why OpenLane can not find the Macro although the .lef and .gds files are there in Macros folder
Kindly guide
regards

**Comment by vijayank88** [comment]
environment survey must and re-producible tar file must to debug the issue

**Comment by vijayank88** [comment]
@microSharjeel  are you trying built-in example or your own design?
If its your own design mean need re-producible tar file needed with environment survey

**Comment by microSharjeel** [comment]
Thanks for reply 
I am attaching the tar of the design since the design is my own.  I am just trying to place macros of an SRAM in my design the .gds and .lef files are there in the Macros
regard
[iob_sp_ram_be.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/7829292/iob_sp_ram_be.zip)
s

**Comment by microSharjeel** [comment]
Are you able to reproduce the error 
best regards

**Comment by vijayank88** [comment]
@microSharjeel 
Refer built-in example manual_macro_placement design from openlane, it will work.
From your config.tcl dont use both DIE_AREA and FP_CORE_UTIL... 
Next src/*.v add (*blackbox*) before module definition. Format available in built-in example

**Comment by maliberty** [comment]
Test cases should be packaged with https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/using_or_issue.md

**Comment by microSharjeel** [comment]
This issue is resolved by following the built in example of OpenLane

**Comment by 0616ygh** [comment]
hello If possible, I would like to know how you finally solved this problem? I encountered the same error as you, also using openRAM using sky water130. Thanks a million!!

**Comment by microSharjeel** [comment]
@0616ygh  can we connect on google hangout etc I hope it will be mutually beneficial

**Comment by 0616ygh** [comment]
@microSharjeel I'm sorry but I don't have a google hangout...I'm a student from China mainland, we don't have hangout QAQ
My question is that after I read Openlane->design->manual_macro_placement_test, I find I don't have :

set ::env(MACRO_PLACEMENT_CFG) $::env(DESIGN_DIR)/macro_placement.cfg
set ::env(BASE_SDC_FILE) $::env(DESIGN_DIR)/base.sdc

these 2 files can't be found in OpenRAM package...
![1](https://user-images.githubusercontent.com/97427070/148781166-1316e236-96d1-4ab2-835e-faa12f7cb64e.png)

**Comment by 0616ygh** [comment]
@microSharjeel Thx for your reply~

**Comment by 28aashish** [comment]
@microSharjeel,
 I am getting errors after Resizer Timing Optimizations 

"[ERROR GRT-0029] Pin ctrlStorage/dout0[0] does not have geometries below the max routing layer (met5).
"
 Description of my design:-
"Designing a controller with custom size memory.SRAM Memory was created with the help of OpenRAM "
