### ISSUE TITLE
[ERROR MPL-0004] No macros found.

### ISSUE THREAD

**Issue by 0616ygh** [The-OpenROAD-Project/OpenLane#857]
When I run Openlane for my RTL design, the tool generated an error log:
[ERROR MPL-0004] No macros found.
Error: basic_mp.tcl, 28 MPL-0004
and I found the "basic_mp.tcl",line 28 is:macro_placement -channel {0 0} -halo {0 0}
I don't know why this bug occurs....

**Comment by vijayank88** [comment]
@0616ygh 
Refer built-in example manual_macro_placement design from openlane, it will work.
If still error repeats, provide test cases should be packaged with https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/using_or_issue.md

**Comment by 0616ygh** [comment]
Thank you a lot ! I will try your method and debug for it. Thank you a lot

**Comment by 0616ygh** [comment]
Thx you very much. But I find I don't have macro_placement.cfg and base.sdc I don't understand how these parameters are set
![1641821211551](https://user-images.githubusercontent.com/97427070/148773636-f73cedbf-d111-49d3-ae25-6c924f7fd32b.jpg)

**Comment by maliberty** [comment]
Just because you can work around the issue with manual macro placement doesn't mean there isn't a problem with automatic macro placement.  If you want that looked at your should provide a test case.  If you need further info you should reopen the issue.
