### ISSUE TITLE
Update netgen and magic

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenLane#898]
There have been some big improvements to netgen performance over the last month, and it would be good to get them into openlane. Magic has had a number of fixes too, including for an LVS issue I'm hitting quite a lot on openlane.

**Comment by donn** [comment]
Magic will need a little more doing. I've went ahead and upped netgen for now.

**Comment by proppy** [comment]
@donn what would be missing to update magic (I'd be happy to help).
@antonblanchard can you detail the LVS issue you're hitting (I'm getting some to using w/ the latest version of `magic` + `open_pdks` and I'm curious if those are related)

**Comment by donn** [comment]
@proppy See my PR
