### ISSUE TITLE
Add more files to finishing directory

### ISSUE THREAD

**Issue by kareefardi** [The-OpenROAD-Project/OpenLane#925]
### Prompt

These are the files in finishing directory:
```
OpenLane Container (169346f):/openlane/designs/spm/runs/RUN_2022.02.16_15.11.53/results/finishing$ ls
spm.drc.mag  spm.gds  spm.klayout.gds  spm.lef  spm.lef.mag  spm.lef.spice  spm.lyp  spm.mag  spm.magic.gds  spm.spice
```
Some views/artifacts are missing, such as `.v`, `.sdc` and `.sdf`.

### Proposal

Add missing views/artifacts to finishing directory.

**Comment by donn** [comment]
So, I forgot that I created a folder called "final" that does exactly that. 

Oops.
