### ISSUE TITLE
Update OpenROAD to fix LVS issue

### ISSUE THREAD

**Issue by antonblanchard** [The-OpenROAD-Project/OpenLane#932]
Hi @donn, I hate to ask for yet another update, but I'm hitting the following OpenROAD issue on a few of my designs:

https://github.com/The-OpenROAD-Project/OpenROAD/issues/1577

This is now fixed upstream so an update of OpenROAD should fix it.

**Comment by donn** [comment]
Never apologize for being helpful. Thank you.

**Comment by antonblanchard** [comment]
Thanks @donn!
