### ISSUE TITLE
Detailed placement failed

### ISSUE THREAD

**Issue by vijayank88** [The-OpenROAD-Project/OpenLane#948]
### Description
GDS file generated successfully with OL tag: [2022.02.16_01.55.24](https://github.com/The-OpenROAD-Project/OpenLane/releases/tag/2022.02.16_01.55.24) but for latest OL tag: [2022.02.21_02.33.47](https://github.com/The-OpenROAD-Project/OpenLane/releases/tag/2022.02.21_02.33.47) detailed placement got failed.

### Environment
```
Kernel: Linux v3.10.0-1160.49.1.el7.x86_64
Distribution: centos 7
Python: v3.6.8 (OK)
Container Engine: docker v20.10.12 (OK)
OpenLane Git Version: 2022.02.21_02.33.47
pip:click: INSTALLED
pip:pyyaml: INSTALLED
pip:venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

e40929f 2022-02-20T10:29:53+02:00 ECO Flow Fix (#940) - donghl17 -  (HEAD -> master, tag: 2022.02.21_02.33.47, origin/master, origin/HEAD)
a7d97cc 2022-02-19T10:00:15+02:00 Update README.md (#939) - wale soyinka -  (tag: 2022.02.20_02.17.26)
58f206f 2022-02-18T16:02:03+02:00 Update Magic, Open_PDKS (#917) - Donn -  (tag: 2022.02.19_02.27.52)

```

### Reproduction Material
* Upload a tarball containing the relevant design. 
[DPL_issue_jacaranda8.zip](https://github.com/The-OpenROAD-Project/OpenLane/files/8116365/DPL_issue_jacaranda8.zip)

* List the commands used to run the design.
* unzip the file and goto openroad_issue_reproducible
* openroad> source run.tcl

### Expected behavior
Has previous OL tag ran successfully, looking for current tag not produce this issue.

### Logs
```
[INFO ODB-0222] Reading LEF file: ./tmp/merged_unpadded.lef
[INFO ODB-0223]     Created 13 technology layers
[INFO ODB-0224]     Created 25 technology vias
[INFO ODB-0225]     Created 441 library cells
[INFO ODB-0226] Finished LEF file:  ./tmp/merged_unpadded.lef
[INFO ODB-0127] Reading DEF file: ./in.def
[INFO ODB-0128] Design: computer
[INFO ODB-0130]     Created 609 pins.
[INFO ODB-0131]     Created 52199 components and 267155 component-terminals.
[INFO ODB-0132]     Created 2 special nets and 181360 connections.
[INFO ODB-0133]     Created 23089 nets and 85565 connections.
[INFO ODB-0134] Finished DEF file: ./in.def
[ERROR DPL-0019] detailed placement failed on _38541_
Error: opendp.tcl, 32 DPL-0019

```

**Comment by vijayank88** [comment]
@maliberty FYI

**Comment by maliberty** [comment]
The density is too high.  You should either add the diode to the padding exclude list or use a lower density during global placement.  I would do the former.

**Comment by dralabeing** [comment]
@vijayank88 looks like this is resolved now for both the options.
