### ISSUE TITLE
magic error

### ISSUE THREAD

**Issue by Sya0** [The-OpenROAD-Project/OpenLane#974]
```
Kernel: Linux v5.11.0-49-generic
Distribution: ubuntu 21.04
Python: v3.9.5 (OK)
Container Engine: docker v20.10.7 (OK)
OpenLane Git Version: -dev
pip:click: INSTALLED
pip:pyyaml: INSTALLED
pip:venv: INSTALLED
---
PDK Version Verification Status: OK
---
Git Log (Last 3 Commits)

e4bfdd7 2022-02-22T16:59:14-03:00 Remove pip install, no longer needed (#953) - Vitor Bandeira -  (grafted, HEAD, tag: 2022.02.23_02.50.41) 
```
I have an error during openlane which is below:
```
[ERROR]: during executing: "magic -noconsole -dnull -rcfile /home/sukruuzun/caravel_pdk/sky130A/libs.tech/magic/sky130A.magicrc /openlane/scripts/magic/gds_pointers.tcl </dev/null |& tee >&@stdout /project/openlane/user_project_wrapper/runs/user_project_wrapper/logs/finishing/20-gds_ptrs.log"                                                       
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
child killed: kill signal 
```

**Comment by Sya0** [comment]
@vijayank88, the error is not coming from OpenROAD, it is from magic scripts so or_issue script is not working for my situation but I have attached my last log file.
[20-gds_ptrs.log](https://github.com/The-OpenROAD-Project/OpenLane/files/8168806/20-gds_ptrs.log)

**Comment by vijayank88** [comment]
@Sya0 
Please find gds_pointers.tcl [here](https://github.com/The-OpenROAD-Project/OpenLane/blob/master/scripts/magic/gds_pointers.tcl)
Attach file : ..../results/finishing/<name>.magic.gds
1.source the above tcl file and add required input files in separate folder
2. If issue re-produced locally with *.gds file, attach the test case here

**Comment by Sya0** [comment]
I fixed above issue but new errors from OpenROAD. 
[openroad_issue_reproducible.tar.gz](https://github.com/The-OpenROAD-Project/OpenLane/files/8169014/openroad_issue_reproducible.tar.gz)
[11-global.log](https://github.com/The-OpenROAD-Project/OpenLane/files/8169034/11-global.log)

**Comment by vijayank88** [comment]
@Sya0 
Are you using mpw-5c tag right?

**Comment by Sya0** [comment]
@vijayank88, yes

**Comment by vijayank88** [comment]
@Sya0  can you share your repo details to clone and test it locally?

**Comment by vijayank88** [comment]
@Sya0 
Found your problem. Plz update your `config.tcl` for following variables:
```
set ::env(RT_MAX_LAYER) {5};
```
to
```
set ::env(RT_MAX_LAYER) {met5};
```
works fine at my end.

**Comment by Sya0** [comment]
@vijayank88 
Interesting.. The error of first message is repeated on my local. It is stopped at step 20 which is gds_ptrs again.
```
[ERROR]: during executing: "magic -noconsole -dnull -rcfile /home/sukruuzun/caravel_pdk/sky130A/libs.tech/magic/sky130A.magicrc /openlane/scripts/magic/gds_pointers.tcl </dev/null |& tee >&@stdout /project/openlane/user_project_wrapper/runs/user_project_wrapper/logs/finishing/20-gds_ptrs.log"                                                       
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
child killed: kill signal
```
By the way, how could you fix such problems? I could not guess that the previous error was due to the `set ::env(RT_MAX_LAYER) {5};` line. Is there any approach that you specifically apply ?

**Comment by vijayank88** [comment]
> @Sya0 Please find gds_pointers.tcl [here](https://github.com/The-OpenROAD-Project/OpenLane/blob/master/scripts/magic/gds_pointers.tcl) Attach file : ..../results/finishing/.magic.gds 1.source the above tcl file and add required input files in separate folder 2. If issue re-produced locally with *.gds file, attach the test case here

attach required files based on this script @Sya0

**Comment by vijayank88** [comment]
> @vijayank88 Interesting.. The error of first message is repeated on my local. It is stopped at step 20 which is gds_ptrs again. I only changed the config.tcl under user_project_wrapper.
> 
> ```
> [ERROR]: during executing: "magic -noconsole -dnull -rcfile /home/sukruuzun/caravel_pdk/sky130A/libs.tech/magic/sky130A.magicrc /openlane/scripts/magic/gds_pointers.tcl </dev/null |& tee >&@stdout /project/openlane/user_project_wrapper/runs/user_project_wrapper/logs/finishing/20-gds_ptrs.log"                                                       
> [ERROR]: Exit code: 1
> [ERROR]: Last 10 lines:
> child killed: kill signal
> ```
> 
> By the way, how could you fix such problems? I mean, I could not guess that the previous error was due to the `set ::env(RT_MAX_LAYER) {5};` line. Is there any approach that you specifically apply ?

From the error log
```
[INFO]: Setting signal min routing layer to: met1 and clock min routing layer to met1. 
[INFO]: Setting signal max routing layer to: 5 and clock max routing layer to 5. 
```
max routing layer to 5 is an integer value. Tool not able to use right metal layer. So the right name is `met5`. 
check min routing layer to `met1`

**Comment by Sya0** [comment]
@vijayank88, sorry but I can't understand what to do. Should I attach .magic.gds and .tcl file?

**Comment by vijayank88** [comment]
@Sya0 
Attach  `results/finishing/<name>.magic.gds`

**Comment by Sya0** [comment]
@vijayank88, I think, my file is not small enough, because it gives me error. github/hub/issues/1479, it is common problem.
I give you drive [link](https://drive.google.com/file/d/1xZShDq-EzU87-LOEhg75fSCNGiCg373Z/view?usp=sharing).

**Comment by vijayank88** [comment]
@Sya0 
I don't have any issues while running `gds_pointers.tcl`  in batch mode.
Can you try once again ?
Check parallel how much RAM used while running your design.

**Comment by vijayank88** [comment]
Inside OpenLane Docker the command I tried:
```
magic -noconsole -dnull -rcfile /home/vijayan/OPENROAD_FLOW/OLFS/OpenLane/pdks/sky130A/libs.tech/magic/sky130A.magicrc ./gds_pointers.tcl > ./magic.log
```
`gds_pointers.tcl` as follows:
```
drc off

gds readonly true
gds rescale false

# This comes afterwards, so that it would contain GDS pointers
# And yes, we need to re-read the GDS we just generated...
gds read ./user_project_wrapper.magic.gds
cellname filepath user_project_wrapper ./finishing
save

set final_filepath ./finishing/gds_ptrs.mag

file rename -force ./finishing/user_project_wrapper.mag $final_filepath

puts "\[INFO\]: Wrote $final_filepath including GDS pointers."
exit 0

```

**Comment by Sya0** [comment]
You used efabless/openlane:latest, right ?

**Comment by vijayank88** [comment]
@Sya0 
I've tested with latest tag  2022.03.02_02.59.05.
I'll install mpw-5c and let you know...

**Comment by vijayank88** [comment]
@Sya0 
mpw-5c is efabless/openlane:2022.02.23_02.50.41
I'm not able to reproduce issue at our end.

Create a valid test case and re-open this issue.
Thanks...
