### ISSUE TITLE
mpw-5c are very noisy for output logs

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenLane#977]
### Prompt

running make user_project_wrapper generates 100k lines of logs

### Proposal

show only errors and top level information. Each tool can log into the log directories as before.

**Comment by kareefardi** [comment]
I believe that's not an openlane issue. It's rather openlane _usage_ issue. Openlane has `-disable_output` in which it only prints the contents of `openlane.log`. Also for mpw-5c, there is a bug where `make user_project_wrapper` or `make user_project_example` or any `make <block>` will actually run all the blocks, fixed here https://github.com/efabless/caravel_user_project/pull/89/. That's one more reason why the logs you are seeing are huge

**Comment by donn** [comment]
Still, the default should be the saner option. `-disable_output` should be inverted into `-verbose`.

**Comment by donn** [comment]
Issue fixed in main- as this will continue to affect mpw-5c, the issue will remain open for documentation purposes.

**Comment by proppy** [comment]
> ... -disable_output (now the default behavior)

While it's nice to have less spammy output, it does make it harder to get a sense of how much progress the tooling doing, esp. for long running operation like `[INFO]: Running Detailed Routing...`.

Should we open another issue to discuss further improvement or is that ok to keep this issue open?

(I also just happened to stumble upon https://clig.dev by @cli-guidelines w/ some good recommendations about output management https://clig.dev/#output and progress indicator https://clig.dev/#robustness-guideline)

**Comment by donn** [comment]
You can just add `-verbose`, then.

I do agree about an exception for routing though. Maybe the OR team can add a more tty-friendly output format..? @maliberty Thoughts?

**Comment by proppy** [comment]
@donn do you have some hints on how the `-verbose` flag works (does it take a level? or is that just a all of nothing thing?); it doesn't seems to affect the output for me.

**Comment by proppy** [comment]
@donn my bad it's already documented in https://github.com/The-OpenROAD-Project/OpenLane/blob/master/docs/source/openlane_commands.md#general-commands, I just had to set it to something > `1` :)
