### ISSUE TITLE
add back the symlink lef file to the output results directories where def files are

### ISSUE THREAD

**Issue by mattvenn** [The-OpenROAD-Project/OpenLane#987]
### Prompt
A clear and concise description of what shortcoming you feel OpenLane has.

I used to be able to use klayout to open def files, but now the tmp-merged.lef is no longer symlinked, the cells aren't shown and there are a lot of warnings on the command line

### Proposal

put back the tmp-merged.lef file symlink wherever there are def files.

**Comment by donn** [comment]
An open_in_klayout function has been added to OpenLane that loads klayout from the commandline with the proper LEF file.

The symlinking was a bit janky, frankly... Made copying, pasting, tarring, etc. too volatile. Also placed constraints on where DEF files can be placed.
